// <auto-generated>
// This file was automatically generated on 2026-04-09 15:38:14 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

// Generated parser imports
import 'parsers/absorbpointer_parser.dart';
import 'parsers/actions_parser.dart';
import 'parsers/align_parser.dart';
import 'parsers/androidviewsurface_parser.dart';
import 'parsers/aspectratio_parser.dart';
import 'parsers/automatickeepalive_parser.dart';
import 'parsers/backdropfilter_parser.dart';
import 'parsers/backdropgroup_parser.dart';
import 'parsers/baseline_parser.dart';
import 'parsers/blocksemantics_parser.dart';
import 'parsers/center_parser.dart';
import 'parsers/clipoval_parser.dart';
import 'parsers/clippath_parser.dart';
import 'parsers/cliprect_parser.dart';
import 'parsers/cliprrect_parser.dart';
import 'parsers/cliprsuperellipse_parser.dart';
import 'parsers/coloredbox_parser.dart';
import 'parsers/colorfiltered_parser.dart';
import 'parsers/column_parser.dart';
import 'parsers/compositedtransformfollower_parser.dart';
import 'parsers/compositedtransformtarget_parser.dart';
import 'parsers/constrainedbox_parser.dart';
import 'parsers/container_parser.dart';
import 'parsers/custommultichildlayout_parser.dart';
import 'parsers/custompaint_parser.dart';
import 'parsers/customsinglechildlayout_parser.dart';
import 'parsers/decoratedbox_parser.dart';
import 'parsers/decoratedsliver_parser.dart';
import 'parsers/defaultassetbundle_parser.dart';
import 'parsers/defaultselectionstyle_parser.dart';
import 'parsers/defaulttexteditingshortcuts_parser.dart';
import 'parsers/defaulttextheightbehavior_parser.dart';
import 'parsers/defaulttextstyle_parser.dart';
import 'parsers/directionality_parser.dart';
import 'parsers/displayfeaturesubscreen_parser.dart';
import 'parsers/dragboundary_parser.dart';
import 'parsers/draggablescrollableactuator_parser.dart';
import 'parsers/excludefocus_parser.dart';
import 'parsers/excludesemantics_parser.dart';
import 'parsers/expanded_parser.dart';
import 'parsers/fittedbox_parser.dart';
import 'parsers/flex_parser.dart';
import 'parsers/flexible_parser.dart';
import 'parsers/flow_parser.dart';
import 'parsers/fractionallysizedbox_parser.dart';
import 'parsers/fractionaltranslation_parser.dart';
import 'parsers/gridpaper_parser.dart';
import 'parsers/icontheme_parser.dart';
import 'parsers/ignorebaseline_parser.dart';
import 'parsers/ignorepointer_parser.dart';
import 'parsers/imagefiltered_parser.dart';
import 'parsers/indexedsemantics_parser.dart';
import 'parsers/indexedstack_parser.dart';
import 'parsers/intrinsicheight_parser.dart';
import 'parsers/intrinsicwidth_parser.dart';
import 'parsers/keepalive_parser.dart';
import 'parsers/keyedsubtree_parser.dart';
import 'parsers/limitedbox_parser.dart';
import 'parsers/listbody_parser.dart';
import 'parsers/localizations_parser.dart';
import 'parsers/lookupboundary_parser.dart';
import 'parsers/mergesemantics_parser.dart';
import 'parsers/metadata_parser.dart';
import 'parsers/offstage_parser.dart';
import 'parsers/opacity_parser.dart';
import 'parsers/overflowbox_parser.dart';
import 'parsers/padding_parser.dart';
import 'parsers/pagestorage_parser.dart';
import 'parsers/performanceoverlay_parser.dart';
import 'parsers/physicalmodel_parser.dart';
import 'parsers/physicalshape_parser.dart';
import 'parsers/pinnedheadersliver_parser.dart';
import 'parsers/placeholder_parser.dart';
import 'parsers/platformselectableregioncontextmenu_parser.dart';
import 'parsers/platformviewsurface_parser.dart';
import 'parsers/positioned_parser.dart';
import 'parsers/positioneddirectional_parser.dart';
import 'parsers/preferredsize_parser.dart';
import 'parsers/rawgesturedetector_parser.dart';
import 'parsers/rawmagnifier_parser.dart';
import 'parsers/rawmenuanchorgroup_parser.dart';
import 'parsers/rawview_parser.dart';
import 'parsers/renderobjecttowidgetadapter_parser.dart';
import 'parsers/reorderabledelayeddragstartlistener_parser.dart';
import 'parsers/reorderabledragstartlistener_parser.dart';
import 'parsers/repaintboundary_parser.dart';
import 'parsers/restorationscope_parser.dart';
import 'parsers/rootrestorationscope_parser.dart';
import 'parsers/rootwidget_parser.dart';
import 'parsers/rotatedbox_parser.dart';
import 'parsers/row_parser.dart';
import 'parsers/safearea_parser.dart';
import 'parsers/scrollnotificationobserver_parser.dart';
import 'parsers/selectionregistrarscope_parser.dart';
import 'parsers/semanticsdebugger_parser.dart';
import 'parsers/sensitivecontent_parser.dart';
import 'parsers/sharedappdata_parser.dart';
import 'parsers/sizechangedlayoutnotifier_parser.dart';
import 'parsers/sizedbox_parser.dart';
import 'parsers/sizedoverflowbox_parser.dart';
import 'parsers/slivercrossaxisgroup_parser.dart';
import 'parsers/sliverensuresemantics_parser.dart';
import 'parsers/sliverfillremaining_parser.dart';
import 'parsers/sliverfillviewport_parser.dart';
import 'parsers/sliverfixedextentlist_parser.dart';
import 'parsers/slivergrid_parser.dart';
import 'parsers/sliverignorepointer_parser.dart';
import 'parsers/sliverlist_parser.dart';
import 'parsers/slivermainaxisgroup_parser.dart';
import 'parsers/sliveroffstage_parser.dart';
import 'parsers/sliveropacity_parser.dart';
import 'parsers/sliverpadding_parser.dart';
import 'parsers/sliverpersistentheader_parser.dart';
import 'parsers/sliverprototypeextentlist_parser.dart';
import 'parsers/slivertoboxadapter_parser.dart';
import 'parsers/spacer_parser.dart';
import 'parsers/stack_parser.dart';
import 'parsers/stretcheffect_parser.dart';
import 'parsers/tablecell_parser.dart';
import 'parsers/tapregionsurface_parser.dart';
import 'parsers/texture_parser.dart';
import 'parsers/tickermode_parser.dart';
import 'parsers/title_parser.dart';
import 'parsers/transform_parser.dart';
import 'parsers/unconstrainedbox_parser.dart';
import 'parsers/unmanagedrestorationscope_parser.dart';
import 'parsers/view_parser.dart';
import 'parsers/viewanchor_parser.dart';
import 'parsers/viewcollection_parser.dart';
import 'parsers/visibility_parser.dart';

// Generated parser instances - add to DynamicWidgetBuilder._parsers list
// Note: These are stub implementations that return placeholders.
// Manual implementations in /parsers directory should be used when available.
final generatedParsers = [
  AbsorbPointerParser(),
  ActionsParser(),
  AlignParser(),
  AndroidViewSurfaceParser(),
  AspectRatioParser(),
  AutomaticKeepAliveParser(),
  BackdropFilterParser(),
  BackdropGroupParser(),
  BaselineParser(),
  BlockSemanticsParser(),
  CenterParser(),
  ClipOvalParser(),
  ClipPathParser(),
  ClipRectParser(),
  ClipRRectParser(),
  ClipRSuperellipseParser(),
  ColoredBoxParser(),
  ColorFilteredParser(),
  ColumnParser(),
  CompositedTransformFollowerParser(),
  CompositedTransformTargetParser(),
  ConstrainedBoxParser(),
  ContainerParser(),
  CustomMultiChildLayoutParser(),
  CustomPaintParser(),
  CustomSingleChildLayoutParser(),
  DecoratedBoxParser(),
  DecoratedSliverParser(),
  DefaultAssetBundleParser(),
  DefaultSelectionStyleParser(),
  DefaultTextEditingShortcutsParser(),
  DefaultTextHeightBehaviorParser(),
  DefaultTextStyleParser(),
  DirectionalityParser(),
  DisplayFeatureSubScreenParser(),
  DragBoundaryParser(),
  DraggableScrollableActuatorParser(),
  ExcludeFocusParser(),
  ExcludeSemanticsParser(),
  ExpandedParser(),
  FittedBoxParser(),
  FlexParser(),
  FlexibleParser(),
  FlowParser(),
  FractionallySizedBoxParser(),
  FractionalTranslationParser(),
  GridPaperParser(),
  IconThemeParser(),
  IgnoreBaselineParser(),
  IgnorePointerParser(),
  ImageFilteredParser(),
  IndexedSemanticsParser(),
  IndexedStackParser(),
  IntrinsicHeightParser(),
  IntrinsicWidthParser(),
  KeepAliveParser(),
  KeyedSubtreeParser(),
  LimitedBoxParser(),
  ListBodyParser(),
  LocalizationsParser(),
  LookupBoundaryParser(),
  MergeSemanticsParser(),
  MetaDataParser(),
  OffstageParser(),
  OpacityParser(),
  OverflowBoxParser(),
  PaddingParser(),
  PageStorageParser(),
  PerformanceOverlayParser(),
  PhysicalModelParser(),
  PhysicalShapeParser(),
  PinnedHeaderSliverParser(),
  PlaceholderParser(),
  PlatformSelectableRegionContextMenuParser(),
  PlatformViewSurfaceParser(),
  PositionedParser(),
  PositionedDirectionalParser(),
  PreferredSizeParser(),
  RawGestureDetectorParser(),
  RawMagnifierParser(),
  RawMenuAnchorGroupParser(),
  RawViewParser(),
  RenderObjectToWidgetAdapterParser(),
  ReorderableDelayedDragStartListenerParser(),
  ReorderableDragStartListenerParser(),
  RepaintBoundaryParser(),
  RestorationScopeParser(),
  RootRestorationScopeParser(),
  RootWidgetParser(),
  RotatedBoxParser(),
  RowParser(),
  SafeAreaParser(),
  ScrollNotificationObserverParser(),
  SelectionRegistrarScopeParser(),
  SemanticsDebuggerParser(),
  SensitiveContentParser(),
  SharedAppDataParser(),
  SizeChangedLayoutNotifierParser(),
  SizedBoxParser(),
  SizedOverflowBoxParser(),
  SliverCrossAxisGroupParser(),
  SliverEnsureSemanticsParser(),
  SliverFillRemainingParser(),
  SliverFillViewportParser(),
  SliverFixedExtentListParser(),
  SliverGridParser(),
  SliverIgnorePointerParser(),
  SliverListParser(),
  SliverMainAxisGroupParser(),
  SliverOffstageParser(),
  SliverOpacityParser(),
  SliverPaddingParser(),
  SliverPersistentHeaderParser(),
  SliverPrototypeExtentListParser(),
  SliverToBoxAdapterParser(),
  SpacerParser(),
  StackParser(),
  StretchEffectParser(),
  TableCellParser(),
  TapRegionSurfaceParser(),
  TextureParser(),
  TickerModeParser(),
  TitleParser(),
  TransformParser(),
  UnconstrainedBoxParser(),
  UnmanagedRestorationScopeParser(),
  ViewParser(),
  ViewAnchorParser(),
  ViewCollectionParser(),
  VisibilityParser(),
];
