// <auto-generated>
// This file was automatically generated on 2026-04-09 15:37:29 UTC
// DO NOT EDIT - Changes will be overwritten
// Contains generated parser utility functions
// </auto-generated>

import 'dart:ffi' hide Size;
import 'dart:ui';
import 'package:ffi/ffi.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter/gestures.dart';  // For gesture callbacks
import 'package:flutter/rendering.dart';  // For PlatformViewHitTestBehavior, PointerSignalEventListener, etc.
import 'package:flutter/services.dart';  // For PointerEnterEventListener, PlatformViewCreatedCallback, etc.
import 'package:flutter_module/mauiRenderer.dart' show invokeHandleAction;  // For callback invocation
import 'flutter_sharp_structs.dart';
import 'utils.dart' show parseBlendMode;
export 'utils.dart' show parseBlendMode, parseBoxFit, parseBrightness, parseClip, parseFlexFit, parseHitTestBehavior, parseMaterialTapTargetSize, parseScrollViewKeyboardDismissBehavior, parseTextCapitalization;

// Struct imports
import 'structs/alignmentdirectional_struct.dart';
import 'structs/alignmentgeometry_struct.dart';
import 'structs/borderradiusdirectional_struct.dart';
import 'structs/borderradiusgeometry_struct.dart';
import 'structs/borderradius_struct.dart';
import 'structs/boxconstraints_struct.dart';
import 'structs/boxdecoration_struct.dart';
import 'structs/decoration_struct.dart';
import 'structs/edgeinsetsdirectional_struct.dart';
import 'structs/edgeinsetsgeometry_struct.dart';
import 'structs/edgeinsets_struct.dart';
import 'structs/gradient_struct.dart';
import 'structs/lineargradient_struct.dart';
import 'structs/matrix4_struct.dart';
import 'structs/offset_struct.dart';
import 'structs/radialgradient_struct.dart';
import 'structs/radius_struct.dart';
import 'structs/rect_struct.dart';
import 'structs/shapedecoration_struct.dart';
import 'structs/size_struct.dart';
import 'structs/sweepgradient_struct.dart';
import 'structs/textstyle_struct.dart';
import 'structs/alignment_struct.dart' as generated_alignment;

/// Parses int from FFI type.
int parseInt(int value) {
  return value;
}


/// Parses double from FFI type.
double parseDouble(double value) {
  return value;
}


/// Parses bool from FFI type.
bool parseBool(int value) {
  return value != 0;
}


/// Parses num from FFI type.
num parseNum(dynamic value) {
  return value as num;
}


/// Parses Duration from FFI type.
Duration parseDuration(int milliseconds) {
  return Duration(milliseconds: milliseconds);
}


/// Parses DateTime from FFI type.
DateTime parseDateTime(int millisecondsSinceEpoch) {
  return DateTime.fromMillisecondsSinceEpoch(millisecondsSinceEpoch);
}


/// Parses Color from ColorStruct.
Color parseColor(ColorStruct struct) {
  return Color.fromARGB(struct.alpha, struct.red, struct.green, struct.blue);
}


/// Parses MaterialColor.
/// TODO: This parser needs manual implementation.
MaterialColor? parseMaterialColor(dynamic value) {
  // TODO: Implement parseMaterialColor
  // CSharp type: 
  print('WARNING: parseMaterialColor is not implemented yet');
  return null;
}

/// Parses MaterialStateProperty.
/// TODO: This parser needs manual implementation.
MaterialStateProperty? parseMaterialStateProperty(dynamic value) {
  // TODO: Implement parseMaterialStateProperty
  // CSharp type: 
  print('WARNING: parseMaterialStateProperty is not implemented yet');
  return null;
}

/// Parses ThemeData.
/// TODO: This parser needs manual implementation.
ThemeData? parseThemeData(dynamic value) {
  // TODO: Implement parseThemeData
  // CSharp type: 
  print('WARNING: parseThemeData is not implemented yet');
  return null;
}

/// Parses IconData.
/// TODO: This parser needs manual implementation.
IconData? parseIconData(dynamic value) {
  // TODO: Implement parseIconData
  // CSharp type: 
  print('WARNING: parseIconData is not implemented yet');
  return null;
}

/// Parses EdgeInsets from EdgeInsetsStruct.
EdgeInsets parseEdgeInsets(EdgeInsetsStruct struct) {
  return EdgeInsets.fromLTRB(struct.left, struct.top, struct.right, struct.bottom);
}


/// Parses EdgeInsetsGeometry from EdgeInsetsGeometryStruct.
EdgeInsetsGeometry parseEdgeInsetsGeometry(EdgeInsetsGeometryStruct struct) {
  return _parseEdgeInsetsGeometryValue(struct);
}


/// Parses Alignment from AlignmentStruct.
Alignment parseAlignment(AlignmentStruct struct) {
  return Alignment(struct.x, struct.y);
}


/// Parses AlignmentGeometry from AlignmentGeometryStruct.
AlignmentGeometry parseAlignmentGeometry(AlignmentGeometryStruct struct) {
  return _parseAlignmentGeometryValue(struct);
}


/// Parses BorderRadius from BorderRadiusStruct.
BorderRadius parseBorderRadius(BorderRadiusStruct struct) {
  return BorderRadius.only(
    topLeft: struct.topLeft.address != 0 ? parseRadius(Pointer<RadiusStruct>.fromAddress(struct.topLeft.address).ref) : Radius.zero,
    topRight: struct.topRight.address != 0 ? parseRadius(Pointer<RadiusStruct>.fromAddress(struct.topRight.address).ref) : Radius.zero,
    bottomLeft: struct.bottomLeft.address != 0 ? parseRadius(Pointer<RadiusStruct>.fromAddress(struct.bottomLeft.address).ref) : Radius.zero,
    bottomRight: struct.bottomRight.address != 0 ? parseRadius(Pointer<RadiusStruct>.fromAddress(struct.bottomRight.address).ref) : Radius.zero
  );
}


/// Parses BorderRadiusGeometry from BorderRadiusGeometryStruct.
BorderRadiusGeometry parseBorderRadiusGeometry(BorderRadiusGeometryStruct struct) {
  return _parseBorderRadiusGeometryValue(struct);
}


/// Parses BoxDecoration from BoxDecorationStruct.
BoxDecoration parseBoxDecoration(BoxDecorationStruct struct) {
  return _parseBoxDecorationValue(struct);
}


/// Parses Decoration from DecorationStruct.
Decoration parseDecoration(DecorationStruct struct) {
  return _parseDecorationValue(struct);
}


/// Parses BoxConstraints from BoxConstraintsStruct.
BoxConstraints parseBoxConstraints(BoxConstraintsStruct struct) {
  return BoxConstraints(minWidth: struct.minWidth, maxWidth: struct.maxWidth, minHeight: struct.minHeight, maxHeight: struct.maxHeight);
}


/// Parses TextStyle from TextStyleStruct.
TextStyle parseTextStyle(TextStyleStruct struct) {
  return parseTextStyleFromStruct(struct);
}


/// Parses Gradient from GradientStruct.
Gradient parseGradient(GradientStruct struct) {
  return _parseGradientValue(struct);
}


/// Parses Size from SizeStruct.
Size parseSize(SizeStruct struct) {
  return Size(struct.width, struct.height);
}


/// Parses Offset from OffsetStruct.
Offset parseOffset(OffsetStruct struct) {
  return Offset(struct.dx, struct.dy);
}


/// Parses Rect from RectStruct.
Rect parseRect(RectStruct struct) {
  return Rect.fromLTRB(struct.left, struct.top, struct.right, struct.bottom);
}


/// Parses Radius from RadiusStruct.
Radius parseRadius(RadiusStruct struct) {
  return Radius.elliptical(struct.x, struct.y);
}


/// Parses Matrix4 from Matrix4Struct.
Matrix4 parseMatrix4(Matrix4Struct struct) {
  return () {
    if (struct.storage.address == 0) return Matrix4.identity();
    var storage = struct.storage.cast<Double>();
    return Matrix4(
      storage[0], storage[1], storage[2], storage[3],
      storage[4], storage[5], storage[6], storage[7],
      storage[8], storage[9], storage[10], storage[11],
      storage[12], storage[13], storage[14], storage[15]
    );
  }();
}


/// Parses List.
/// TODO: This parser needs manual implementation.
List? parseList(dynamic value) {
  // TODO: Implement parseList
  // CSharp type: 
  print('WARNING: parseList is not implemented yet');
  return null;
}

/// Parses Set.
/// TODO: This parser needs manual implementation.
Set? parseSet(dynamic value) {
  // TODO: Implement parseSet
  // CSharp type: 
  print('WARNING: parseSet is not implemented yet');
  return null;
}

/// Parses Map.
/// TODO: This parser needs manual implementation.
Map? parseMap(dynamic value) {
  // TODO: Implement parseMap
  // CSharp type: 
  print('WARNING: parseMap is not implemented yet');
  return null;
}

/// Parses Iterable.
/// TODO: This parser needs manual implementation.
Iterable? parseIterable(dynamic value) {
  // TODO: Implement parseIterable
  // CSharp type: 
  print('WARNING: parseIterable is not implemented yet');
  return null;
}

/// Parses ValueSetter.
/// TODO: This parser needs manual implementation.
ValueSetter? parseValueSetter(dynamic value) {
  // TODO: Implement parseValueSetter
  // CSharp type: 
  print('WARNING: parseValueSetter is not implemented yet');
  return null;
}

/// Parses ValueGetter.
/// TODO: This parser needs manual implementation.
ValueGetter? parseValueGetter(dynamic value) {
  // TODO: Implement parseValueGetter
  // CSharp type: 
  print('WARNING: parseValueGetter is not implemented yet');
  return null;
}

/// Parses GestureTapCallback.
/// TODO: This parser needs manual implementation.
// Callback parsers need special handling for FFI function pointers
GestureTapCallback? parseGestureTapCallback(dynamic value) {
  // TODO: Implement parseGestureTapCallback
  // CSharp type: 
  print('WARNING: parseGestureTapCallback is not implemented yet');
  return null;
}

/// Parses WidgetBuilder.
/// TODO: This parser needs manual implementation.
WidgetBuilder? parseWidgetBuilder(dynamic value) {
  // TODO: Implement parseWidgetBuilder
  // CSharp type: 
  print('WARNING: parseWidgetBuilder is not implemented yet');
  return null;
}

/// Parses IndexedWidgetBuilder.
/// TODO: This parser needs manual implementation.
IndexedWidgetBuilder? parseIndexedWidgetBuilder(dynamic value) {
  // TODO: Implement parseIndexedWidgetBuilder
  // CSharp type: 
  print('WARNING: parseIndexedWidgetBuilder is not implemented yet');
  return null;
}

/// Parses TransitionBuilder.
/// TODO: This parser needs manual implementation.
TransitionBuilder? parseTransitionBuilder(dynamic value) {
  // TODO: Implement parseTransitionBuilder
  // CSharp type: 
  print('WARNING: parseTransitionBuilder is not implemented yet');
  return null;
}

/// Parses NullableIndexedWidgetBuilder.
/// TODO: This parser needs manual implementation.
NullableIndexedWidgetBuilder? parseNullableIndexedWidgetBuilder(dynamic value) {
  // TODO: Implement parseNullableIndexedWidgetBuilder
  // CSharp type: 
  print('WARNING: parseNullableIndexedWidgetBuilder is not implemented yet');
  return null;
}

/// Parses TextAlign.
TextAlign? parseTextAlign(dynamic value) {
  return _parseEnumValue(
    value,
    TextAlign.values
  );
}

/// Parses MainAxisAlignment.
MainAxisAlignment? parseMainAxisAlignment(dynamic value) {
  return _parseEnumValue(
    value,
    MainAxisAlignment.values
  );
}

/// Parses CrossAxisAlignment.
CrossAxisAlignment? parseCrossAxisAlignment(dynamic value) {
  return _parseEnumValue(
    value,
    CrossAxisAlignment.values
  );
}

/// Parses MainAxisSize.
MainAxisSize? parseMainAxisSize(dynamic value) {
  return _parseEnumValue(
    value,
    MainAxisSize.values
  );
}

/// Parses Axis.
Axis? parseAxis(dynamic value) {
  return _parseEnumValue(
    value,
    Axis.values
  );
}

/// Parses VerticalDirection.
VerticalDirection? parseVerticalDirection(dynamic value) {
  return _parseEnumValue(
    value,
    VerticalDirection.values
  );
}

/// Parses TextDirection.
TextDirection? parseTextDirection(dynamic value) {
  return _parseEnumValue(
    value,
    TextDirection.values
  );
}

/// Parses FontWeight.
/// TODO: This parser needs manual implementation.
FontWeight? parseFontWeight(dynamic value) {
  // TODO: Implement parseFontWeight
  // CSharp type: 
  print('WARNING: parseFontWeight is not implemented yet');
  return null;
}

/// Parses FontStyle.
FontStyle? parseFontStyle(dynamic value) {
  return _parseEnumValue(
    value,
    FontStyle.values
  );
}

/// Parses NavigatorState.
/// TODO: This parser needs manual implementation.
NavigatorState? parseNavigatorState(dynamic value) {
  // TODO: Implement parseNavigatorState
  // CSharp type: 
  print('WARNING: parseNavigatorState is not implemented yet');
  return null;
}

/// Parses RouteSettings.
/// TODO: This parser needs manual implementation.
RouteSettings? parseRouteSettings(dynamic value) {
  // TODO: Implement parseRouteSettings
  // CSharp type: 
  print('WARNING: parseRouteSettings is not implemented yet');
  return null;
}

/// Parses RouterConfig.
/// TODO: This parser needs manual implementation.
RouterConfig? parseRouterConfig(dynamic value) {
  // TODO: Implement parseRouterConfig
  // CSharp type: 
  print('WARNING: parseRouterConfig is not implemented yet');
  return null;
}

/// Parses RouteInformationParser.
/// TODO: This parser needs manual implementation.
RouteInformationParser? parseRouteInformationParser(dynamic value) {
  // TODO: Implement parseRouteInformationParser
  // CSharp type: 
  print('WARNING: parseRouteInformationParser is not implemented yet');
  return null;
}

/// Parses BackButtonDispatcher.
/// TODO: This parser needs manual implementation.
BackButtonDispatcher? parseBackButtonDispatcher(dynamic value) {
  // TODO: Implement parseBackButtonDispatcher
  // CSharp type: 
  print('WARNING: parseBackButtonDispatcher is not implemented yet');
  return null;
}

/// Parses Locale.
/// TODO: This parser needs manual implementation.
Locale? parseLocale(dynamic value) {
  // TODO: Implement parseLocale
  // CSharp type: 
  print('WARNING: parseLocale is not implemented yet');
  return null;
}

/// Parses ShortcutActivator.
/// TODO: This parser needs manual implementation.
ShortcutActivator? parseShortcutActivator(dynamic value) {
  // TODO: Implement parseShortcutActivator
  // CSharp type: 
  print('WARNING: parseShortcutActivator is not implemented yet');
  return null;
}

/// Parses LayoutWidgetBuilder.
/// TODO: This parser needs manual implementation.
LayoutWidgetBuilder? parseLayoutWidgetBuilder(dynamic value) {
  // TODO: Implement parseLayoutWidgetBuilder
  // CSharp type: 
  print('WARNING: parseLayoutWidgetBuilder is not implemented yet');
  return null;
}

/// Parses ScrollPhysics.
/// TODO: This parser needs manual implementation.
ScrollPhysics? parseScrollPhysics(dynamic value) {
  // TODO: Implement parseScrollPhysics
  // CSharp type: 
  print('WARNING: parseScrollPhysics is not implemented yet');
  return null;
}

/// Parses GestureRecognizerFactory.
/// TODO: This parser needs manual implementation.
GestureRecognizerFactory? parseGestureRecognizerFactory(dynamic value) {
  // TODO: Implement parseGestureRecognizerFactory
  // CSharp type: 
  print('WARNING: parseGestureRecognizerFactory is not implemented yet');
  return null;
}

/// Parses FocusNode.
/// TODO: This parser needs manual implementation.
FocusNode? parseFocusNode(dynamic value) {
  // TODO: Implement parseFocusNode
  // CSharp type: 
  print('WARNING: parseFocusNode is not implemented yet');
  return null;
}

/// Parses TextInputType.
/// TODO: This parser needs manual implementation.
TextInputType? parseTextInputType(dynamic value) {
  // TODO: Implement parseTextInputType
  // CSharp type: 
  print('WARNING: parseTextInputType is not implemented yet');
  return null;
}

/// Parses FloatingActionButtonLocation.
/// TODO: This parser needs manual implementation.
FloatingActionButtonLocation? parseFloatingActionButtonLocation(dynamic value) {
  // TODO: Implement parseFloatingActionButtonLocation
  // CSharp type: 
  print('WARNING: parseFloatingActionButtonLocation is not implemented yet');
  return null;
}

/// Parses FloatingActionButtonAnimator.
/// TODO: This parser needs manual implementation.
FloatingActionButtonAnimator? parseFloatingActionButtonAnimator(dynamic value) {
  // TODO: Implement parseFloatingActionButtonAnimator
  // CSharp type: 
  print('WARNING: parseFloatingActionButtonAnimator is not implemented yet');
  return null;
}

/// Parses SnackBarBehavior.
SnackBarBehavior? parseSnackBarBehavior(dynamic value) {
  return _parseEnumValue(
    value,
    SnackBarBehavior.values
  );
}

/// Parses FormFieldValidator.
/// TODO: This parser needs manual implementation.
FormFieldValidator? parseFormFieldValidator(dynamic value) {
  // TODO: Implement parseFormFieldValidator
  // CSharp type: 
  print('WARNING: parseFormFieldValidator is not implemented yet');
  return null;
}

/// Parses FormFieldSetter.
/// TODO: This parser needs manual implementation.
FormFieldSetter? parseFormFieldSetter(dynamic value) {
  // TODO: Implement parseFormFieldSetter
  // CSharp type: 
  print('WARNING: parseFormFieldSetter is not implemented yet');
  return null;
}

/// Parses AutovalidateMode.
AutovalidateMode? parseAutovalidateMode(dynamic value) {
  return _parseEnumValue(
    value,
    AutovalidateMode.values
  );
}

/// Parses RenderObject.
/// TODO: This parser needs manual implementation.
RenderObject? parseRenderObject(dynamic value) {
  // TODO: Implement parseRenderObject
  // CSharp type: 
  print('WARNING: parseRenderObject is not implemented yet');
  return null;
}

/// Parses RenderBox.
/// TODO: This parser needs manual implementation.
RenderBox? parseRenderBox(dynamic value) {
  // TODO: Implement parseRenderBox
  // CSharp type: 
  print('WARNING: parseRenderBox is not implemented yet');
  return null;
}

/// Parses StackFit.
StackFit? parseStackFit(dynamic value) {
  return _parseEnumValue(
    value,
    StackFit.values
  );
}

/// Parses WrapAlignment.
WrapAlignment? parseWrapAlignment(dynamic value) {
  return _parseEnumValue(
    value,
    WrapAlignment.values
  );
}

/// Parses WrapCrossAlignment.
WrapCrossAlignment? parseWrapCrossAlignment(dynamic value) {
  return _parseEnumValue(
    value,
    WrapCrossAlignment.values
  );
}

/// Parses TextOverflow.
TextOverflow? parseTextOverflow(dynamic value) {
  return _parseEnumValue(
    value,
    TextOverflow.values
  );
}

/// Parses TextBaseline.
TextBaseline? parseTextBaseline(dynamic value) {
  return _parseEnumValue(
    value,
    TextBaseline.values
  );
}

/// Parses TextWidthBasis.
TextWidthBasis? parseTextWidthBasis(dynamic value) {
  return _parseEnumValue(
    value,
    TextWidthBasis.values
  );
}

/// Parses ImageRepeat.
ImageRepeat? parseImageRepeat(dynamic value) {
  return _parseEnumValue(
    value,
    ImageRepeat.values
  );
}

/// Parses FilterQuality.
FilterQuality? parseFilterQuality(dynamic value) {
  return _parseEnumValue(
    value,
    FilterQuality.values
  );
}

/// Parses HeroFlightDirection.
HeroFlightDirection? parseHeroFlightDirection(dynamic value) {
  return _parseEnumValue(
    value,
    HeroFlightDirection.values
  );
}

/// Parses TooltipTriggerMode.
TooltipTriggerMode? parseTooltipTriggerMode(dynamic value) {
  return _parseEnumValue(
    value,
    TooltipTriggerMode.values
  );
}

/// Parses Type.
/// TODO: This parser needs manual implementation.
Type? parseType(dynamic value) {
  // TODO: Implement parseType
  // CSharp type: 
  print('WARNING: parseType is not implemented yet');
  return null;
}

/// Parses KeyEvent.
/// TODO: This parser needs manual implementation.
KeyEvent? parseKeyEvent(dynamic value) {
  // TODO: Implement parseKeyEvent
  // CSharp type: 
  print('WARNING: parseKeyEvent is not implemented yet');
  return null;
}

/// Parses KeyEventResult.
KeyEventResult? parseKeyEventResult(dynamic value) {
  return _parseEnumValue(
    value,
    KeyEventResult.values
  );
}

/// Parses PointerEvent.
/// TODO: This parser needs manual implementation.
PointerEvent? parsePointerEvent(dynamic value) {
  // TODO: Implement parsePointerEvent
  // CSharp type: 
  print('WARNING: parsePointerEvent is not implemented yet');
  return null;
}

/// Parses TapUpDetails.
/// TODO: This parser needs manual implementation.
TapUpDetails? parseTapUpDetails(dynamic value) {
  // TODO: Implement parseTapUpDetails
  // CSharp type: 
  print('WARNING: parseTapUpDetails is not implemented yet');
  return null;
}

/// Parses TapDownDetails.
/// TODO: This parser needs manual implementation.
TapDownDetails? parseTapDownDetails(dynamic value) {
  // TODO: Implement parseTapDownDetails
  // CSharp type: 
  print('WARNING: parseTapDownDetails is not implemented yet');
  return null;
}

/// Parses DragUpdateDetails.
/// TODO: This parser needs manual implementation.
DragUpdateDetails? parseDragUpdateDetails(dynamic value) {
  // TODO: Implement parseDragUpdateDetails
  // CSharp type: 
  print('WARNING: parseDragUpdateDetails is not implemented yet');
  return null;
}

/// Parses DragEndDetails.
/// TODO: This parser needs manual implementation.
DragEndDetails? parseDragEndDetails(dynamic value) {
  // TODO: Implement parseDragEndDetails
  // CSharp type: 
  print('WARNING: parseDragEndDetails is not implemented yet');
  return null;
}

/// Parses DragStartDetails.
/// TODO: This parser needs manual implementation.
DragStartDetails? parseDragStartDetails(dynamic value) {
  // TODO: Implement parseDragStartDetails
  // CSharp type: 
  print('WARNING: parseDragStartDetails is not implemented yet');
  return null;
}

/// Parses TextSelection.
/// TODO: This parser needs manual implementation.
TextSelection? parseTextSelection(dynamic value) {
  // TODO: Implement parseTextSelection
  // CSharp type: 
  print('WARNING: parseTextSelection is not implemented yet');
  return null;
}

/// Parses PointerDeviceKind.
PointerDeviceKind? parsePointerDeviceKind(dynamic value) {
  return _parseEnumValue(
    value,
    PointerDeviceKind.values
  );
}

/// Parses ScrollBehavior.
/// TODO: This parser needs manual implementation.
ScrollBehavior? parseScrollBehavior(dynamic value) {
  // TODO: Implement parseScrollBehavior
  // CSharp type: 
  print('WARNING: parseScrollBehavior is not implemented yet');
  return null;
}

/// Parses StackTrace.
/// TODO: This parser needs manual implementation.
StackTrace? parseStackTrace(dynamic value) {
  // TODO: Implement parseStackTrace
  // CSharp type: 
  print('WARNING: parseStackTrace is not implemented yet');
  return null;
}

/// Parses BoxHeightStyle.
BoxHeightStyle? parseBoxHeightStyle(dynamic value) {
  return _parseEnumValue(
    value,
    BoxHeightStyle.values
  );
}

/// Parses BoxWidthStyle.
BoxWidthStyle? parseBoxWidthStyle(dynamic value) {
  return _parseEnumValue(
    value,
    BoxWidthStyle.values
  );
}

/// Parses BoxShape.
BoxShape? parseBoxShape(dynamic value) {
  return _parseEnumValue(
    value,
    BoxShape.values
  );
}

/// Parses BoxBorder.
/// TODO: This parser needs manual implementation.
BoxBorder? parseBoxBorder(dynamic value) {
  // TODO: Implement parseBoxBorder
  // CSharp type: 
  print('WARNING: parseBoxBorder is not implemented yet');
  return null;
}

/// Parses StrutStyle.
/// TODO: This parser needs manual implementation.
StrutStyle? parseStrutStyle(dynamic value) {
  // TODO: Implement parseStrutStyle
  // CSharp type: 
  print('WARNING: parseStrutStyle is not implemented yet');
  return null;
}

/// Parses TextHeightBehavior.
/// TODO: This parser needs manual implementation.
TextHeightBehavior? parseTextHeightBehavior(dynamic value) {
  // TODO: Implement parseTextHeightBehavior
  // CSharp type: 
  print('WARNING: parseTextHeightBehavior is not implemented yet');
  return null;
}

/// Parses InlineSpan.
/// TODO: This parser needs manual implementation.
InlineSpan? parseInlineSpan(dynamic value) {
  // TODO: Implement parseInlineSpan
  // CSharp type: 
  print('WARNING: parseInlineSpan is not implemented yet');
  return null;
}

/// Parses LayerLink.
/// TODO: This parser needs manual implementation.
LayerLink? parseLayerLink(dynamic value) {
  // TODO: Implement parseLayerLink
  // CSharp type: 
  print('WARNING: parseLayerLink is not implemented yet');
  return null;
}

/// Parses ImageFilter.
/// TODO: This parser needs manual implementation.
ImageFilter? parseImageFilter(dynamic value) {
  // TODO: Implement parseImageFilter
  // CSharp type: 
  print('WARNING: parseImageFilter is not implemented yet');
  return null;
}

/// Parses ColorFilter.
/// TODO: This parser needs manual implementation.
ColorFilter? parseColorFilter(dynamic value) {
  // TODO: Implement parseColorFilter
  // CSharp type: 
  print('WARNING: parseColorFilter is not implemented yet');
  return null;
}

/// Parses AssetBundle.
/// TODO: This parser needs manual implementation.
AssetBundle? parseAssetBundle(dynamic value) {
  // TODO: Implement parseAssetBundle
  // CSharp type: 
  print('WARNING: parseAssetBundle is not implemented yet');
  return null;
}

/// Parses FlutterView.
/// TODO: This parser needs manual implementation.
FlutterView? parseFlutterView(dynamic value) {
  // TODO: Implement parseFlutterView
  // CSharp type: 
  print('WARNING: parseFlutterView is not implemented yet');
  return null;
}

/// Parses PlatformViewHitTestBehavior.
PlatformViewHitTestBehavior? parsePlatformViewHitTestBehavior(dynamic value) {
  return _parseEnumValue(
    value,
    PlatformViewHitTestBehavior.values
  );
}

/// Parses BoxConstraintsTransform.
/// TODO: This parser needs manual implementation.
BoxConstraintsTransform? parseBoxConstraintsTransform(dynamic value) {
  // TODO: Implement parseBoxConstraintsTransform
  // CSharp type: 
  print('WARNING: parseBoxConstraintsTransform is not implemented yet');
  return null;
}

/// Parses Tween.
/// TODO: This parser needs manual implementation.
Tween? parseTween(dynamic value) {
  // TODO: Implement parseTween
  // CSharp type: 
  print('WARNING: parseTween is not implemented yet');
  return null;
}

// ═══════════════════════════════════════════════════════════════
// Additional Helper Parsers
// ═══════════════════════════════════════════════════════════════

/// Parses Duration from FFI type (microseconds).
/// Used for ImplicitlyAnimatedWidget.duration which is stored as Int64 microseconds.
Duration parseDurationMicroseconds(int microseconds) {
  return Duration(microseconds: microseconds);
}

/// Parses Animation from struct.
/// Animation is abstract and complex - this is a placeholder that returns a constant animation.
Animation<T>? parseAnimation<T>(dynamic value) {
  // Animation types cannot be parsed from FFI directly.
  // The C# side should manage animation controllers and pass values.
  print('WARNING: parseAnimation is not fully implemented - Animation types require special handling');
  return null;
}

/// Parses ImageProvider from struct.
/// ImageProvider is abstract - this is a placeholder.
ImageProvider? parseImageProvider(dynamic value) {
  // ImageProvider types cannot be parsed from FFI directly.
  // Use specific implementations like NetworkImage or AssetImage.
  print('WARNING: parseImageProvider is not implemented - use specific ImageProvider types');
  return null;
}

/// Parses Curve from struct.
/// Curve is abstract - returns linear curve as default.
Curve parseCurve(dynamic value) {
  // For now, return a default curve
  // TODO: Implement proper curve parsing from struct
  return Curves.linear;
}

T? _parseEnumValue<T extends Enum>(dynamic value, List<T> values, {Map<String, String> aliases = const {}}) {
  if (value == null) return null;
  if (value is T) return value;
  if (value is int) {
    if (value < 0 || value >= values.length) return null;
    return values[value];
  }
  if (value is String) {
    final normalized = value.trim();
    if (normalized.isEmpty) return null;
    final aliased = aliases[normalized] ?? normalized;
    for (final candidate in values) {
      if (candidate.name == aliased) return candidate;
    }
  }
  return null;
}

String? _widgetTypeName(Pointer<Utf8> widgetType) {
  if (widgetType.address == 0) return null;
  return widgetType.toDartString();
}

bool _matchesWidgetType(String? widgetType, String expected) {
  return widgetType == expected || widgetType == '${expected}Struct';
}

BoxShape _parseBoxShapeValue(int value) {
  return _parseEnumValue(value, BoxShape.values) ?? BoxShape.rectangle;
}

const List<Color> _transparentGradientColors = <Color>[
  Color(0x00000000),
  Color(0x00000000),
];

AlignmentGeometry _parseAlignmentGeometryValue(AlignmentGeometryStruct struct) {
  final widgetType = _widgetTypeName(struct.widgetType);
  final address = struct.handle.address;
  if (address == 0) {
    assert(() {
      debugPrint('AlignmentGeometry handle was null for $widgetType, falling back to Alignment.center');
      return true;
    }());
    return Alignment.center;
  }
  if (_matchesWidgetType(widgetType, 'Alignment')) {
    final alignment = Pointer<generated_alignment.AlignmentStruct>.fromAddress(address).ref;
    return Alignment(alignment.x, alignment.y);
  }
  if (_matchesWidgetType(widgetType, 'AlignmentDirectional')) {
    final alignment = Pointer<AlignmentDirectionalStruct>.fromAddress(address).ref;
    return AlignmentDirectional(alignment.start, alignment.y);
  }
  assert(() {
    debugPrint('Unsupported AlignmentGeometry widgetType: $widgetType, falling back to Alignment.center');
    return true;
  }());
  return Alignment.center;
}

EdgeInsetsGeometry _parseEdgeInsetsGeometryValue(EdgeInsetsGeometryStruct struct) {
  final widgetType = _widgetTypeName(struct.widgetType);
  final address = struct.handle.address;
  if (address == 0) {
    assert(() {
      debugPrint('EdgeInsetsGeometry handle was null for $widgetType, falling back to EdgeInsets.zero');
      return true;
    }());
    return EdgeInsets.zero;
  }
  if (_matchesWidgetType(widgetType, 'EdgeInsets')) {
    return parseEdgeInsets(Pointer<EdgeInsetsStruct>.fromAddress(address).ref);
  }
  if (_matchesWidgetType(widgetType, 'EdgeInsetsDirectional')) {
    final insets = Pointer<EdgeInsetsDirectionalStruct>.fromAddress(address).ref;
    return EdgeInsetsDirectional.fromSTEB(insets.start, insets.top, insets.end, insets.bottom);
  }
  assert(() {
    debugPrint('Unsupported EdgeInsetsGeometry widgetType: $widgetType, falling back to EdgeInsets.zero');
    return true;
  }());
  return EdgeInsets.zero;
}

BorderRadiusGeometry _parseBorderRadiusGeometryValue(BorderRadiusGeometryStruct struct) {
  final widgetType = _widgetTypeName(struct.widgetType);
  final address = struct.handle.address;
  if (address == 0) {
    assert(() {
      debugPrint('BorderRadiusGeometry handle was null for $widgetType, falling back to BorderRadius.zero');
      return true;
    }());
    return BorderRadius.zero;
  }
  if (_matchesWidgetType(widgetType, 'BorderRadius')) {
    return parseBorderRadius(Pointer<BorderRadiusStruct>.fromAddress(address).ref);
  }
  if (_matchesWidgetType(widgetType, 'BorderRadiusDirectional')) {
    final radius = Pointer<BorderRadiusDirectionalStruct>.fromAddress(address).ref;
    return BorderRadiusDirectional.only(
      topStart: radius.topStart.address != 0 ? parseRadius(radius.topStart.ref) : Radius.zero,
      topEnd: radius.topEnd.address != 0 ? parseRadius(radius.topEnd.ref) : Radius.zero,
      bottomStart: radius.bottomStart.address != 0 ? parseRadius(radius.bottomStart.ref) : Radius.zero,
      bottomEnd: radius.bottomEnd.address != 0 ? parseRadius(radius.bottomEnd.ref) : Radius.zero,
    );
  }
  assert(() {
    debugPrint('Unsupported BorderRadiusGeometry widgetType: $widgetType, falling back to BorderRadius.zero');
    return true;
  }());
  return BorderRadius.zero;
}

BoxDecoration _parseBoxDecorationValue(BoxDecorationStruct struct) {
  assert(() {
    final unsupported = <String>[
      if (struct.hasImage != 0 && struct.image.address != 0) 'image',
      if (struct.hasBorder != 0 && struct.border.address != 0) 'border',
      if (struct.hasBoxShadow != 0 && struct.boxShadow.address != 0) 'boxShadow',
    ];
    if (unsupported.isNotEmpty) {
      debugPrint('BoxDecoration parser is skipping unsupported fields: ${unsupported.join(', ')}');
    }
    return true;
  }());
  return BoxDecoration(
    color: struct.hasColor != 0 ? Color(struct.color) : null,
    borderRadius: struct.hasBorderRadius != 0 && struct.borderRadius.address != 0
        ? _parseBorderRadiusGeometryValue(struct.borderRadius.ref)
        : null,
    gradient: struct.hasGradient != 0 && struct.gradient.address != 0
        ? parseGradient(struct.gradient.ref)
        : null,
    backgroundBlendMode: struct.hasBackgroundBlendMode != 0
        ? parseBlendMode(struct.backgroundBlendMode)
        : null,
    shape: _parseBoxShapeValue(struct.shape),
  );
}

Decoration _parseDecorationValue(DecorationStruct struct) {
  final widgetType = _widgetTypeName(struct.widgetType);
  final address = struct.handle.address;
  if (address == 0) {
    assert(() {
      debugPrint('Decoration handle was null for $widgetType, falling back to const BoxDecoration()');
      return true;
    }());
    return const BoxDecoration();
  }
  if (_matchesWidgetType(widgetType, 'BoxDecoration')) {
    return _parseBoxDecorationValue(Pointer<BoxDecorationStruct>.fromAddress(address).ref);
  }
  if (_matchesWidgetType(widgetType, 'ShapeDecoration')) {
    final decoration = Pointer<ShapeDecorationStruct>.fromAddress(address).ref;
    assert(() {
      final unsupported = <String>[
        if (decoration.hasImage != 0 && decoration.image.address != 0) 'image',
        if (decoration.hasShadows != 0 && decoration.shadows.address != 0) 'shadows',
        if (decoration.shape.address != 0) 'shape',
      ];
      if (unsupported.isNotEmpty) {
        debugPrint('ShapeDecoration parser is skipping unsupported fields: ${unsupported.join(', ')}');
      }
      return true;
    }());
    return BoxDecoration(
      color: decoration.hasColor != 0 ? Color(decoration.color) : null,
      gradient: decoration.hasGradient != 0 && decoration.gradient.address != 0
          ? parseGradient(decoration.gradient.ref)
          : null,
    );
  }
  assert(() {
    debugPrint('Unsupported Decoration widgetType: $widgetType, falling back to const BoxDecoration()');
    return true;
  }());
  return const BoxDecoration();
}

Gradient _parseGradientValue(GradientStruct struct) {
  final widgetType = _widgetTypeName(struct.widgetType);
  final address = struct.handle.address;
  if (address == 0) {
    assert(() {
      debugPrint('Gradient handle was null for $widgetType, falling back to a transparent LinearGradient');
      return true;
    }());
    return const LinearGradient(colors: _transparentGradientColors);
  }
  if (_matchesWidgetType(widgetType, 'LinearGradient')) {
    final gradient = Pointer<LinearGradientStruct>.fromAddress(address).ref;
    assert(() {
      final unsupported = <String>[
        if (gradient.colors.address != 0) 'colors',
        if (gradient.hasStops != 0 && gradient.stops.address != 0) 'stops',
        if (gradient.tileMode.address != 0) 'tileMode',
        if (gradient.hasTransform != 0 && gradient.transform.address != 0) 'transform',
      ];
      if (unsupported.isNotEmpty) {
        debugPrint('LinearGradient parser is skipping unsupported fields: ${unsupported.join(', ')}');
      }
      return true;
    }());
    return LinearGradient(
      begin: gradient.begin.address != 0 ? parseAlignmentGeometry(gradient.begin.ref) : Alignment.centerLeft,
      end: gradient.end.address != 0 ? parseAlignmentGeometry(gradient.end.ref) : Alignment.centerRight,
      colors: _transparentGradientColors,
    );
  }
  if (_matchesWidgetType(widgetType, 'RadialGradient')) {
    final gradient = Pointer<RadialGradientStruct>.fromAddress(address).ref;
    assert(() {
      final unsupported = <String>[
        if (gradient.colors.address != 0) 'colors',
        if (gradient.hasStops != 0 && gradient.stops.address != 0) 'stops',
        if (gradient.tileMode.address != 0) 'tileMode',
        if (gradient.hasTransform != 0 && gradient.transform.address != 0) 'transform',
      ];
      if (unsupported.isNotEmpty) {
        debugPrint('RadialGradient parser is skipping unsupported fields: ${unsupported.join(', ')}');
      }
      return true;
    }());
    return RadialGradient(
      center: gradient.center.address != 0 ? parseAlignmentGeometry(gradient.center.ref) : Alignment.center,
      radius: gradient.radius > 0 ? gradient.radius : 0.5,
      focal: gradient.hasFocal != 0 && gradient.focal.address != 0 ? parseAlignmentGeometry(gradient.focal.ref) : null,
      focalRadius: gradient.focalRadius > 0 ? gradient.focalRadius : 0.0,
      colors: _transparentGradientColors,
    );
  }
  if (_matchesWidgetType(widgetType, 'SweepGradient')) {
    final gradient = Pointer<SweepGradientStruct>.fromAddress(address).ref;
    assert(() {
      final unsupported = <String>[
        if (gradient.colors.address != 0) 'colors',
        if (gradient.hasStops != 0 && gradient.stops.address != 0) 'stops',
        if (gradient.tileMode.address != 0) 'tileMode',
        if (gradient.hasTransform != 0 && gradient.transform.address != 0) 'transform',
      ];
      if (unsupported.isNotEmpty) {
        debugPrint('SweepGradient parser is skipping unsupported fields: ${unsupported.join(', ')}');
      }
      return true;
    }());
    return SweepGradient(
      center: gradient.center.address != 0 ? parseAlignmentGeometry(gradient.center.ref) : Alignment.center,
      startAngle: gradient.startAngle,
      endAngle: gradient.endAngle != 0 ? gradient.endAngle : 6.283185307179586,
      colors: _transparentGradientColors,
    );
  }
  assert(() {
    debugPrint('Unsupported Gradient widgetType: $widgetType, falling back to a transparent LinearGradient');
    return true;
  }());
  return const LinearGradient(colors: _transparentGradientColors);
}

/// Parses TextStyle from TextStyleStruct (FFI struct).
TextStyle parseTextStyleFromStruct(TextStyleStruct struct) {
  return TextStyle(
    inherit: struct.inherit == 1,
    color: struct.color != 0 ? Color(struct.color) : null,
    backgroundColor: struct.backgroundColor != 0 ? Color(struct.backgroundColor) : null,
    fontFamily: struct.fontFamily.address != 0 ? struct.fontFamily.toDartString() : null,
    fontSize: struct.fontSize > 0 ? struct.fontSize : null,
    fontWeight: struct.fontWeight >= 0 ? _parseFontWeight(struct.fontWeight) : null,
    fontStyle: struct.fontStyle >= 0 ? _parseFontStyle(struct.fontStyle) : null,
    letterSpacing: struct.letterSpacing != 0 ? struct.letterSpacing : null,
    wordSpacing: struct.wordSpacing != 0 ? struct.wordSpacing : null,
    textBaseline: struct.textBaseline >= 0 ? _parseTextBaseline(struct.textBaseline) : null,
    height: struct.height > 0 ? struct.height : null,
    decorationThickness: struct.decorationThickness > 0 ? struct.decorationThickness : null,
    debugLabel: struct.debugLabel.address != 0 ? struct.debugLabel.toDartString() : null,
  );
}

FontWeight? _parseFontWeight(int value) {
  if (value < 0 || value > 8) return null;
  return FontWeight.values[value];
}

FontStyle? _parseFontStyle(int value) {
  if (value < 0 || value > 1) return null;
  return FontStyle.values[value];
}

TextBaseline? _parseTextBaseline(int value) {
  if (value < 0 || value > 1) return null;
  return TextBaseline.values[value];
}


// ═══════════════════════════════════════════════════════════════
// Callback Creator Functions
// ═══════════════════════════════════════════════════════════════
// These functions create Flutter callbacks that dispatch to C# via method channel.
// The actionId parameter is a string identifier for the C# action handler.


/// Invokes a C# action by its string ID via the method channel.
Future<void> _invokeAction(String? actionId, {String? widgetType, Map<String, dynamic>? args}) async {
  if (actionId == null || actionId.isEmpty) return;
  try {
    await invokeHandleAction(actionId, widgetType: widgetType, args: args);
  } catch (e) {
    print('Error invoking action $actionId: $e');
  }
}

/// Creates a VoidCallback that invokes the C# action.
VoidCallback? createVoidCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return () => _invokeAction(actionId);
}

/// Creates a ValueChanged<bool> callback that invokes the C# action.
ValueChanged<bool>? createValueChangedCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (bool value) => _invokeAction(actionId, args: {'value': value});
}

/// Creates a ValueChanged<bool> callback (alias).
ValueChanged<bool>? createValueChangedBoolCallback(String? actionId) {
  return createValueChangedCallback(actionId);
}

/// Creates a ValueChanged<String> callback that invokes the C# action.
ValueChanged<String>? createValueChangedStringCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (String value) => _invokeAction(actionId, args: {'value': value});
}

/// Creates a ValueChanged<int> callback that invokes the C# action.
ValueChanged<int>? createValueChangedIntCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (int value) => _invokeAction(actionId, args: {'value': value});
}

/// Creates a ValueChanged<double> callback that invokes the C# action.
ValueChanged<double>? createValueChangedDoubleCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (double value) => _invokeAction(actionId, args: {'value': value});
}

/// Creates a ValueChanged<DateTime> callback that invokes the C# action.
ValueChanged<DateTime>? createValueChangedDateTimeCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (DateTime value) => _invokeAction(actionId, args: {'value': value.millisecondsSinceEpoch});
}

/// Creates a ValueChanged<TimeOfDay> callback that invokes the C# action.
ValueChanged<TimeOfDay>? createValueChangedTimeOfDayCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (TimeOfDay value) => _invokeAction(actionId, args: {
    'hour': value.hour,
    'minute': value.minute,
  });
}

/// Creates a ValueChanged<Color> callback that invokes the C# action.
ValueChanged<Color>? createValueChangedColorCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (Color value) => _invokeAction(actionId, args: {'value': value.value});
}

/// Creates a ValueChanged<RangeValues> callback that invokes the C# action.
ValueChanged<RangeValues>? createValueChangedRangeValuesCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (RangeValues value) => _invokeAction(actionId, args: {
    'start': value.start,
    'end': value.end,
  });
}

/// Creates a FormFieldValidator<String> callback that invokes the C# action.
/// Note: This is async but validator expects sync - returns null and logs value for now.
FormFieldValidator<String>? createFormFieldValidatorCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (String? value) {
    _invokeAction(actionId, args: {'value': value});
    return null; // Validation must be handled differently
  };
}

/// Creates an onSubmitted callback that invokes the C# action.
ValueChanged<String>? createOnSubmittedCallback(String? actionId) {
  return createValueChangedStringCallback(actionId);
}

/// Creates a GestureTapCallback that invokes the C# action.
GestureTapCallback? createGestureTapCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return () => _invokeAction(actionId);
}

/// Creates a GestureTapDownCallback that invokes the C# action.
GestureTapDownCallback? createGestureTapDownCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (TapDownDetails details) => _invokeAction(actionId, args: {
    'eventType': 'TapDownDetails',
    'globalPosition': {'dx': details.globalPosition.dx, 'dy': details.globalPosition.dy},
    'localPosition': {'dx': details.localPosition.dx, 'dy': details.localPosition.dy},
  });
}

/// Creates a GestureTapUpCallback that invokes the C# action.
GestureTapUpCallback? createGestureTapUpCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (TapUpDetails details) => _invokeAction(actionId, args: {
    'eventType': 'TapUpDetails',
    'globalPosition': {'dx': details.globalPosition.dx, 'dy': details.globalPosition.dy},
    'localPosition': {'dx': details.localPosition.dx, 'dy': details.localPosition.dy},
  });
}

/// Creates a GestureTapCancelCallback that invokes the C# action.
GestureTapCancelCallback? createGestureTapCancelCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return () => _invokeAction(actionId);
}

/// Creates a GestureTapMoveCallback that invokes the C# action.
GestureTapMoveCallback? createGestureTapMoveCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (TapMoveDetails details) => _invokeAction(actionId, args: {
    'eventType': 'TapMoveDetails',
    'globalPosition': {'dx': details.globalPosition.dx, 'dy': details.globalPosition.dy},
    'localPosition': {'dx': details.localPosition.dx, 'dy': details.localPosition.dy},
  });
}

/// Creates a GestureLongPressCallback that invokes the C# action.
GestureLongPressCallback? createGestureLongPressCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return () => _invokeAction(actionId);
}

/// Creates a GestureLongPressDownCallback that invokes the C# action.
GestureLongPressDownCallback? createGestureLongPressDownCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (LongPressDownDetails details) => _invokeAction(actionId, args: {
    'eventType': 'LongPressDownDetails',
    'globalPosition': {'dx': details.globalPosition.dx, 'dy': details.globalPosition.dy},
    'localPosition': {'dx': details.localPosition.dx, 'dy': details.localPosition.dy},
  });
}

/// Creates a GestureLongPressUpCallback that invokes the C# action.
GestureLongPressUpCallback? createGestureLongPressUpCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return () => _invokeAction(actionId);
}

/// Creates a GestureLongPressStartCallback that invokes the C# action.
GestureLongPressStartCallback? createGestureLongPressStartCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (LongPressStartDetails details) => _invokeAction(actionId, args: {
    'eventType': 'LongPressStartDetails',
    'globalPosition': {'dx': details.globalPosition.dx, 'dy': details.globalPosition.dy},
    'localPosition': {'dx': details.localPosition.dx, 'dy': details.localPosition.dy},
  });
}

/// Creates a GestureLongPressEndCallback that invokes the C# action.
GestureLongPressEndCallback? createGestureLongPressEndCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (LongPressEndDetails details) => _invokeAction(actionId, args: {
    'eventType': 'LongPressEndDetails',
    'globalPosition': {'dx': details.globalPosition.dx, 'dy': details.globalPosition.dy},
    'localPosition': {'dx': details.localPosition.dx, 'dy': details.localPosition.dy},
  });
}

/// Creates a GestureLongPressCancelCallback that invokes the C# action.
GestureLongPressCancelCallback? createGestureLongPressCancelCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return () => _invokeAction(actionId);
}

/// Creates a GestureLongPressMoveUpdateCallback that invokes the C# action.
GestureLongPressMoveUpdateCallback? createGestureLongPressMoveUpdateCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (LongPressMoveUpdateDetails details) => _invokeAction(actionId, args: {
    'eventType': 'LongPressMoveUpdateDetails',
    'globalPosition': {'dx': details.globalPosition.dx, 'dy': details.globalPosition.dy},
    'localPosition': {'dx': details.localPosition.dx, 'dy': details.localPosition.dy},
    'offsetFromOrigin': {'dx': details.offsetFromOrigin.dx, 'dy': details.offsetFromOrigin.dy},
    'localOffsetFromOrigin': {'dx': details.localOffsetFromOrigin.dx, 'dy': details.localOffsetFromOrigin.dy},
  });
}

/// Creates a GestureDragDownCallback that invokes the C# action.
GestureDragDownCallback? createGestureDragDownCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (DragDownDetails details) => _invokeAction(actionId, args: {
    'eventType': 'DragDownDetails',
    'globalPosition': {'dx': details.globalPosition.dx, 'dy': details.globalPosition.dy},
    'localPosition': {'dx': details.localPosition.dx, 'dy': details.localPosition.dy},
  });
}

/// Creates a GestureDragStartCallback that invokes the C# action.
GestureDragStartCallback? createGestureDragStartCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (DragStartDetails details) => _invokeAction(actionId, args: {
    'eventType': 'DragStartDetails',
    'globalPosition': {'dx': details.globalPosition.dx, 'dy': details.globalPosition.dy},
    'localPosition': {'dx': details.localPosition.dx, 'dy': details.localPosition.dy},
  });
}

/// Creates a GestureDragUpdateCallback that invokes the C# action.
GestureDragUpdateCallback? createGestureDragUpdateCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (DragUpdateDetails details) => _invokeAction(actionId, args: {
    'eventType': 'DragUpdateDetails',
    'globalPosition': {'dx': details.globalPosition.dx, 'dy': details.globalPosition.dy},
    'localPosition': {'dx': details.localPosition.dx, 'dy': details.localPosition.dy},
    'delta': {'dx': details.delta.dx, 'dy': details.delta.dy},
  });
}

/// Creates a GestureDragEndCallback that invokes the C# action.
GestureDragEndCallback? createGestureDragEndCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (DragEndDetails details) => _invokeAction(actionId, args: {
    'eventType': 'DragEndDetails',
    'velocity': {'pixelsPerSecond': {'dx': details.velocity.pixelsPerSecond.dx, 'dy': details.velocity.pixelsPerSecond.dy}},
    'primaryVelocity': details.primaryVelocity ?? 0,
  });
}

/// Creates a GestureDragCancelCallback that invokes the C# action.
GestureDragCancelCallback? createGestureDragCancelCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return () => _invokeAction(actionId);
}

/// Creates a GestureScaleStartCallback that invokes the C# action.
GestureScaleStartCallback? createGestureScaleStartCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (ScaleStartDetails details) => _invokeAction(actionId, args: {
    'eventType': 'ScaleStartDetails',
    'focalPoint': {'dx': details.focalPoint.dx, 'dy': details.focalPoint.dy},
    'localFocalPoint': {'dx': details.localFocalPoint.dx, 'dy': details.localFocalPoint.dy},
    'pointerCount': details.pointerCount,
  });
}

/// Creates a GestureScaleUpdateCallback that invokes the C# action.
GestureScaleUpdateCallback? createGestureScaleUpdateCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (ScaleUpdateDetails details) => _invokeAction(actionId, args: {
    'eventType': 'ScaleUpdateDetails',
    'focalPoint': {'dx': details.focalPoint.dx, 'dy': details.focalPoint.dy},
    'localFocalPoint': {'dx': details.localFocalPoint.dx, 'dy': details.localFocalPoint.dy},
    'focalPointDelta': {'dx': details.focalPointDelta.dx, 'dy': details.focalPointDelta.dy},
    'scale': details.scale,
    'horizontalScale': details.horizontalScale,
    'verticalScale': details.verticalScale,
    'rotation': details.rotation,
    'pointerCount': details.pointerCount,
  });
}

/// Creates a GestureScaleEndCallback that invokes the C# action.
GestureScaleEndCallback? createGestureScaleEndCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (ScaleEndDetails details) => _invokeAction(actionId, args: {
    'eventType': 'ScaleEndDetails',
    'velocity': {'pixelsPerSecond': {'dx': details.velocity.pixelsPerSecond.dx, 'dy': details.velocity.pixelsPerSecond.dy}},
    'pointerCount': details.pointerCount,
  });
}

/// Creates a GestureForcePressStartCallback that invokes the C# action.
GestureForcePressStartCallback? createGestureForcePressStartCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (ForcePressDetails details) => _invokeAction(actionId, args: {
    'eventType': 'ForcePressDetails',
    'globalPosition': {'dx': details.globalPosition.dx, 'dy': details.globalPosition.dy},
    'localPosition': {'dx': details.localPosition.dx, 'dy': details.localPosition.dy},
    'pressure': details.pressure,
  });
}

/// Creates a GestureForcePressPeakCallback that invokes the C# action.
GestureForcePressPeakCallback? createGestureForcePressPeakCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (ForcePressDetails details) => _invokeAction(actionId, args: {
    'eventType': 'ForcePressDetails',
    'globalPosition': {'dx': details.globalPosition.dx, 'dy': details.globalPosition.dy},
    'localPosition': {'dx': details.localPosition.dx, 'dy': details.localPosition.dy},
    'pressure': details.pressure,
  });
}

/// Creates a GestureForcePressUpdateCallback that invokes the C# action.
GestureForcePressUpdateCallback? createGestureForcePressUpdateCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (ForcePressDetails details) => _invokeAction(actionId, args: {
    'eventType': 'ForcePressDetails',
    'globalPosition': {'dx': details.globalPosition.dx, 'dy': details.globalPosition.dy},
    'localPosition': {'dx': details.localPosition.dx, 'dy': details.localPosition.dy},
    'pressure': details.pressure,
  });
}

/// Creates a GestureForcePressEndCallback that invokes the C# action.
GestureForcePressEndCallback? createGestureForcePressEndCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (ForcePressDetails details) => _invokeAction(actionId, args: {
    'eventType': 'ForcePressDetails',
    'globalPosition': {'dx': details.globalPosition.dx, 'dy': details.globalPosition.dy},
    'localPosition': {'dx': details.localPosition.dx, 'dy': details.localPosition.dy},
    'pressure': details.pressure,
  });
}

/// Creates a PointerDownEventListener that invokes the C# action.
PointerDownEventListener? createPointerDownEventListener(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (PointerDownEvent event) => _invokeAction(actionId, args: {
    'eventType': 'PointerDownEvent',
    'position': {'dx': event.position.dx, 'dy': event.position.dy},
    'localPosition': {'dx': event.localPosition.dx, 'dy': event.localPosition.dy},
    'pointer': event.pointer,
    'kind': event.kind.index,
  });
}

/// Creates a PointerMoveEventListener that invokes the C# action.
PointerMoveEventListener? createPointerMoveEventListener(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (PointerMoveEvent event) => _invokeAction(actionId, args: {
    'eventType': 'PointerMoveEvent',
    'position': {'dx': event.position.dx, 'dy': event.position.dy},
    'localPosition': {'dx': event.localPosition.dx, 'dy': event.localPosition.dy},
    'delta': {'dx': event.delta.dx, 'dy': event.delta.dy},
    'pointer': event.pointer,
  });
}

/// Creates a PointerUpEventListener that invokes the C# action.
PointerUpEventListener? createPointerUpEventListener(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (PointerUpEvent event) => _invokeAction(actionId, args: {
    'eventType': 'PointerUpEvent',
    'position': {'dx': event.position.dx, 'dy': event.position.dy},
    'localPosition': {'dx': event.localPosition.dx, 'dy': event.localPosition.dy},
    'pointer': event.pointer,
    'kind': event.kind.index,
  });
}

/// Creates a PointerCancelEventListener that invokes the C# action.
PointerCancelEventListener? createPointerCancelEventListener(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (PointerCancelEvent event) => _invokeAction(actionId, args: {
    'eventType': 'PointerCancelEvent',
    'position': {'dx': event.position.dx, 'dy': event.position.dy},
    'localPosition': {'dx': event.localPosition.dx, 'dy': event.localPosition.dy},
    'pointer': event.pointer,
  });
}

/// Creates a PointerEnterEventListener that invokes the C# action.
PointerEnterEventListener? createPointerEnterEventListener(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (PointerEnterEvent event) => _invokeAction(actionId, args: {
    'eventType': 'PointerEnterEvent',
    'position': {'dx': event.position.dx, 'dy': event.position.dy},
    'localPosition': {'dx': event.localPosition.dx, 'dy': event.localPosition.dy},
  });
}

/// Creates a PointerExitEventListener that invokes the C# action.
PointerExitEventListener? createPointerExitEventListener(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (PointerExitEvent event) => _invokeAction(actionId, args: {
    'eventType': 'PointerExitEvent',
    'position': {'dx': event.position.dx, 'dy': event.position.dy},
    'localPosition': {'dx': event.localPosition.dx, 'dy': event.localPosition.dy},
  });
}

/// Creates a PointerHoverEventListener that invokes the C# action.
PointerHoverEventListener? createPointerHoverEventListener(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (PointerHoverEvent event) => _invokeAction(actionId, args: {
    'eventType': 'PointerHoverEvent',
    'position': {'dx': event.position.dx, 'dy': event.position.dy},
    'localPosition': {'dx': event.localPosition.dx, 'dy': event.localPosition.dy},
    'delta': {'dx': event.delta.dx, 'dy': event.delta.dy},
    'pointer': event.pointer,
  });
}

/// Creates a PointerSignalEventListener that invokes the C# action.
PointerSignalEventListener? createPointerSignalEventListener(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (PointerSignalEvent event) => _invokeAction(actionId, args: {
    'eventType': 'PointerSignalEvent',
    'position': {'dx': event.position.dx, 'dy': event.position.dy},
    'localPosition': {'dx': event.localPosition.dx, 'dy': event.localPosition.dy},
  });
}

/// Creates a PointerPanZoomStartEventListener that invokes the C# action.
PointerPanZoomStartEventListener? createPointerPanZoomStartEventListener(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (PointerPanZoomStartEvent event) => _invokeAction(actionId, args: {
    'eventType': 'PointerPanZoomStartEvent',
    'position': {'dx': event.position.dx, 'dy': event.position.dy},
    'localPosition': {'dx': event.localPosition.dx, 'dy': event.localPosition.dy},
  });
}

/// Creates a PointerPanZoomUpdateEventListener that invokes the C# action.
PointerPanZoomUpdateEventListener? createPointerPanZoomUpdateEventListener(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (PointerPanZoomUpdateEvent event) => _invokeAction(actionId, args: {
    'eventType': 'PointerPanZoomUpdateEvent',
    'position': {'dx': event.position.dx, 'dy': event.position.dy},
    'localPosition': {'dx': event.localPosition.dx, 'dy': event.localPosition.dy},
    'pan': {'dx': event.pan.dx, 'dy': event.pan.dy},
    'scale': event.scale,
    'rotation': event.rotation,
  });
}

/// Creates a PointerPanZoomEndEventListener that invokes the C# action.
PointerPanZoomEndEventListener? createPointerPanZoomEndEventListener(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (PointerPanZoomEndEvent event) => _invokeAction(actionId, args: {
    'eventType': 'PointerPanZoomEndEvent',
    'position': {'dx': event.position.dx, 'dy': event.position.dy},
    'localPosition': {'dx': event.localPosition.dx, 'dy': event.localPosition.dy},
  });
}

/// Creates a PlatformViewCreatedCallback that invokes the C# action.
PlatformViewCreatedCallback? createPlatformViewCreatedCallback(String? actionId) {
  if (actionId == null || actionId.isEmpty) return null;
  return (int id) => _invokeAction(actionId, args: {'id': id});
}

/// Creates a ShaderCallback placeholder - Shader callbacks require special handling.
/// Note: ShaderCallback returns a Shader, not void, so it cannot be handled via method channel.
ShaderCallback? createShaderCallback(String? actionId) {
  // ShaderCallback cannot be properly implemented via method channel
  // as it needs to return a Shader synchronously
  return null;
}


