flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'FlutterBridge_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOSUsingPlugin
  install_all_flutter_pods(flutter_application_path)

  pod 'CocoaHTTPServer2', '~> 2.4'

end