name: flutter_sharp_source_gen
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  source_gen:
  analyzer: ^3.0.0
  build: ^2.0.0
  build_config: ^1.0.0
  path: ^1.8.0
  logging: ^1.0.1
  code_builder: ^4.0.0
  dart_style: ^2.0.1
  flutter_sharp:

dev_dependencies:
  lints: ^1.0.0
  test:
  build_runner: ^2.0.3
  build_runner_core: ^7.0.0
  build_test: ^2.1.0
  build_verify: ^2.0.0

  
dependency_overrides:
  flutter_sharp:
    path: ../flutter_sharp
