// <auto-generated>
// This file was automatically generated on 2026-01-07 08:01:56 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi';
import 'package:ffi/ffi.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_module/flutter_sharp_structs.dart';
import '../generated_utility_parsers.dart';
import 'package:flutter_module/maui_flutter.dart';
import '../structs/animatedmodalbarrier_struct.dart';

/// A widget that prevents the user from interacting with widgets behind itself,
  /// and can be configured with an animated color value.
  /// 
  /// The modal barrier is the scrim that is rendered behind each route, which
  /// generally prevents the user from interacting with the route below the
  /// current route, and normally partially obscures such routes.
  /// 
  /// For example, when a dialog is on the screen, the page below the dialog is
  /// usually darkened by the modal barrier.
  /// 
  /// This widget is similar to [ModalBarrier] except that it takes an animated
  /// [color] instead of a single color.
  /// 
  /// See also:
  /// 
  /// * [ModalRoute], which uses this widget.
class AnimatedModalBarrierParser extends WidgetParser {
  @override
  Widget parse(IFlutterObjectStruct fos, BuildContext buildContext) {
    var map = Pointer<AnimatedModalBarrierStruct>.fromAddress(fos.handle.address).ref;
    return AnimatedModalBarrier(
      dismissible: map.dismissible,
      semanticsLabel: map.semanticsLabel,
      barrierSemanticsDismissible: map.barrierSemanticsDismissible,
      onDismiss: parseInvalidType(map.onDismiss),
      clipDetailsNotifier: parseInvalidType(map.clipDetailsNotifier),
      semanticsOnTapHint: map.semanticsOnTapHint,
      color: Color(map.color)
    );
  }

  @override
  String get widgetName => "AnimatedModalBarrier";

  /// Handles action dispatch to C# via method channel
  void _handleAction(String? actionId) {
    if (actionId == null || actionId.isEmpty) return;

    // Dispatch action to C# via method channel
    methodChannel.invokeMethod('HandleAction', {
      'actionId': actionId,
      'widgetType': widgetName,
    }).catchError((error) {
      print('Error dispatching action $actionId: $error');
    });
  }
}
