// <auto-generated>
// This file was automatically generated on 2026-01-07 09:38:34 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi';
import 'package:ffi/ffi.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_module/flutter_sharp_structs.dart';
import '../generated_utility_parsers.dart';
import 'package:flutter_module/maui_flutter.dart';
import '../structs/animateddefaulttextstyle_struct.dart';

/// Animated version of [DefaultTextStyle] which automatically transitions the
  /// default text style (the text style to apply to descendant [Text] widgets
  /// without explicit style) over a given duration whenever the given style
  /// changes.
  /// 
  /// The [textAlign], [softWrap], [overflow], [maxLines], [textWidthBasis]
  /// and [textHeightBehavior] properties are not animated and take effect
  /// immediately when changed.
  /// 
  /// Here's an illustration of what using this widget looks like, using a [curve]
  /// of [Curves.elasticInOut].
  /// {@animation 250 266 https://flutter.github.io/assets-for-api-docs/assets/widgets/animated_default_text_style.mp4}
  /// 
  /// For the animation, you can choose a [curve] as well as a [duration] and the
  /// widget will automatically animate to the new default text style. If you require
  /// more control over the animation (e.g. if you want to stop it mid-animation),
  /// consider using a [DefaultTextStyleTransition] instead, which takes a provided
  /// [Animation] as argument. While that allows you to fine-tune the animation,
  /// it also requires more development overhead as you have to manually manage
  /// the lifecycle of the underlying [AnimationController].
class AnimatedDefaultTextStyleParser extends WidgetParser {
  @override
  Widget parse(IFlutterObjectStruct fos, BuildContext buildContext) {
    var map = Pointer<AnimatedDefaultTextStyleStruct>.fromAddress(fos.handle.address).ref;
    return AnimatedDefaultTextStyle(
      style: map.hasStyle == 1 ? parseTextStyle(map.style.ref) : null,
      softWrap: map.softWrap == 1,
      maxLines: map.maxLines,
    );
  }

  @override
  String get widgetName => "AnimatedDefaultTextStyle";

  /// Handles action dispatch to C# via method channel
  void _handleAction(String? actionId) {
    if (actionId == null || actionId.isEmpty) return;

    // Dispatch action to C# via method channel
    methodChannel.invokeMethod('HandleAction', {
      'actionId': actionId,
      'widgetType': widgetName,
    }).catchError((error) {
      print('Error dispatching action $actionId: $error');
    });
  }
}
