// <auto-generated>
// Manually implemented for BottomSheet
// </auto-generated>

import 'dart:ffi' hide Size;
import 'package:flutter/material.dart';
import '../flutter_sharp_structs.dart';
import '../generated/structs/bottom_sheet_struct.dart';
import '../generated/generated_utility_parsers.dart';
import '../maui_flutter.dart';
import '../utils.dart' hide parseBoxConstraints;

class BottomSheetParser extends WidgetParser {
  @override
  Widget parse(IFlutterObjectStruct fos, BuildContext buildContext) {
    var map = Pointer<BottomSheetStruct>.fromAddress(fos.handle.address).ref;
    final id = parseString(map.id);

    // Parse onClosing callback
    final onClosingAction = parseString(map.onClosingAction);

    // Parse builder callback
    final builderAction = parseString(map.builderAction);

    // Parse optional callbacks
    final onDragStartAction = map.hasOnDragStartAction != 0
        ? parseString(map.onDragStartAction)
        : null;
    final onDragEndAction =
        map.hasOnDragEndAction != 0 ? parseString(map.onDragEndAction) : null;

    // Parse properties
    final enableDrag = map.enableDrag != 0;

    bool? showDragHandle;
    if (map.hasShowDragHandle != 0) {
      showDragHandle = map.showDragHandle != 0;
    }

    Color? dragHandleColor;
    if (map.hasDragHandleColor != 0) {
      dragHandleColor = Color(map.dragHandleColor);
    }

    Size? dragHandleSize;
    if (map.hasDragHandleSize != 0 && map.dragHandleSize.address != 0) {
      dragHandleSize = parseSize(map.dragHandleSize.ref);
    }

    Color? backgroundColor;
    if (map.hasBackgroundColor != 0) {
      backgroundColor = Color(map.backgroundColor);
    }

    Color? shadowColor;
    if (map.hasShadowColor != 0) {
      shadowColor = Color(map.shadowColor);
    }

    double? elevation;
    if (map.hasElevation != 0) {
      elevation = map.elevation;
    }

    Clip? clipBehavior;
    if (map.hasClipBehavior != 0) {
      clipBehavior = Clip.values[map.clipBehavior];
    }

    BoxConstraints? constraints;
    if (map.hasConstraints != 0 && map.constraints.address != 0) {
      constraints = parseBoxConstraints(map.constraints.ref);
    }

    // Create onClosing callback - use createVoidCallback or direct callback
    final onClosingCallback = createVoidCallback(onClosingAction) ?? () {};

    return BottomSheet(
      onClosing: onClosingCallback,
      builder: (context) {
        if (builderAction != null && id != null) {
          return FutureBuilder(
            future: requestMauiData(id, builderAction, null),
            builder: (BuildContext context, AsyncSnapshot snapshot) {
              if (snapshot.hasData) {
                var pointer = int.parse(snapshot.data);
                return DynamicWidgetBuilder.buildFromAddress(
                        pointer, context) ??
                    const SizedBox.shrink();
              }
              return const SizedBox.shrink();
            },
          );
        }
        return const SizedBox.shrink();
      },
      onDragStart: onDragStartAction != null
          ? (details) {
              createVoidCallback(onDragStartAction)?.call();
            }
          : null,
      onDragEnd: onDragEndAction != null
          ? (details, {required isClosing}) {
              createVoidCallback(onDragEndAction)?.call();
            }
          : null,
      enableDrag: enableDrag,
      showDragHandle: showDragHandle,
      dragHandleColor: dragHandleColor,
      dragHandleSize: dragHandleSize,
      backgroundColor: backgroundColor,
      shadowColor: shadowColor,
      elevation: elevation,
      clipBehavior: clipBehavior,
      constraints: constraints,
    );
  }

  @override
  String get widgetName => "BottomSheet";
}
