// <auto-generated>
// This file was automatically generated on 2026-04-09 02:46:15 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi' hide Size;
import 'package:flutter/widgets.dart';
import 'package:flutter_module/flutter_sharp_structs.dart';
import '../generated/generated_utility_parsers.dart';
import 'package:flutter_module/maui_flutter.dart';
import '../generated/structs/cliprsuperellipse_struct.dart';

/// A widget that clips its child using a rounded superellipse.
///
/// A rounded superellipse is a shape similar to a typical rounded rectangle
/// ([ClipRRect]), but with smoother transitions between the straight sides and
/// the rounded corners. It resembles the `RoundedRectangle` shape in SwiftUI
/// with the `.continuous` corner style. Technically, it is created by replacing
/// the four corners of a superellipse (also known as a Lamé curve) with
/// circular arcs.
///
/// By default, [ClipRSuperellipse] uses its own bounds as the base rectangle
/// for the clip, but the size and location of the clip can be customized using
/// a custom [clipper].
///
/// See also:
///
/// * [CustomClipper], for information about creating custom clips.
/// * [ClipRect], for more efficient clips without rounded corners.
/// * [ClipRRect], for a typical rounded rectangle, which is created by
/// replacing the four corners of a rectangle with circular arcs.
/// * [ClipOval], for an elliptical clip.
/// * [ClipPath], for an arbitrarily shaped clip.
class ClipRSuperellipseParser extends WidgetParser {
  @override
  Widget parse(IFlutterObjectStruct fos, BuildContext buildContext) {
    var map =
        Pointer<ClipRSuperellipseStruct>.fromAddress(fos.handle.address).ref;
    return ClipRSuperellipse(
        borderRadius: map.borderRadius.address != 0
            ? parseBorderRadiusGeometry(map.borderRadius.ref)
            : BorderRadius.zero,
        // TODO: clipper uses Pointer<Void> and cannot be marshaled through FFI.
        // We only pass a placeholder when a non-null pointer is provided.
        clipper: map.hasClipper != 0 && map.clipper.address != 0
            ? _getClipperPlaceholder()
            : (null as dynamic),
        clipBehavior: Clip.values[map.clipBehavior],
        child: map.hasChild != 0
            ? DynamicWidgetBuilder.buildFromPointer(map.child, buildContext)
            : null);
  }

  @override
  String get widgetName => "ClipRSuperellipse";

  // Placeholder methods for parameters that cannot be marshaled through FFI.
  // TODO: Implement proper handling for these parameters or create a manual wrapper
  dynamic _getClipperPlaceholder() {
    // TODO: Provide proper default value for CustomClipper<RSuperellipse>?
    throw UnimplementedError(
        'ClipRSuperellipse.clipper requires manual implementation - type CustomClipper<RSuperellipse>? cannot be auto-generated');
  }
}
