// <auto-generated>
// This file was automatically generated on 2026-04-09 15:38:14 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi' hide Size;
import 'package:flutter/widgets.dart';
import 'package:flutter_module/flutter_sharp_structs.dart';
import '../generated_utility_parsers.dart';
import 'package:flutter_module/maui_flutter.dart';
import '../structs/fractionallysizedbox_struct.dart';

/// A widget that sizes its child to a fraction of the total available space.
  /// For more details about the layout algorithm, see
  /// [RenderFractionallySizedOverflowBox].
  /// 
  /// {@youtube 560 315 https://www.youtube.com/watch?v=PEsY654EGZ0}
  /// 
  /// {@tool dartpad}
  /// This sample shows a [FractionallySizedBox] whose one child is 50% of
  /// the box's size per the width and height factor parameters, and centered
  /// within that box by the alignment parameter.
  /// 
  /// ** See code in examples/api/lib/widgets/basic/fractionally_sized_box.0.dart **
  /// {@end-tool}
  /// 
  /// See also:
  /// 
  /// * [Align], which sizes itself based on its child's size and positions
  /// the child according to an [Alignment] value.
  /// * [OverflowBox], a widget that imposes different constraints on its child
  /// than it gets from its parent, possibly allowing the child to overflow the
  /// parent.
  /// * The [catalog of layout widgets](https://flutter.dev/widgets/layout/).
class FractionallySizedBoxParser extends WidgetParser {
  @override
  Widget parse(IFlutterObjectStruct fos, BuildContext buildContext) {
    var map = Pointer<FractionallySizedBoxStruct>.fromAddress(fos.handle.address).ref;
    return FractionallySizedBox(
      widthFactor: map.hasWidthFactor != 0 ? map.widthFactor : null,
      heightFactor: map.hasHeightFactor != 0 ? map.heightFactor : null,
      alignment: map.alignment.address != 0 ? parseAlignmentGeometry(map.alignment.ref) : Alignment.center,
      child: map.hasChild != 0 ? DynamicWidgetBuilder.buildFromPointer(map.child, buildContext) : null
    );
  }

  @override
  String get widgetName => "FractionallySizedBox";
}
