// <auto-generated>
// This file was automatically generated on 2026-01-08 22:03:24 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi' hide Size;
import 'package:ffi/ffi.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter/gestures.dart' show DragStartBehavior;
import 'package:flutter_module/flutter_sharp_structs.dart';
import '../generated_utility_parsers.dart';
import 'package:flutter_module/maui_flutter.dart';
import '../structs/gesturedetector_struct.dart';

/// A widget that detects gestures.
///
/// Attempts to recognize gestures that correspond to its non-null callbacks.
///
/// If this widget has a child, it defers to that child for its sizing behavior.
/// If it does not have a child, it grows to fit the parent instead.
///
/// {@youtube 560 315 https://www.youtube.com/watch?v=WhVXkCFPmK4}
///
/// By default a GestureDetector with an invisible child ignores touches;
/// this behavior can be controlled with [behavior].
///
/// GestureDetector also listens for accessibility events and maps
/// them to the callbacks. To ignore accessibility events, set
/// [excludeFromSemantics] to true.
///
/// See <http://flutter.dev/to/gestures> for additional information.
///
/// Material design applications typically react to touches with ink splash
/// effects. The [InkWell] class implements this effect and can be used in place
/// of a [GestureDetector] for handling taps.
///
/// {@tool dartpad}
/// This example contains a black light bulb wrapped in a [GestureDetector]. It
/// turns the light bulb yellow when the "TURN LIGHT ON" button is tapped by
/// setting the `_lights` field, and off again when "TURN LIGHT OFF" is tapped.
///
/// ** See code in examples/api/lib/widgets/gesture_detector/gesture_detector.0.dart **
/// {@end-tool}
///
/// {@tool dartpad}
/// This example uses a [Container] that wraps a [GestureDetector] widget which
/// detects a tap.
///
/// Since the [GestureDetector] does not have a child, it takes on the size of its
/// parent, making the entire area of the surrounding [Container] clickable. When
/// tapped, the [Container] turns yellow by setting the `_color` field. When
/// tapped again, it goes back to white.
///
/// ** See code in examples/api/lib/widgets/gesture_detector/gesture_detector.1.dart **
/// {@end-tool}
///
/// ### Troubleshooting
///
/// Why isn't my parent [GestureDetector.onTap] method called?
///
/// Given a parent [GestureDetector] with an onTap callback, and a child
/// GestureDetector that also defines an onTap callback, when the inner
/// GestureDetector is tapped, both GestureDetectors send a [GestureRecognizer]
/// into the gesture arena. This is because the pointer coordinates are within the
/// bounds of both GestureDetectors. The child GestureDetector wins in this
/// scenario because it was the first to enter the arena, resolving as first come,
/// first served. The child onTap is called, and the parent's is not as the gesture has
/// been consumed.
/// For more information on gesture disambiguation see:
/// [Gesture disambiguation](https://flutter.dev/to/gesture-disambiguation).
///
/// Setting [GestureDetector.behavior] to [HitTestBehavior.opaque]
/// or [HitTestBehavior.translucent] has no impact on parent-child relationships:
/// both GestureDetectors send a GestureRecognizer into the gesture arena, only one wins.
///
/// Some callbacks (e.g. onTapDown) can fire before a recognizer wins the arena,
/// and others (e.g. onTapCancel) fire even when it loses the arena. Therefore,
/// the parent detector in the example above may call some of its callbacks even
/// though it loses in the arena.
///
/// {@tool dartpad}
/// This example uses a [GestureDetector] that wraps a green [Container] and a second
/// GestureDetector that wraps a yellow Container. The second GestureDetector is
/// a child of the green Container.
/// Both GestureDetectors define an onTap callback. When the callback is called it
/// adds a red border to the corresponding Container.
///
/// When the green Container is tapped, it's parent GestureDetector enters
/// the gesture arena. It wins because there is no competing GestureDetector and
/// the green Container shows a red border.
/// When the yellow Container is tapped, it's parent GestureDetector enters
/// the gesture arena. The GestureDetector that wraps the green Container also
/// enters the gesture arena (the pointer events coordinates are inside both
/// GestureDetectors bounds). The GestureDetector that wraps the yellow Container
/// wins because it was the first detector to enter the arena.
///
/// This example sets [debugPrintGestureArenaDiagnostics] to true.
/// This flag prints useful information about gesture arenas.
///
/// Changing the [GestureDetector.behavior] property to [HitTestBehavior.translucent]
/// or [HitTestBehavior.opaque] has no impact: both GestureDetectors send a [GestureRecognizer]
/// into the gesture arena, only one wins.
///
/// ** See code in examples/api/lib/widgets/gesture_detector/gesture_detector.2.dart **
/// {@end-tool}
///
/// ## Debugging
///
/// To see how large the hit test box of a [GestureDetector] is for debugging
/// purposes, set [debugPaintPointersEnabled] to true.
///
/// See also:
///
/// * [Listener], a widget for listening to lower-level raw pointer events.
/// * [MouseRegion], a widget that tracks the movement of mice, even when no
/// button is pressed.
/// * [RawGestureDetector], a widget that is used to detect custom gestures.
class GestureDetectorParser extends WidgetParser {
  @override
  Widget parse(IFlutterObjectStruct fos, BuildContext buildContext) {
    var map =
        Pointer<GestureDetectorStruct>.fromAddress(fos.handle.address).ref;
    return GestureDetector(
        onTapDown: createGestureTapDownCallback(map.onTapDownAction.address != 0
            ? map.onTapDownAction.toDartString()
            : null),
        onTapUp: createGestureTapUpCallback(map.onTapUpAction.address != 0
            ? map.onTapUpAction.toDartString()
            : null),
        onTap: createGestureTapCallback(map.onTapAction.address != 0
            ? map.onTapAction.toDartString()
            : null),
        onTapMove: createGestureTapMoveCallback(map.onTapMoveAction.address != 0
            ? map.onTapMoveAction.toDartString()
            : null),
        onTapCancel: createGestureTapCancelCallback(map.onTapCancelAction.address != 0
            ? map.onTapCancelAction.toDartString()
            : null),
        onSecondaryTap: createGestureTapCallback(map.onSecondaryTapAction.address != 0
            ? map.onSecondaryTapAction.toDartString()
            : null),
        onSecondaryTapDown: createGestureTapDownCallback(
            map.onSecondaryTapDownAction.address != 0
                ? map.onSecondaryTapDownAction.toDartString()
                : null),
        onSecondaryTapUp: createGestureTapUpCallback(map.onSecondaryTapUpAction.address != 0
            ? map.onSecondaryTapUpAction.toDartString()
            : null),
        onSecondaryTapCancel: createGestureTapCancelCallback(
            map.onSecondaryTapCancelAction.address != 0
                ? map.onSecondaryTapCancelAction.toDartString()
                : null),
        onTertiaryTapDown: createGestureTapDownCallback(
            map.onTertiaryTapDownAction.address != 0
                ? map.onTertiaryTapDownAction.toDartString()
                : null),
        onTertiaryTapUp: createGestureTapUpCallback(map.onTertiaryTapUpAction.address != 0 ? map.onTertiaryTapUpAction.toDartString() : null),
        onTertiaryTapCancel: createGestureTapCancelCallback(map.onTertiaryTapCancelAction.address != 0 ? map.onTertiaryTapCancelAction.toDartString() : null),
        onDoubleTapDown: createGestureTapDownCallback(map.onDoubleTapDownAction.address != 0 ? map.onDoubleTapDownAction.toDartString() : null),
        onDoubleTap: createGestureTapCallback(map.onDoubleTapAction.address != 0 ? map.onDoubleTapAction.toDartString() : null),
        onDoubleTapCancel: createGestureTapCancelCallback(map.onDoubleTapCancelAction.address != 0 ? map.onDoubleTapCancelAction.toDartString() : null),
        onLongPressDown: createGestureLongPressDownCallback(map.onLongPressDownAction.address != 0 ? map.onLongPressDownAction.toDartString() : null),
        onLongPressCancel: createGestureLongPressCancelCallback(map.onLongPressCancelAction.address != 0 ? map.onLongPressCancelAction.toDartString() : null),
        onLongPress: createGestureLongPressCallback(map.onLongPressAction.address != 0 ? map.onLongPressAction.toDartString() : null),
        onLongPressStart: createGestureLongPressStartCallback(map.onLongPressStartAction.address != 0 ? map.onLongPressStartAction.toDartString() : null),
        onLongPressMoveUpdate: createGestureLongPressMoveUpdateCallback(map.onLongPressMoveUpdateAction.address != 0 ? map.onLongPressMoveUpdateAction.toDartString() : null),
        onLongPressUp: createGestureLongPressUpCallback(map.onLongPressUpAction.address != 0 ? map.onLongPressUpAction.toDartString() : null),
        onLongPressEnd: createGestureLongPressEndCallback(map.onLongPressEndAction.address != 0 ? map.onLongPressEndAction.toDartString() : null),
        onSecondaryLongPressDown: createGestureLongPressDownCallback(map.onSecondaryLongPressDownAction.address != 0 ? map.onSecondaryLongPressDownAction.toDartString() : null),
        onSecondaryLongPressCancel: createGestureLongPressCancelCallback(map.onSecondaryLongPressCancelAction.address != 0 ? map.onSecondaryLongPressCancelAction.toDartString() : null),
        onSecondaryLongPress: createGestureLongPressCallback(map.onSecondaryLongPressAction.address != 0 ? map.onSecondaryLongPressAction.toDartString() : null),
        onSecondaryLongPressStart: createGestureLongPressStartCallback(map.onSecondaryLongPressStartAction.address != 0 ? map.onSecondaryLongPressStartAction.toDartString() : null),
        onSecondaryLongPressMoveUpdate: createGestureLongPressMoveUpdateCallback(map.onSecondaryLongPressMoveUpdateAction.address != 0 ? map.onSecondaryLongPressMoveUpdateAction.toDartString() : null),
        onSecondaryLongPressUp: createGestureLongPressUpCallback(map.onSecondaryLongPressUpAction.address != 0 ? map.onSecondaryLongPressUpAction.toDartString() : null),
        onSecondaryLongPressEnd: createGestureLongPressEndCallback(map.onSecondaryLongPressEndAction.address != 0 ? map.onSecondaryLongPressEndAction.toDartString() : null),
        onTertiaryLongPressDown: createGestureLongPressDownCallback(map.onTertiaryLongPressDownAction.address != 0 ? map.onTertiaryLongPressDownAction.toDartString() : null),
        onTertiaryLongPressCancel: createGestureLongPressCancelCallback(map.onTertiaryLongPressCancelAction.address != 0 ? map.onTertiaryLongPressCancelAction.toDartString() : null),
        onTertiaryLongPress: createGestureLongPressCallback(map.onTertiaryLongPressAction.address != 0 ? map.onTertiaryLongPressAction.toDartString() : null),
        onTertiaryLongPressStart: createGestureLongPressStartCallback(map.onTertiaryLongPressStartAction.address != 0 ? map.onTertiaryLongPressStartAction.toDartString() : null),
        onTertiaryLongPressMoveUpdate: createGestureLongPressMoveUpdateCallback(map.onTertiaryLongPressMoveUpdateAction.address != 0 ? map.onTertiaryLongPressMoveUpdateAction.toDartString() : null),
        onTertiaryLongPressUp: createGestureLongPressUpCallback(map.onTertiaryLongPressUpAction.address != 0 ? map.onTertiaryLongPressUpAction.toDartString() : null),
        onTertiaryLongPressEnd: createGestureLongPressEndCallback(map.onTertiaryLongPressEndAction.address != 0 ? map.onTertiaryLongPressEndAction.toDartString() : null),
        onVerticalDragDown: createGestureDragDownCallback(map.onVerticalDragDownAction.address != 0 ? map.onVerticalDragDownAction.toDartString() : null),
        onVerticalDragStart: createGestureDragStartCallback(map.onVerticalDragStartAction.address != 0 ? map.onVerticalDragStartAction.toDartString() : null),
        onVerticalDragUpdate: createGestureDragUpdateCallback(map.onVerticalDragUpdateAction.address != 0 ? map.onVerticalDragUpdateAction.toDartString() : null),
        onVerticalDragEnd: createGestureDragEndCallback(map.onVerticalDragEndAction.address != 0 ? map.onVerticalDragEndAction.toDartString() : null),
        onVerticalDragCancel: createGestureDragCancelCallback(map.onVerticalDragCancelAction.address != 0 ? map.onVerticalDragCancelAction.toDartString() : null),
        onHorizontalDragDown: createGestureDragDownCallback(map.onHorizontalDragDownAction.address != 0 ? map.onHorizontalDragDownAction.toDartString() : null),
        onHorizontalDragStart: createGestureDragStartCallback(map.onHorizontalDragStartAction.address != 0 ? map.onHorizontalDragStartAction.toDartString() : null),
        onHorizontalDragUpdate: createGestureDragUpdateCallback(map.onHorizontalDragUpdateAction.address != 0 ? map.onHorizontalDragUpdateAction.toDartString() : null),
        onHorizontalDragEnd: createGestureDragEndCallback(map.onHorizontalDragEndAction.address != 0 ? map.onHorizontalDragEndAction.toDartString() : null),
        onHorizontalDragCancel: createGestureDragCancelCallback(map.onHorizontalDragCancelAction.address != 0 ? map.onHorizontalDragCancelAction.toDartString() : null),
        onPanDown: createGestureDragDownCallback(map.onPanDownAction.address != 0 ? map.onPanDownAction.toDartString() : null),
        onPanStart: createGestureDragStartCallback(map.onPanStartAction.address != 0 ? map.onPanStartAction.toDartString() : null),
        onPanUpdate: createGestureDragUpdateCallback(map.onPanUpdateAction.address != 0 ? map.onPanUpdateAction.toDartString() : null),
        onPanEnd: createGestureDragEndCallback(map.onPanEndAction.address != 0 ? map.onPanEndAction.toDartString() : null),
        onPanCancel: createGestureDragCancelCallback(map.onPanCancelAction.address != 0 ? map.onPanCancelAction.toDartString() : null),
        onScaleStart: createGestureScaleStartCallback(map.onScaleStartAction.address != 0 ? map.onScaleStartAction.toDartString() : null),
        onScaleUpdate: createGestureScaleUpdateCallback(map.onScaleUpdateAction.address != 0 ? map.onScaleUpdateAction.toDartString() : null),
        onScaleEnd: createGestureScaleEndCallback(map.onScaleEndAction.address != 0 ? map.onScaleEndAction.toDartString() : null),
        onForcePressStart: createGestureForcePressStartCallback(map.onForcePressStartAction.address != 0 ? map.onForcePressStartAction.toDartString() : null),
        onForcePressPeak: createGestureForcePressPeakCallback(map.onForcePressPeakAction.address != 0 ? map.onForcePressPeakAction.toDartString() : null),
        onForcePressUpdate: createGestureForcePressUpdateCallback(map.onForcePressUpdateAction.address != 0 ? map.onForcePressUpdateAction.toDartString() : null),
        onForcePressEnd: createGestureForcePressEndCallback(map.onForcePressEndAction.address != 0 ? map.onForcePressEndAction.toDartString() : null),
        behavior: HitTestBehavior.values[map.behavior],
        excludeFromSemantics: map.excludeFromSemantics == 1,
        dragStartBehavior: DragStartBehavior.values[map.dragStartBehavior],
        trackpadScrollCausesScale: map.trackpadScrollCausesScale == 1,
        // TODO: trackpadScrollToScaleFactor is required but type 'InvalidType' cannot be marshaled through FFI
        // This widget needs a manual wrapper to properly handle this parameter
        trackpadScrollToScaleFactor: _getTrackpadScrollToScaleFactorPlaceholder(),
        child: DynamicWidgetBuilder.buildFromPointerNotNull(map.child, buildContext));
  }

  @override
  String get widgetName => "GestureDetector";

  // Placeholder methods for required parameters that cannot be marshaled through FFI
  // TODO: Implement proper handling for these parameters or create a manual wrapper
  dynamic _getTrackpadScrollToScaleFactorPlaceholder() {
    // TODO: Provide proper default value for InvalidType
    throw UnimplementedError(
        'GestureDetector.trackpadScrollToScaleFactor requires manual implementation - type InvalidType cannot be auto-generated');
  }
}
