// <auto-generated>
// This file was automatically generated on 2026-01-07 08:01:56 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi';
import 'package:ffi/ffi.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_module/flutter_sharp_structs.dart';
import '../generated_utility_parsers.dart';
import 'package:flutter_module/maui_flutter.dart';
import '../structs/image_struct.dart';

/// A widget that displays an image.
  /// 
  /// {@youtube 560 315 https://www.youtube.com/watch?v=7oIAs-0G4mw}
  /// 
  /// Several constructors are provided for the various ways that an image can be
  /// specified:
  /// 
  /// * [Image.new], for obtaining an image from an [ImageProvider].
  /// * [Image.asset], for obtaining an image from an [AssetBundle]
  /// using a key.
  /// * [Image.network], for obtaining an image from a URL.
  /// * [Image.file], for obtaining an image from a [File].
  /// * [Image.memory], for obtaining an image from a [Uint8List].
  /// 
  /// The following image formats are supported: {@macro dart.ui.imageFormats}
  /// 
  /// To automatically perform pixel-density-aware asset resolution, specify the
  /// image using an [AssetImage] and make sure that a [MaterialApp], [WidgetsApp],
  /// or [MediaQuery] widget exists above the [Image] widget in the widget tree.
  /// 
  /// The image is painted using [paintImage], which describes the meanings of the
  /// various fields on this class in more detail.
  /// 
  /// {@tool snippet}
  /// The default constructor can be used with any [ImageProvider], such as a
  /// [NetworkImage], to display an image from the internet.
  /// 
  /// ![An image of an owl displayed by the image widget](https://flutter.github.io/assets-for-api-docs/assets/widgets/owl.jpg)
  /// 
  /// ```dart
  /// const Image(
  /// image: NetworkImage('https://flutter.github.io/assets-for-api-docs/assets/widgets/owl.jpg'),
  /// )
  /// ```
  /// {@end-tool}
  /// 
  /// {@tool snippet}
  /// The [Image] Widget also provides several constructors to display different
  /// types of images for convenience. In this example, use the [Image.network]
  /// constructor to display an image from the internet.
  /// 
  /// ![An image of an owl displayed by the image widget using the shortcut constructor](https://flutter.github.io/assets-for-api-docs/assets/widgets/owl-2.jpg)
  /// 
  /// ```dart
  /// Image.network('https://flutter.github.io/assets-for-api-docs/assets/widgets/owl-2.jpg')
  /// ```
  /// {@end-tool}
  /// 
  /// ## Memory usage
  /// 
  /// The image is stored in memory in uncompressed form (so that it can be
  /// rendered). Large images will use a lot of memory: a 4K image (3840×2160)
  /// will use over 30MB of RAM (assuming 32 bits per pixel).
  /// 
  /// This problem is exacerbated by the images being cached in the [ImageCache],
  /// so large images can use memory for even longer than they are displayed.
  /// 
  /// The [Image.asset], [Image.network], [Image.file], and [Image.memory]
  /// constructors allow a custom decode size to be specified through `cacheWidth`
  /// and `cacheHeight` parameters. The engine will then decode and store the
  /// image at the specified size, instead of the image's natural size.
  /// 
  /// This can significantly reduce the memory usage. For example, a 4K image that
  /// will be rendered at only 384×216 pixels (one-tenth the horizontal and
  /// vertical dimensions) would only use 330KB if those dimensions are specified
  /// using the `cacheWidth` and `cacheHeight` parameters, a 100-fold reduction in
  /// memory usage.
  /// 
  /// ## Custom image providers
  /// 
  /// {@tool dartpad}
  /// In this example, a variant of [NetworkImage] is created that passes all the
  /// [ImageConfiguration] information (locale, platform, size, etc) to the server
  /// using query arguments in the image URL.
  /// 
  /// ** See code in examples/api/lib/painting/image_provider/image_provider.0.dart **
  /// {@end-tool}
  /// 
  /// See also:
  /// 
  /// * [Icon], which shows an image from a font.
  /// * [Ink.image], which is the preferred way to show an image in a
  /// material application (especially if the image is in a [Material] and will
  /// have an [InkWell] on top of it).
  /// * [Image](dart-ui/Image-class.html), the class in the [dart:ui] library.
  /// * Cookbook: [Display images from the internet](https://docs.flutter.dev/cookbook/images/network-image)
  /// * Cookbook: [Fade in images with a placeholder](https://docs.flutter.dev/cookbook/images/fading-in-images)
class ImageParser extends WidgetParser {
  @override
  Widget parse(IFlutterObjectStruct fos, BuildContext buildContext) {
    var map = Pointer<ImageStruct>.fromAddress(fos.handle.address).ref;
    return Image(
      image: parseInvalidType(map.image),
      frameBuilderAction: map.frameBuilderActionAction.address != 0 ? _createFrameBuilderCallback(map.frameBuilderActionAction.toDartString()) : null,
      loadingBuilderAction: map.loadingBuilderActionAction.address != 0 ? _createLoadingBuilderCallback(map.loadingBuilderActionAction.toDartString()) : null,
      errorBuilderAction: map.errorBuilderActionAction.address != 0 ? _createErrorBuilderCallback(map.errorBuilderActionAction.toDartString()) : null,
      width: map.width,
      height: map.height,
      color: Color(map.color),
      opacity: parseInvalidType(map.opacity),
      filterQuality: parseInvalidType(map.filterQuality),
      colorBlendMode: parseInvalidType(map.colorBlendMode),
      fit: parseInvalidType(map.fit),
      alignment: parseAlignmentGeometry(map.alignment),
      repeat: parseInvalidType(map.repeat),
      centerSlice: parseInvalidType(map.centerSlice),
      matchTextDirection: map.matchTextDirection,
      gaplessPlayback: map.gaplessPlayback,
      semanticLabel: map.semanticLabel,
      excludeFromSemantics: map.excludeFromSemantics,
      isAntiAlias: map.isAntiAlias
    );
  }

  @override
  String get widgetName => "Image";

  /// Handles action dispatch to C# via method channel
  void _handleAction(String? actionId) {
    if (actionId == null || actionId.isEmpty) return;

    // Dispatch action to C# via method channel
    methodChannel.invokeMethod('HandleAction', {
      'actionId': actionId,
      'widgetType': widgetName,
    }).catchError((error) {
      print('Error dispatching action $actionId: $error');
    });
  }

  // Callback wrapper methods that dispatch to C# via method channel
  dynamic _createFrameBuilderCallback(String actionId) {
    // Generic callback wrapper that handles various callback signatures
    // Returns a closure that dispatches the action and returns a placeholder widget if needed
    return (context, [child]) {
      _handleAction(actionId);
      // For builder callbacks, return the child or an empty Container
      return child ?? Container();
    };
  }
  dynamic _createLoadingBuilderCallback(String actionId) {
    // Generic callback wrapper that handles various callback signatures
    // Returns a closure that dispatches the action and returns a placeholder widget if needed
    return (context, [child]) {
      _handleAction(actionId);
      // For builder callbacks, return the child or an empty Container
      return child ?? Container();
    };
  }
  dynamic _createErrorBuilderCallback(String actionId) {
    // Generic callback wrapper that handles various callback signatures
    // Returns a closure that dispatches the action and returns a placeholder widget if needed
    return (context, [child]) {
      _handleAction(actionId);
      // For builder callbacks, return the child or an empty Container
      return child ?? Container();
    };
  }
}
