// <auto-generated>
// This file was automatically generated on 2026-01-08 02:00:39 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi' hide Size;
import 'package:ffi/ffi.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter/gestures.dart' show DragStartBehavior;
import 'package:flutter/rendering.dart' show PlatformViewHitTestBehavior, PointerSignalEventListener;
import 'package:flutter/services.dart' show PlatformViewCreatedCallback, PointerEnterEventListener, PointerExitEventListener, PointerHoverEventListener;
import 'package:flutter_module/flutter_sharp_structs.dart';
import '../generated_utility_parsers.dart';
import 'package:flutter_module/utils.dart' hide parseBoxConstraints, parseEdgeInsetsGeometry, parseColor, parseCurve, parseBoxBorder;
import 'package:flutter_module/maui_flutter.dart';
import '../generated/structs/indexedstack_struct.dart';

/// A [Stack] that shows a single child from a list of children.
  /// 
  /// The displayed child is the one with the given [index]. The stack is
  /// always as big as the largest child.
  /// 
  /// If value is null, then nothing is displayed.
  /// 
  /// {@youtube 560 315 https://www.youtube.com/watch?v=_O0PPD1Xfbk}
  /// 
  /// {@tool dartpad}
  /// This example shows a [IndexedStack] widget being used to lay out one card
  /// at a time from a series of cards, each keeping their respective states.
  /// 
  /// ** See code in examples/api/lib/widgets/basic/indexed_stack.0.dart **
  /// {@end-tool}
  /// 
  /// See also:
  /// 
  /// * [Stack], for more details about stacks.
  /// * The [catalog of layout widgets](https://flutter.dev/widgets/layout/).
class IndexedStackParser extends WidgetParser {
  @override
  Widget parse(IFlutterObjectStruct fos, BuildContext buildContext) {
    var map = Pointer<IndexedStackStruct>.fromAddress(fos.handle.address).ref;
    return IndexedStack(
      // TODO: alignment is required but type 'AlignmentGeometry' cannot be marshaled through FFI
      // This widget needs a manual wrapper to properly handle this parameter
      alignment: _getAlignmentPlaceholder(),
      textDirection: TextDirection.values[map.textDirection],
      clipBehavior: Clip.values[map.clipBehavior],
      sizing: StackFit.values[map.sizing],
      index: map.index,
      children: DynamicWidgetBuilder.buildWidgets(map.children.cast<ChildrenStruct>(), buildContext)
    );
  }

  @override
  String get widgetName => "IndexedStack";

  // Placeholder methods for required parameters that cannot be marshaled through FFI
  // TODO: Implement proper handling for these parameters or create a manual wrapper
  dynamic _getAlignmentPlaceholder() {
    // TODO: Provide proper default value for AlignmentGeometry
    throw UnimplementedError('IndexedStack.alignment requires manual implementation - type AlignmentGeometry cannot be auto-generated');
  }
}
