// <auto-generated>
// This file was automatically generated on 2026-04-09 02:46:15 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi' hide Size;
import 'package:flutter/widgets.dart';
import 'package:flutter_module/flutter_sharp_structs.dart';
import 'package:flutter_module/maui_flutter.dart';
import '../generated/structs/performanceoverlay_struct.dart';

/// Displays performance statistics.
///
/// The overlay shows two time series. The first shows how much time was
/// required on this thread to produce each frame. The second shows how much
/// time was required on the raster thread (formerly known as the GPU thread)
/// to produce each frame. Ideally, both these values would be less than
/// the total frame budget for the hardware on which the app is running.
/// For example, if the hardware has a screen that updates at 60 Hz, each
/// thread should ideally spend less than 16ms producing each frame.
/// This ideal condition is indicated by a green vertical line for each thread.
/// Otherwise, the performance overlay shows a red vertical line.
///
/// The simplest way to show the performance overlay is to set
/// [MaterialApp.showPerformanceOverlay] or [WidgetsApp.showPerformanceOverlay]
/// to true.
class PerformanceOverlayParser extends WidgetParser {
  @override
  Widget parse(IFlutterObjectStruct fos, BuildContext buildContext) {
    var map =
        Pointer<PerformanceOverlayStruct>.fromAddress(fos.handle.address).ref;
    return PerformanceOverlay(optionsMask: map.optionsMask);
  }

  @override
  String get widgetName => "PerformanceOverlay";
}
