// <auto-generated>
// This file was automatically generated on 2026-01-08 02:00:39 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi' hide Size;
import 'package:ffi/ffi.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter/gestures.dart' show DragStartBehavior;
import 'package:flutter/rendering.dart' show PlatformViewHitTestBehavior, PointerSignalEventListener;
import 'package:flutter/services.dart' show PlatformViewCreatedCallback, PointerEnterEventListener, PointerExitEventListener, PointerHoverEventListener;
import 'package:flutter_module/flutter_sharp_structs.dart';
import '../generated_utility_parsers.dart';
import 'package:flutter_module/utils.dart' hide parseBoxConstraints, parseEdgeInsetsGeometry, parseColor, parseCurve, parseBoxBorder;
import 'package:flutter_module/maui_flutter.dart';
import '../generated/structs/placeholder_struct.dart';

/// A widget that draws a box that represents where other widgets will one day
  /// be added.
  /// 
  /// This widget is useful during development to indicate that the interface is
  /// not yet complete.
  /// 
  /// By default, the placeholder is sized to fit its container. If the
  /// placeholder is in an unbounded space, it will size itself according to the
  /// given [fallbackWidth] and [fallbackHeight].
  /// 
  /// {@youtube 560 315 https://www.youtube.com/watch?v=LPe56fezmoo}
class PlaceholderParser extends WidgetParser {
  @override
  Widget parse(IFlutterObjectStruct fos, BuildContext buildContext) {
    var map = Pointer<PlaceholderStruct>.fromAddress(fos.handle.address).ref;
    return Placeholder(
      color: Color(map.color),
      strokeWidth: map.strokeWidth,
      fallbackWidth: map.fallbackWidth,
      fallbackHeight: map.fallbackHeight,
      child: DynamicWidgetBuilder.buildFromPointerNotNull(map.child, buildContext)
    );
  }

  @override
  String get widgetName => "Placeholder";
}
