// <auto-generated>
// This file was automatically generated on 2026-01-08 02:00:39 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi' hide Size;
import 'package:ffi/ffi.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter/gestures.dart' show DragStartBehavior;
import 'package:flutter/rendering.dart' show PlatformViewHitTestBehavior, PointerSignalEventListener;
import 'package:flutter/services.dart' show PlatformViewCreatedCallback, PointerEnterEventListener, PointerExitEventListener, PointerHoverEventListener;
import 'package:flutter_module/flutter_sharp_structs.dart';
import '../generated_utility_parsers.dart';
import 'package:flutter_module/utils.dart' hide parseBoxConstraints, parseEdgeInsetsGeometry, parseColor, parseCurve, parseBoxBorder;
import 'package:flutter_module/maui_flutter.dart';
import '../generated/structs/platformselectableregioncontextmenu_struct.dart';

/// See `_platform_selectable_region_context_menu_io.dart` for full
  /// documentation.
class PlatformSelectableRegionContextMenuParser extends WidgetParser {
  @override
  Widget parse(IFlutterObjectStruct fos, BuildContext buildContext) {
    var map = Pointer<PlatformSelectableRegionContextMenuStruct>.fromAddress(fos.handle.address).ref;
    return PlatformSelectableRegionContextMenu(
      child: DynamicWidgetBuilder.buildFromPointerNotNull(map.child, buildContext)
    );
  }

  @override
  String get widgetName => "PlatformSelectableRegionContextMenu";
}
