// <auto-generated>
// This file was automatically generated on 2026-01-07 08:01:56 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi';
import 'package:ffi/ffi.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_module/flutter_sharp_structs.dart';
import '../generated_utility_parsers.dart';
import 'package:flutter_module/maui_flutter.dart';
import '../structs/rawimage_struct.dart';

/// A widget that displays a [dart:ui.Image] directly.
  /// 
  /// The image is painted using [paintImage], which describes the meanings of the
  /// various fields on this class in more detail.
  /// 
  /// The [image] is not disposed of by this widget. Creators of the widget are
  /// expected to call [dart:ui.Image.dispose] on the [image] once the [RawImage]
  /// is no longer buildable.
  /// 
  /// The `scale` argument specifies the linear scale factor for drawing this
  /// image at its intended size and applies to both the width and the height.
  /// {@macro flutter.painting.imageInfo.scale}
  /// 
  /// This widget is rarely used directly. Instead, consider using [Image].
class RawImageParser extends WidgetParser {
  @override
  Widget parse(IFlutterObjectStruct fos, BuildContext buildContext) {
    var map = Pointer<RawImageStruct>.fromAddress(fos.handle.address).ref;
    return RawImage(
      image: parseInvalidType(map.image),
      debugImageLabel: map.debugImageLabel,
      width: map.width,
      height: map.height,
      scale: map.scale,
      color: Color(map.color),
      opacity: parseInvalidType(map.opacity),
      filterQuality: parseInvalidType(map.filterQuality),
      colorBlendMode: parseInvalidType(map.colorBlendMode),
      fit: parseInvalidType(map.fit),
      alignment: parseAlignmentGeometry(map.alignment),
      repeat: parseInvalidType(map.repeat),
      centerSlice: parseInvalidType(map.centerSlice),
      matchTextDirection: map.matchTextDirection,
      invertColors: map.invertColors,
      isAntiAlias: map.isAntiAlias
    );
  }

  @override
  String get widgetName => "RawImage";

  /// Handles action dispatch to C# via method channel
  void _handleAction(String? actionId) {
    if (actionId == null || actionId.isEmpty) return;

    // Dispatch action to C# via method channel
    methodChannel.invokeMethod('HandleAction', {
      'actionId': actionId,
      'widgetType': widgetName,
    }).catchError((error) {
      print('Error dispatching action $actionId: $error');
    });
  }
}
