// <auto-generated>
// This file was automatically generated on 2026-04-09 15:38:14 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi' hide Size;
import 'package:flutter/widgets.dart';
import 'package:flutter_module/flutter_sharp_structs.dart';
import '../generated_utility_parsers.dart';
import 'package:flutter_module/maui_flutter.dart';
import '../structs/rawmenuanchorgroup_struct.dart';

/// Creates a menu anchor that is always visible and is not displayed in an
  /// [OverlayPortal].
  /// 
  /// A [RawMenuAnchorGroup] can be used to create a menu bar that handles
  /// external taps and keyboard shortcuts, but defines no default focus or
  /// keyboard traversal to enable more flexibility.
  /// 
  /// When a [MenuController] is given to a [RawMenuAnchorGroup],
  /// - [MenuController.open] has no effect.
  /// - [MenuController.close] closes all child [RawMenuAnchor]s that are open.
  /// - [MenuController.isOpen] reflects whether any child [RawMenuAnchor] is
  /// open.
  /// 
  /// A [child] must be provided.
  /// 
  /// {@tool dartpad}
  /// 
  /// This example uses [RawMenuAnchorGroup] to build a menu bar with four
  /// submenus. Hovering over a menu item opens its respective submenu. Selecting
  /// a menu item will close the menu and update the selected item text.
  /// 
  /// ** See code in examples/api/lib/widgets/raw_menu_anchor/raw_menu_anchor.1.dart **
  /// {@end-tool}
  /// 
  /// See also:
  /// * [MenuBar], which wraps this widget with standard layout and semantics and
  /// focus management.
  /// * [MenuAnchor], a menu anchor that follows the Material Design guidelines.
  /// * [RawMenuAnchor], a widget that defines a region attached to a floating
  /// submenu.
class RawMenuAnchorGroupParser extends WidgetParser {
  @override
  Widget parse(IFlutterObjectStruct fos, BuildContext buildContext) {
    var map = Pointer<RawMenuAnchorGroupStruct>.fromAddress(fos.handle.address).ref;
    return RawMenuAnchorGroup(
      // TODO: controller uses Pointer<Void> and cannot be marshaled through FFI.
      // We only pass a placeholder when a non-null pointer is provided.
      controller: map.controller.address != 0 ? _getControllerPlaceholder() : (null as dynamic),
      child: DynamicWidgetBuilder.buildFromPointerNotNull(map.child, buildContext)
    );
  }

  @override
  String get widgetName => "RawMenuAnchorGroup";

  // Placeholder methods for parameters that cannot be marshaled through FFI.
  // TODO: Implement proper handling for these parameters or create a manual wrapper
  dynamic _getControllerPlaceholder() {
    // TODO: Provide proper default value for MenuController
    throw UnimplementedError('RawMenuAnchorGroup.controller requires manual implementation - type MenuController cannot be auto-generated');
  }
}
