// <auto-generated>
// This file was automatically generated on 2026-01-07 08:01:56 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi';
import 'package:ffi/ffi.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_module/flutter_sharp_structs.dart';
import '../generated_utility_parsers.dart';
import 'package:flutter_module/maui_flutter.dart';
import '../structs/selectioncontainer_struct.dart';

/// A container that handles [SelectionEvent]s for the [Selectable]s in
  /// the subtree.
  /// 
  /// This widget is useful when one wants to customize selection behaviors for
  /// a group of [Selectable]s
  /// 
  /// The state of this container is a single selectable and will register
  /// itself to the [registrar] if provided. Otherwise, it will register to the
  /// [SelectionRegistrar] from the context. Consider using a [SelectionArea]
  /// widget to provide a root registrar.
  /// 
  /// The containers handle the [SelectionEvent]s from the registered
  /// [SelectionRegistrar] and delegate the events to the [delegate].
  /// 
  /// This widget uses [SelectionRegistrarScope] to host the [delegate] as the
  /// [SelectionRegistrar] for the subtree to collect the [Selectable]s, and
  /// [SelectionEvent]s received by this container are sent to the [delegate] using
  /// the [SelectionHandler] API of the delegate.
  /// 
  /// {@tool dartpad}
  /// This sample demonstrates how to create a [SelectionContainer] that only
  /// allows selecting everything or nothing with no partial selection.
  /// 
  /// ** See code in examples/api/lib/material/selection_container/selection_container.0.dart **
  /// {@end-tool}
  /// 
  /// See also:
  /// * [SelectableRegion], which provides an overview of the selection system.
  /// * [SelectionContainer.disabled], which disable selection for a
  /// subtree.
class SelectionContainerParser extends WidgetParser {
  @override
  Widget parse(IFlutterObjectStruct fos, BuildContext buildContext) {
    var map = Pointer<SelectionContainerStruct>.fromAddress(fos.handle.address).ref;
    return SelectionContainer(
      registrar: parseInvalidType(map.registrar),
      @delegate: parseSelectionContainerDelegate(map.@delegate)
    );
  }

  @override
  String get widgetName => "SelectionContainer";

  /// Handles action dispatch to C# via method channel
  void _handleAction(String? actionId) {
    if (actionId == null || actionId.isEmpty) return;

    // Dispatch action to C# via method channel
    methodChannel.invokeMethod('HandleAction', {
      'actionId': actionId,
      'widgetType': widgetName,
    }).catchError((error) {
      print('Error dispatching action $actionId: $error');
    });
  }
}
