// <auto-generated>
// This file was automatically generated on 2026-01-08 02:00:39 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi' hide Size;
import 'package:ffi/ffi.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter/gestures.dart' show DragStartBehavior;
import 'package:flutter/rendering.dart' show PlatformViewHitTestBehavior, PointerSignalEventListener;
import 'package:flutter/services.dart' show PlatformViewCreatedCallback, PointerEnterEventListener, PointerExitEventListener, PointerHoverEventListener;
import 'package:flutter_module/flutter_sharp_structs.dart';
import '../generated_utility_parsers.dart';
import 'package:flutter_module/utils.dart' hide parseBoxConstraints, parseEdgeInsetsGeometry, parseColor, parseCurve, parseBoxBorder;
import 'package:flutter_module/maui_flutter.dart';
import '../generated/structs/sliverfixedextentlist_struct.dart';

/// A sliver that places multiple box children with the same main axis extent in
  /// a linear array.
  /// 
  /// _To learn more about slivers, see [CustomScrollView.slivers]._
  /// 
  /// [SliverFixedExtentList] places its children in a linear array along the main
  /// axis starting at offset zero and without gaps. Each child is forced to have
  /// the [itemExtent] in the main axis and the
  /// [SliverConstraints.crossAxisExtent] in the cross axis.
  /// 
  /// [SliverFixedExtentList] is more efficient than [SliverList] because
  /// [SliverFixedExtentList] does not need to perform layout on its children to
  /// obtain their extent in the main axis.
  /// 
  /// {@tool snippet}
  /// 
  /// This example, which would be inserted into a [CustomScrollView.slivers]
  /// list, shows an infinite number of items in varying shades of blue:
  /// 
  /// ```dart
  /// SliverFixedExtentList(
  /// itemExtent: 50.0,
  /// delegate: SliverChildBuilderDelegate(
  /// (BuildContext context, int index) {
  /// return Container(
  /// alignment: Alignment.center,
  /// color: Colors.lightBlue[100 * (index % 9)],
  /// child: Text('list item $index'),
  /// );
  /// },
  /// ),
  /// )
  /// ```
  /// {@end-tool}
  /// 
  /// {@macro flutter.widgets.SliverChildDelegate.lifecycle}
  /// 
  /// See also:
  /// 
  /// * [SliverPrototypeExtentList], which is similar to [SliverFixedExtentList]
  /// except that it uses a prototype list item instead of a pixel value to define
  /// the main axis extent of each item.
  /// * [SliverVariedExtentList], which supports children with varying (but known
  /// upfront) extents.
  /// * [SliverFillViewport], which determines the [itemExtent] based on
  /// [SliverConstraints.viewportMainAxisExtent].
  /// * [SliverList], which does not require its children to have the same
  /// extent in the main axis.
class SliverFixedExtentListParser extends WidgetParser {
  @override
  Widget parse(IFlutterObjectStruct fos, BuildContext buildContext) {
    var map = Pointer<SliverFixedExtentListStruct>.fromAddress(fos.handle.address).ref;
    return SliverFixedExtentList(
      itemExtent: map.itemExtent,
      // TODO: delegate is required but type 'SliverChildDelegate' cannot be marshaled through FFI
      // This widget needs a manual wrapper to properly handle this parameter
      delegate: _getDelegatePlaceholder()
    );
  }

  @override
  String get widgetName => "SliverFixedExtentList";

  // Placeholder methods for required parameters that cannot be marshaled through FFI
  // TODO: Implement proper handling for these parameters or create a manual wrapper
  dynamic _getDelegatePlaceholder() {
    // TODO: Provide proper default value for SliverChildDelegate
    throw UnimplementedError('SliverFixedExtentList.delegate requires manual implementation - type SliverChildDelegate cannot be auto-generated');
  }
}
