// <auto-generated>
// This file was automatically generated on 2026-04-09 02:46:15 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi' hide Size;
import 'package:flutter/widgets.dart';
import 'package:flutter_module/flutter_sharp_structs.dart';
import 'package:flutter_module/maui_flutter.dart';
import '../structs/tickermode_struct.dart';

/// Enables or disables tickers (and thus animation controllers) in the widget
/// subtree.
///
/// This only works if [AnimationController] objects are created using
/// widget-aware ticker providers. For example, using a
/// [TickerProviderStateMixin] or a [SingleTickerProviderStateMixin].
class TickerModeParser extends WidgetParser {
  @override
  Widget parse(IFlutterObjectStruct fos, BuildContext buildContext) {
    var map = Pointer<TickerModeStruct>.fromAddress(fos.handle.address).ref;
    return TickerMode(
        enabled: map.enabled == 1,
        child: DynamicWidgetBuilder.buildFromPointerNotNull(
            map.child, buildContext));
  }

  @override
  String get widgetName => "TickerMode";
}
