// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;

namespace Flutter.Widgets
{
/// Predefined autofill context clean up actions.
	public enum AutofillContextAction
	{
/// Destroys the current autofill context after informing the platform to save
/// the user input from it.
/// 
/// Corresponds to calling [TextInput.finishAutofillContext] with
/// `shouldSave == true`.
		Commit,
/// Destroys the current autofill context without saving the user input.
/// 
/// Corresponds to calling [TextInput.finishAutofillContext] with
/// `shouldSave == false`.
		Cancel
	}

	/// <summary>
	/// Extension methods for AutofillContextAction enum.
	/// </summary>
	public static class AutofillContextActionExtensions
	{
		/// <summary>
		/// Converts the enum to its Dart integer representation.
		/// </summary>
		public static int ToDartInt(this AutofillContextAction value)
		{
			return (int)value;
		}

		/// <summary>
		/// Converts the enum to its Dart string representation.
		/// </summary>
		public static string ToDartString(this AutofillContextAction value)
		{
			return value switch
			{
				AutofillContextAction.Commit => "commit",
				AutofillContextAction.Cancel => "cancel",
				_ => throw new ArgumentOutOfRangeException(nameof(value), value, null)
			};
		}

		/// <summary>
		/// Converts from a Dart integer representation to the enum.
		/// </summary>
		public static AutofillContextAction FromDartInt(int value)
		{
			return (AutofillContextAction)value;
		}

		/// <summary>
		/// Converts from a Dart string representation to the enum.
		/// </summary>
		public static AutofillContextAction FromDartString(string value)
		{
			return value switch
			{
				"commit" => AutofillContextAction.Commit,
				"cancel" => AutofillContextAction.Cancel,
				_ => throw new ArgumentException($"Unknown AutofillContextAction value: {value}", nameof(value))
			};
		}
	}
}