// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;

namespace Flutter.Widgets
{
/// Where to show a [Banner].
/// 
/// The start and end locations are relative to the ambient [Directionality]
/// (which can be overridden by [Banner.layoutDirection]).
	public enum BannerLocation
	{
/// Show the banner in the top-right corner when the ambient [Directionality]
/// (or [Banner.layoutDirection]) is [TextDirection.rtl] and in the top-left
/// corner when the ambient [Directionality] is [TextDirection.ltr].
		TopStart,
/// Show the banner in the top-left corner when the ambient [Directionality]
/// (or [Banner.layoutDirection]) is [TextDirection.rtl] and in the top-right
/// corner when the ambient [Directionality] is [TextDirection.ltr].
		TopEnd,
/// Show the banner in the bottom-right corner when the ambient
/// [Directionality] (or [Banner.layoutDirection]) is [TextDirection.rtl] and
/// in the bottom-left corner when the ambient [Directionality] is
/// [TextDirection.ltr].
		BottomStart,
/// Show the banner in the bottom-left corner when the ambient
/// [Directionality] (or [Banner.layoutDirection]) is [TextDirection.rtl] and
/// in the bottom-right corner when the ambient [Directionality] is
/// [TextDirection.ltr].
		BottomEnd
	}

	/// <summary>
	/// Extension methods for BannerLocation enum.
	/// </summary>
	public static class BannerLocationExtensions
	{
		/// <summary>
		/// Converts the enum to its Dart integer representation.
		/// </summary>
		public static int ToDartInt(this BannerLocation value)
		{
			return (int)value;
		}

		/// <summary>
		/// Converts the enum to its Dart string representation.
		/// </summary>
		public static string ToDartString(this BannerLocation value)
		{
			return value switch
			{
				BannerLocation.TopStart => "topStart",
				BannerLocation.TopEnd => "topEnd",
				BannerLocation.BottomStart => "bottomStart",
				BannerLocation.BottomEnd => "bottomEnd",
				_ => throw new ArgumentOutOfRangeException(nameof(value), value, null)
			};
		}

		/// <summary>
		/// Converts from a Dart integer representation to the enum.
		/// </summary>
		public static BannerLocation FromDartInt(int value)
		{
			return (BannerLocation)value;
		}

		/// <summary>
		/// Converts from a Dart string representation to the enum.
		/// </summary>
		public static BannerLocation FromDartString(string value)
		{
			return value switch
			{
				"topStart" => BannerLocation.TopStart,
				"topEnd" => BannerLocation.TopEnd,
				"bottomStart" => BannerLocation.BottomStart,
				"bottomEnd" => BannerLocation.BottomEnd,
				_ => throw new ArgumentException($"Unknown BannerLocation value: {value}", nameof(value))
			};
		}
	}
}