// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;

namespace Flutter.Material
{
/// Used with [ButtonTheme] and [ButtonThemeData] to define a button's base
/// colors, and the defaults for the button's minimum size, internal padding,
/// and shape.
	public enum ButtonTextTheme
	{
/// Button text is black or white depending on [ThemeData.brightness].
		Normal,
/// Button text is [ColorScheme.secondary].
		Accent,
/// Button text is based on [ThemeData.primaryColor].
		Primary
	}

	/// <summary>
	/// Extension methods for ButtonTextTheme enum.
	/// </summary>
	public static class ButtonTextThemeExtensions
	{
		/// <summary>
		/// Converts the enum to its Dart integer representation.
		/// </summary>
		public static int ToDartInt(this ButtonTextTheme value)
		{
			return (int)value;
		}

		/// <summary>
		/// Converts the enum to its Dart string representation.
		/// </summary>
		public static string ToDartString(this ButtonTextTheme value)
		{
			return value switch
			{
				ButtonTextTheme.Normal => "normal",
				ButtonTextTheme.Accent => "accent",
				ButtonTextTheme.Primary => "primary",
				_ => throw new ArgumentOutOfRangeException(nameof(value), value, null)
			};
		}

		/// <summary>
		/// Converts from a Dart integer representation to the enum.
		/// </summary>
		public static ButtonTextTheme FromDartInt(int value)
		{
			return (ButtonTextTheme)value;
		}

		/// <summary>
		/// Converts from a Dart string representation to the enum.
		/// </summary>
		public static ButtonTextTheme FromDartString(string value)
		{
			return value switch
			{
				"normal" => ButtonTextTheme.Normal,
				"accent" => ButtonTextTheme.Accent,
				"primary" => ButtonTextTheme.Primary,
				_ => throw new ArgumentException($"Unknown ButtonTextTheme value: {value}", nameof(value))
			};
		}
	}
}