// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;

namespace Flutter.Cupertino
{
/// Determines the order of the columns inside [CupertinoDatePicker] in
/// time and date time mode.
	public enum DatePickerDateTimeOrder
	{
/// Order of the columns, from left to right: date, hour, minute, am/pm.
/// 
/// Example: Fri Aug 31 | 02 | 08 | PM.
		Date_time_dayPeriod,
/// Order of the columns, from left to right: date, am/pm, hour, minute.
/// 
/// Example: Fri Aug 31 | PM | 02 | 08.
		Date_dayPeriod_time,
/// Order of the columns, from left to right: hour, minute, am/pm, date.
/// 
/// Example: 02 | 08 | PM | Fri Aug 31.
		Time_dayPeriod_date,
/// Order of the columns, from left to right: am/pm, hour, minute, date.
/// 
/// Example: PM | 02 | 08 | Fri Aug 31.
		DayPeriod_time_date
	}

	/// <summary>
	/// Extension methods for DatePickerDateTimeOrder enum.
	/// </summary>
	public static class DatePickerDateTimeOrderExtensions
	{
		/// <summary>
		/// Converts the enum to its Dart integer representation.
		/// </summary>
		public static int ToDartInt(this DatePickerDateTimeOrder value)
		{
			return (int)value;
		}

		/// <summary>
		/// Converts the enum to its Dart string representation.
		/// </summary>
		public static string ToDartString(this DatePickerDateTimeOrder value)
		{
			return value switch
			{
				DatePickerDateTimeOrder.Date_time_dayPeriod => "date_time_dayPeriod",
				DatePickerDateTimeOrder.Date_dayPeriod_time => "date_dayPeriod_time",
				DatePickerDateTimeOrder.Time_dayPeriod_date => "time_dayPeriod_date",
				DatePickerDateTimeOrder.DayPeriod_time_date => "dayPeriod_time_date",
				_ => throw new ArgumentOutOfRangeException(nameof(value), value, null)
			};
		}

		/// <summary>
		/// Converts from a Dart integer representation to the enum.
		/// </summary>
		public static DatePickerDateTimeOrder FromDartInt(int value)
		{
			return (DatePickerDateTimeOrder)value;
		}

		/// <summary>
		/// Converts from a Dart string representation to the enum.
		/// </summary>
		public static DatePickerDateTimeOrder FromDartString(string value)
		{
			return value switch
			{
				"date_time_dayPeriod" => DatePickerDateTimeOrder.Date_time_dayPeriod,
				"date_dayPeriod_time" => DatePickerDateTimeOrder.Date_dayPeriod_time,
				"time_dayPeriod_date" => DatePickerDateTimeOrder.Time_dayPeriod_date,
				"dayPeriod_time_date" => DatePickerDateTimeOrder.DayPeriod_time_date,
				_ => throw new ArgumentException($"Unknown DatePickerDateTimeOrder value: {value}", nameof(value))
			};
		}
	}
}