// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;

namespace Flutter.Material
{
/// {@template flutter.material.ButtonStyleButton.iconAlignment}
/// Determines the alignment of the icon within the widgets such as:
/// - [ElevatedButton.icon],
/// - [FilledButton.icon],
/// - [FilledButton.tonalIcon].
/// - [OutlinedButton.icon],
/// - [TextButton.icon],
/// 
/// The effect of `iconAlignment` depends on [TextDirection]. If textDirection is
/// [TextDirection.ltr] then [IconAlignment.start] and [IconAlignment.end] align the
/// icon on the left or right respectively.  If textDirection is [TextDirection.rtl] the
/// the alignments are reversed.
/// 
/// Defaults to [IconAlignment.start].
/// 
/// {@tool dartpad}
/// This sample demonstrates how to use `iconAlignment` to align the button icon to the start
/// or the end of the button.
/// 
/// ** See code in examples/api/lib/material/button_style_button/button_style_button.icon_alignment.0.dart **
/// {@end-tool}
/// 
/// {@endtemplate}
	public enum IconAlignment
	{
/// The icon is placed at the start of the button.
		Start,
/// The icon is placed at the end of the button.
		End
	}

	/// <summary>
	/// Extension methods for IconAlignment enum.
	/// </summary>
	public static class IconAlignmentExtensions
	{
		/// <summary>
		/// Converts the enum to its Dart integer representation.
		/// </summary>
		public static int ToDartInt(this IconAlignment value)
		{
			return (int)value;
		}

		/// <summary>
		/// Converts the enum to its Dart string representation.
		/// </summary>
		public static string ToDartString(this IconAlignment value)
		{
			return value switch
			{
				IconAlignment.Start => "start",
				IconAlignment.End => "end",
				_ => throw new ArgumentOutOfRangeException(nameof(value), value, null)
			};
		}

		/// <summary>
		/// Converts from a Dart integer representation to the enum.
		/// </summary>
		public static IconAlignment FromDartInt(int value)
		{
			return (IconAlignment)value;
		}

		/// <summary>
		/// Converts from a Dart string representation to the enum.
		/// </summary>
		public static IconAlignment FromDartString(string value)
		{
			return value switch
			{
				"start" => IconAlignment.Start,
				"end" => IconAlignment.End,
				_ => throw new ArgumentException($"Unknown IconAlignment value: {value}", nameof(value))
			};
		}
	}
}