// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;

namespace Flutter.Widgets
{
/// Defines the visual and behavioral variants for an [InspectorButton].
	public enum InspectorButtonVariant
	{
/// A standard button with a filled background and foreground icon.
		Filled,
/// A button that can be toggled on or off, visually representing its state.
/// 
/// The [InspectorButton.toggledOn] property determines its current state.
		Toggle,
/// A button that displays only an icon, typically with a transparent background.
		IconOnly
	}

	/// <summary>
	/// Extension methods for InspectorButtonVariant enum.
	/// </summary>
	public static class InspectorButtonVariantExtensions
	{
		/// <summary>
		/// Converts the enum to its Dart integer representation.
		/// </summary>
		public static int ToDartInt(this InspectorButtonVariant value)
		{
			return (int)value;
		}

		/// <summary>
		/// Converts the enum to its Dart string representation.
		/// </summary>
		public static string ToDartString(this InspectorButtonVariant value)
		{
			return value switch
			{
				InspectorButtonVariant.Filled => "filled",
				InspectorButtonVariant.Toggle => "toggle",
				InspectorButtonVariant.IconOnly => "iconOnly",
				_ => throw new ArgumentOutOfRangeException(nameof(value), value, null)
			};
		}

		/// <summary>
		/// Converts from a Dart integer representation to the enum.
		/// </summary>
		public static InspectorButtonVariant FromDartInt(int value)
		{
			return (InspectorButtonVariant)value;
		}

		/// <summary>
		/// Converts from a Dart string representation to the enum.
		/// </summary>
		public static InspectorButtonVariant FromDartString(string value)
		{
			return value switch
			{
				"filled" => InspectorButtonVariant.Filled,
				"toggle" => InspectorButtonVariant.Toggle,
				"iconOnly" => InspectorButtonVariant.IconOnly,
				_ => throw new ArgumentException($"Unknown InspectorButtonVariant value: {value}", nameof(value))
			};
		}
	}
}