// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;

namespace Flutter.Widgets
{
/// An enumeration that indicates whether the current device is available for Live Text input.
/// 
/// See also:
/// * [LiveText], where the availability of Live Text input can be obtained.
	public enum LiveTextInputStatus
	{
/// This device supports Live Text input currently.
		Enabled,
/// The status of the Live Text input is unknown. Since getting the Live Text input availability
/// is asynchronous (see [LiveText.isLiveTextInputAvailable]), this status often exists while
/// waiting to receive the status value for the first time.
		Unknown,
/// The current device doesn't support Live Text input.
		Disabled
	}

	/// <summary>
	/// Extension methods for LiveTextInputStatus enum.
	/// </summary>
	public static class LiveTextInputStatusExtensions
	{
		/// <summary>
		/// Converts the enum to its Dart integer representation.
		/// </summary>
		public static int ToDartInt(this LiveTextInputStatus value)
		{
			return (int)value;
		}

		/// <summary>
		/// Converts the enum to its Dart string representation.
		/// </summary>
		public static string ToDartString(this LiveTextInputStatus value)
		{
			return value switch
			{
				LiveTextInputStatus.Enabled => "enabled",
				LiveTextInputStatus.Unknown => "unknown",
				LiveTextInputStatus.Disabled => "disabled",
				_ => throw new ArgumentOutOfRangeException(nameof(value), value, null)
			};
		}

		/// <summary>
		/// Converts from a Dart integer representation to the enum.
		/// </summary>
		public static LiveTextInputStatus FromDartInt(int value)
		{
			return (LiveTextInputStatus)value;
		}

		/// <summary>
		/// Converts from a Dart string representation to the enum.
		/// </summary>
		public static LiveTextInputStatus FromDartString(string value)
		{
			return value switch
			{
				"enabled" => LiveTextInputStatus.Enabled,
				"unknown" => LiveTextInputStatus.Unknown,
				"disabled" => LiveTextInputStatus.Disabled,
				_ => throw new ArgumentException($"Unknown LiveTextInputStatus value: {value}", nameof(value))
			};
		}
	}
}