// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;

namespace Flutter.UI
{
/// How much space should be occupied in the main axis.
/// 
/// During a flex layout, available space along the main axis is allocated to
/// children. After allocating space, there might be some remaining free space.
/// This value controls whether to maximize or minimize the amount of free
/// space, subject to the incoming layout constraints.
/// 
/// See also:
/// 
/// * [Column], [Row], and [Flex], the flex widgets.
/// * [Expanded] and [Flexible], the widgets that controls a flex widgets'
/// children's flex.
/// * [RenderFlex], the flex render object.
/// * [MainAxisAlignment], which controls how the free space is distributed.
	public enum MainAxisSize
	{
/// Minimize the amount of free space along the main axis, subject to the
/// incoming layout constraints.
/// 
/// If the incoming layout constraints have a large enough
/// [BoxConstraints.minWidth] or [BoxConstraints.minHeight], there might still
/// be a non-zero amount of free space.
/// 
/// If the incoming layout constraints are unbounded, and any children have a
/// non-zero [FlexParentData.flex] and a [FlexFit.tight] fit (as applied by
/// [Expanded]), the [RenderFlex] will assert, because there would be infinite
/// remaining free space and boxes cannot be given infinite size.
		Min,
/// Maximize the amount of free space along the main axis, subject to the
/// incoming layout constraints.
/// 
/// If the incoming layout constraints have a small enough
/// [BoxConstraints.maxWidth] or [BoxConstraints.maxHeight], there might still
/// be no free space.
/// 
/// If the incoming layout constraints are unbounded, the [RenderFlex] will
/// assert, because there would be infinite remaining free space and boxes
/// cannot be given infinite size.
		Max
	}

	/// <summary>
	/// Extension methods for MainAxisSize enum.
	/// </summary>
	public static class MainAxisSizeExtensions
	{
		/// <summary>
		/// Converts the enum to its Dart integer representation.
		/// </summary>
		public static int ToDartInt(this MainAxisSize value)
		{
			return (int)value;
		}

		/// <summary>
		/// Converts the enum to its Dart string representation.
		/// </summary>
		public static string ToDartString(this MainAxisSize value)
		{
			return value switch
			{
				MainAxisSize.Min => "min",
				MainAxisSize.Max => "max",
				_ => throw new ArgumentOutOfRangeException(nameof(value), value, null)
			};
		}

		/// <summary>
		/// Converts from a Dart integer representation to the enum.
		/// </summary>
		public static MainAxisSize FromDartInt(int value)
		{
			return (MainAxisSize)value;
		}

		/// <summary>
		/// Converts from a Dart string representation to the enum.
		/// </summary>
		public static MainAxisSize FromDartString(string value)
		{
			return value switch
			{
				"min" => MainAxisSize.Min,
				"max" => MainAxisSize.Max,
				_ => throw new ArgumentException($"Unknown MainAxisSize value: {value}", nameof(value))
			};
		}
	}
}