// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;

namespace Flutter.Widgets
{
/// Describes the navigation mode to be set by a [MediaQuery] widget.
/// 
/// The different modes indicate the type of navigation to be used in a widget
/// subtree for those widgets sensitive to it.
/// 
/// Use `MediaQuery.navigationModeOf(context)` to determine the navigation mode
/// in effect for the given context. Use a [MediaQuery] widget to set the
/// navigation mode for its descendant widgets.
	public enum NavigationMode
	{
/// This indicates a traditional keyboard-and-mouse navigation modality.
/// 
/// This navigation mode is where the arrow keys can be used for secondary
/// modification operations, like moving sliders or cursors, and disabled
/// controls will lose focus and not be traversable.
		Traditional,
/// This indicates a directional-based navigation mode.
/// 
/// This navigation mode indicates that arrow keys should be reserved for
/// navigation operations, and secondary modifications operations, like moving
/// sliders or cursors, will use alternative bindings or be disabled.
/// 
/// Some behaviors are also affected by this mode. For instance, disabled
/// controls will retain focus when disabled, and will be able to receive
/// focus (although they remain disabled) when traversed.
		Directional
	}

	/// <summary>
	/// Extension methods for NavigationMode enum.
	/// </summary>
	public static class NavigationModeExtensions
	{
		/// <summary>
		/// Converts the enum to its Dart integer representation.
		/// </summary>
		public static int ToDartInt(this NavigationMode value)
		{
			return (int)value;
		}

		/// <summary>
		/// Converts the enum to its Dart string representation.
		/// </summary>
		public static string ToDartString(this NavigationMode value)
		{
			return value switch
			{
				NavigationMode.Traditional => "traditional",
				NavigationMode.Directional => "directional",
				_ => throw new ArgumentOutOfRangeException(nameof(value), value, null)
			};
		}

		/// <summary>
		/// Converts from a Dart integer representation to the enum.
		/// </summary>
		public static NavigationMode FromDartInt(int value)
		{
			return (NavigationMode)value;
		}

		/// <summary>
		/// Converts from a Dart string representation to the enum.
		/// </summary>
		public static NavigationMode FromDartString(string value)
		{
			return value switch
			{
				"traditional" => NavigationMode.Traditional,
				"directional" => NavigationMode.Directional,
				_ => throw new ArgumentException($"Unknown NavigationMode value: {value}", nameof(value))
			};
		}
	}
}