// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;

namespace Flutter.UI
{
/// How much space should be occupied by the [OverflowBox] if there is no
/// overflow.
	public enum OverflowBoxFit
	{
/// The widget will size itself to be as large as the parent allows.
		Max,
/// The widget will follow the child's size.
/// 
/// More specifically, the render object will size itself to match the size of
/// its child within the constraints of its parent, or as small as the
/// parent allows if no child is set.
		DeferToChild
	}

	/// <summary>
	/// Extension methods for OverflowBoxFit enum.
	/// </summary>
	public static class OverflowBoxFitExtensions
	{
		/// <summary>
		/// Converts the enum to its Dart integer representation.
		/// </summary>
		public static int ToDartInt(this OverflowBoxFit value)
		{
			return (int)value;
		}

		/// <summary>
		/// Converts the enum to its Dart string representation.
		/// </summary>
		public static string ToDartString(this OverflowBoxFit value)
		{
			return value switch
			{
				OverflowBoxFit.Max => "max",
				OverflowBoxFit.DeferToChild => "deferToChild",
				_ => throw new ArgumentOutOfRangeException(nameof(value), value, null)
			};
		}

		/// <summary>
		/// Converts from a Dart integer representation to the enum.
		/// </summary>
		public static OverflowBoxFit FromDartInt(int value)
		{
			return (OverflowBoxFit)value;
		}

		/// <summary>
		/// Converts from a Dart string representation to the enum.
		/// </summary>
		public static OverflowBoxFit FromDartString(string value)
		{
			return value switch
			{
				"max" => OverflowBoxFit.Max,
				"deferToChild" => OverflowBoxFit.DeferToChild,
				_ => throw new ArgumentException($"Unknown OverflowBoxFit value: {value}", nameof(value))
			};
		}
	}
}