// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;

namespace Flutter.UI
{
/// The direction of a scroll, relative to the positive scroll offset axis given
/// by an [AxisDirection] and a [GrowthDirection].
/// 
/// This is similar to [GrowthDirection], but contrasts in that it has a third
/// value, [idle], for the case where no scroll is occurring.
/// 
/// This is used by [RenderSliverFloatingPersistentHeader] to only expand when
/// the user is scrolling in the same direction as the detected scroll offset
/// change.
/// 
/// {@template flutter.rendering.ScrollDirection.sample}
/// {@tool dartpad}
/// This sample shows a [CustomScrollView], with [Radio] buttons in the
/// [AppBar.bottom] that change the [AxisDirection] to illustrate different
/// configurations. With a [NotificationListener] to listen to
/// [UserScrollNotification]s, which occur when the [ScrollDirection] changes
/// or stops.
/// 
/// ** See code in examples/api/lib/rendering/scroll_direction/scroll_direction.0.dart **
/// {@end-tool}
/// {@endtemplate}
/// 
/// See also:
/// 
/// * [AxisDirection], which is a directional version of this enum (with values
/// like left and right, rather than just horizontal).
/// * [GrowthDirection], the direction in which slivers and their content are
/// ordered, relative to the scroll offset axis as specified by
/// [AxisDirection].
/// * [UserScrollNotification], which will notify listeners when the
/// [ScrollDirection] changes.
	public enum ScrollDirection
	{
/// No scrolling is underway.
		Idle,
/// Scrolling is happening in the negative scroll offset direction.
/// 
/// For example, for the [GrowthDirection.forward] part of a vertical
/// [AxisDirection.down] list, which is the default directional configuration
/// of all scroll views, this means the content is going down, exposing
/// earlier content as it approaches the zero position.
/// 
/// An anecdote for this most common case is 'forward is toward' the zero
/// position.
		Forward,
/// Scrolling is happening in the positive scroll offset direction.
/// 
/// For example, for the [GrowthDirection.forward] part of a vertical
/// [AxisDirection.down] list, which is the default directional configuration
/// of all scroll views, this means the content is moving up, exposing
/// lower content.
/// 
/// An anecdote for this most common case is reversing, or backing away, from
/// the zero position.
		Reverse
	}

	/// <summary>
	/// Extension methods for ScrollDirection enum.
	/// </summary>
	public static class ScrollDirectionExtensions
	{
		/// <summary>
		/// Converts the enum to its Dart integer representation.
		/// </summary>
		public static int ToDartInt(this ScrollDirection value)
		{
			return (int)value;
		}

		/// <summary>
		/// Converts the enum to its Dart string representation.
		/// </summary>
		public static string ToDartString(this ScrollDirection value)
		{
			return value switch
			{
				ScrollDirection.Idle => "idle",
				ScrollDirection.Forward => "forward",
				ScrollDirection.Reverse => "reverse",
				_ => throw new ArgumentOutOfRangeException(nameof(value), value, null)
			};
		}

		/// <summary>
		/// Converts from a Dart integer representation to the enum.
		/// </summary>
		public static ScrollDirection FromDartInt(int value)
		{
			return (ScrollDirection)value;
		}

		/// <summary>
		/// Converts from a Dart string representation to the enum.
		/// </summary>
		public static ScrollDirection FromDartString(string value)
		{
			return value switch
			{
				"idle" => ScrollDirection.Idle,
				"forward" => ScrollDirection.Forward,
				"reverse" => ScrollDirection.Reverse,
				_ => throw new ArgumentException($"Unknown ScrollDirection value: {value}", nameof(value))
			};
		}
	}
}