// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;

namespace Flutter.Material
{
/// Defines how the tab indicator animates when the selected tab changes.
/// 
/// See also:
/// * [TabBar], which displays a row of tabs.
/// * [TabBarThemeData], which can be used to configure the appearance of the tab
/// indicator.
	public enum TabIndicatorAnimation
	{
/// The tab indicator animates linearly.
		Linear,
/// The tab indicator animates with an elastic effect.
		Elastic
	}

	/// <summary>
	/// Extension methods for TabIndicatorAnimation enum.
	/// </summary>
	public static class TabIndicatorAnimationExtensions
	{
		/// <summary>
		/// Converts the enum to its Dart integer representation.
		/// </summary>
		public static int ToDartInt(this TabIndicatorAnimation value)
		{
			return (int)value;
		}

		/// <summary>
		/// Converts the enum to its Dart string representation.
		/// </summary>
		public static string ToDartString(this TabIndicatorAnimation value)
		{
			return value switch
			{
				TabIndicatorAnimation.Linear => "linear",
				TabIndicatorAnimation.Elastic => "elastic",
				_ => throw new ArgumentOutOfRangeException(nameof(value), value, null)
			};
		}

		/// <summary>
		/// Converts from a Dart integer representation to the enum.
		/// </summary>
		public static TabIndicatorAnimation FromDartInt(int value)
		{
			return (TabIndicatorAnimation)value;
		}

		/// <summary>
		/// Converts from a Dart string representation to the enum.
		/// </summary>
		public static TabIndicatorAnimation FromDartString(string value)
		{
			return value switch
			{
				"linear" => TabIndicatorAnimation.Linear,
				"elastic" => TabIndicatorAnimation.Elastic,
				_ => throw new ArgumentException($"Unknown TabIndicatorAnimation value: {value}", nameof(value))
			};
		}
	}
}