// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;

namespace Flutter.UI
{
/// How [Wrap] should align objects.
/// 
/// Used both to align children within a run in the main axis as well as to
/// align the runs themselves in the cross axis.
	public enum WrapAlignment
	{
/// Place the objects as close to the start of the axis as possible.
/// 
/// If this value is used in a horizontal direction, a [TextDirection] must be
/// available to determine if the start is the left or the right.
/// 
/// If this value is used in a vertical direction, a [VerticalDirection] must be
/// available to determine if the start is the top or the bottom.
		Start,
/// Place the objects as close to the end of the axis as possible.
/// 
/// If this value is used in a horizontal direction, a [TextDirection] must be
/// available to determine if the end is the left or the right.
/// 
/// If this value is used in a vertical direction, a [VerticalDirection] must be
/// available to determine if the end is the top or the bottom.
		End,
/// Place the objects as close to the middle of the axis as possible.
		Center,
/// Place the free space evenly between the objects.
		SpaceBetween,
/// Place the free space evenly between the objects as well as half of that
/// space before and after the first and last objects.
		SpaceAround,
/// Place the free space evenly between the objects as well as before and
/// after the first and last objects.
		SpaceEvenly
	}

	/// <summary>
	/// Extension methods for WrapAlignment enum.
	/// </summary>
	public static class WrapAlignmentExtensions
	{
		/// <summary>
		/// Converts the enum to its Dart integer representation.
		/// </summary>
		public static int ToDartInt(this WrapAlignment value)
		{
			return (int)value;
		}

		/// <summary>
		/// Converts the enum to its Dart string representation.
		/// </summary>
		public static string ToDartString(this WrapAlignment value)
		{
			return value switch
			{
				WrapAlignment.Start => "start",
				WrapAlignment.End => "end",
				WrapAlignment.Center => "center",
				WrapAlignment.SpaceBetween => "spaceBetween",
				WrapAlignment.SpaceAround => "spaceAround",
				WrapAlignment.SpaceEvenly => "spaceEvenly",
				_ => throw new ArgumentOutOfRangeException(nameof(value), value, null)
			};
		}

		/// <summary>
		/// Converts from a Dart integer representation to the enum.
		/// </summary>
		public static WrapAlignment FromDartInt(int value)
		{
			return (WrapAlignment)value;
		}

		/// <summary>
		/// Converts from a Dart string representation to the enum.
		/// </summary>
		public static WrapAlignment FromDartString(string value)
		{
			return value switch
			{
				"start" => WrapAlignment.Start,
				"end" => WrapAlignment.End,
				"center" => WrapAlignment.Center,
				"spaceBetween" => WrapAlignment.SpaceBetween,
				"spaceAround" => WrapAlignment.SpaceAround,
				"spaceEvenly" => WrapAlignment.SpaceEvenly,
				_ => throw new ArgumentException($"Unknown WrapAlignment value: {value}", nameof(value))
			};
		}
	}
}