// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections.Generic;
using Flutter;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;

namespace Flutter.Widgets
{
/// Animated version of [PhysicalModel].
/// 
/// The [borderRadius] and [elevation] are animated.
/// 
/// The [color] is animated if the [animateColor] property is set; otherwise,
/// the color changes immediately at the start of the animation for the other
/// two properties. This allows the color to be animated independently (e.g.
/// because it is being driven by an [AnimatedTheme]).
/// 
/// The [shape] is not animated.
/// 
/// Here's an illustration of what using this widget looks like, using a [curve]
/// of [Curves.fastOutSlowIn].
/// {@animation 250 266 https://flutter.github.io/assets-for-api-docs/assets/widgets/animated_physical_model.mp4}
	public class AnimatedPhysicalModel : ImplicitlyAnimatedWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="AnimatedPhysicalModel"/> class.
		/// </summary>
		public AnimatedPhysicalModel(
			Widget _child,
			BoxShape _shape,
			Clip _clipBehavior,
			BorderRadiusGeometry? _borderRadius,
			double _elevation,
			Color? _color,
			bool _animateColor,
			Color? _shadowColor,
			bool _animateShadowColor,
			TimeSpan _duration
,
			Curve _curve = null,
			InvalidType _onEnd = null
		)
		{
			// TODO: Property assignments will be handled by a proper FFI marshaling layer
			// For now, constructors accept parameters but don't assign them
			// This avoids type mismatch errors where C# objects would be assigned to nint struct fields
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new AnimatedPhysicalModelStruct();
	}
}
