// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections.Generic;
using Flutter;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;

namespace Flutter.Widgets
{
/// Annotates a region of the layer tree with a value.
/// 
/// See also:
/// 
/// * [Layer.find], for an example of how this value is retrieved.
/// * [AnnotatedRegionLayer], the layer pushed into the layer tree.
	public class AnnotatedRegion<T> : SingleChildRenderObjectWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="AnnotatedRegion"/> class.
		/// </summary>
		public AnnotatedRegion(
			T _value,
			bool _sized

		)
		{
			// TODO: Property assignments will be handled by a proper FFI marshaling layer
			// For now, constructors accept parameters but don't assign them
			// This avoids type mismatch errors where C# objects would be assigned to nint struct fields
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new AnnotatedRegionStruct();
	}
}
