// <auto-generated>
// This file was manually created for FlutterSharp Phase 4 - Material Widgets
// </auto-generated>

using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using Flutter;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;

namespace Flutter.Widgets
{
	/// <summary>
	/// A Material Design bottom navigation bar.
	///
	/// Bottom navigation bars display three to five destinations at the bottom of a screen.
	/// Each destination is represented by an icon and an optional text label. When a bottom
	/// navigation icon is tapped, the user is taken to the top-level navigation destination
	/// associated with that icon.
	///
	/// The bottom navigation bar consists of multiple items in the form of text labels, icons,
	/// or both, laid out on top of a piece of material. It provides quick navigation between
	/// the top-level views of an app. For larger screens, side navigation may be a better fit.
	///
	/// A bottom navigation bar is usually used in conjunction with a Scaffold, where it is
	/// provided as the Scaffold.bottomNavigationBar argument.
	///
	/// The bottom navigation bar's type changes how its items are displayed. If not specified,
	/// it's automatically set to BottomNavigationBarType.Fixed when there are less than four items,
	/// and BottomNavigationBarType.Shifting otherwise.
	///
	/// BottomNavigationBarType.Fixed, the default when there are less than four items.
	/// The selected item is rendered with the selectedItemColor if it's non-null, otherwise
	/// the theme's ColorScheme.primary color is used for Brightness.light themes and
	/// ColorScheme.secondary for Brightness.dark themes. If backgroundColor is null, The
	/// navigation bar's background color defaults to the Material background color,
	/// ThemeData.canvasColor (essentially opaque white).
	///
	/// BottomNavigationBarType.Shifting, the default when there are four or more items.
	/// If selectedItemColor is null, all items are rendered in white. The navigation bar's
	/// background color is the same as the BottomNavigationBarItem.backgroundColor of the
	/// selected item. In this case it's assumed that each item will have a different
	/// background color and that background color will contrast well with white.
	///
	/// See also:
	///
	///  * BottomNavigationBarItem
	///  * Scaffold
	///  * <https://material.io/design/components/bottom-navigation.html>
	///  * <https://m3.material.io/components/navigation-bar>
	/// </summary>
	public class BottomNavigationBar : StatefulWidget
	{
		private List<BottomNavigationBarItem> _items = new();

		/// <summary>
		/// Initializes a new instance of the <see cref="BottomNavigationBar"/> class.
		/// </summary>
		/// <param name="items">Defines the appearance of the button items that are arrayed within the bottom navigation bar.</param>
		/// <param name="currentIndex">The index into items for the current active BottomNavigationBarItem.</param>
		/// <param name="onTap">Called when one of the items is tapped.</param>
		/// <param name="elevation">The z-coordinate of this BottomNavigationBar.</param>
		/// <param name="type">Defines the layout and behavior of a BottomNavigationBar.</param>
		/// <param name="backgroundColor">The color of the BottomNavigationBar itself (ARGB format).</param>
		/// <param name="iconSize">The size of all of the BottomNavigationBarItem icons.</param>
		/// <param name="selectedItemColor">The color of the selected BottomNavigationBarItem.icon and label (ARGB format).</param>
		/// <param name="unselectedItemColor">The color of the unselected BottomNavigationBarItem.icon and label (ARGB format).</param>
		/// <param name="selectedFontSize">The font size of the BottomNavigationBarItem labels when selected.</param>
		/// <param name="unselectedFontSize">The font size of the BottomNavigationBarItem labels when not selected.</param>
		/// <param name="showSelectedLabels">Whether the labels are shown for the selected BottomNavigationBarItem.</param>
		/// <param name="showUnselectedLabels">Whether the labels are shown for the unselected BottomNavigationBarItem.</param>
		/// <param name="enableFeedback">Whether detected gestures should provide acoustic and/or haptic feedback.</param>
		/// <param name="landscapeLayout">The arrangement of the bar's items when in landscape orientation.</param>
		/// <param name="useLegacyColorScheme">Whether to use the root Navigator for pushing deep links.</param>
		public BottomNavigationBar(
			List<BottomNavigationBarItem> items,
			int currentIndex = 0,
			Action<int>? onTap = null,
			double? elevation = null,
			BottomNavigationBarType? type = null,
			uint? backgroundColor = null,
			double? iconSize = null,
			uint? selectedItemColor = null,
			uint? unselectedItemColor = null,
			double? selectedFontSize = null,
			double? unselectedFontSize = null,
			bool? showSelectedLabels = null,
			bool? showUnselectedLabels = null,
			bool enableFeedback = true,
			BottomNavigationBarLandscapeLayout landscapeLayout = BottomNavigationBarLandscapeLayout.Spread,
			bool useLegacyColorScheme = true
		)
		{
			_items = items ?? new List<BottomNavigationBarItem>();

			var s = GetBackingStruct<BottomNavigationBarStruct>();

			// Assign currentIndex
			s.currentIndex = currentIndex;

			// Register onTap callback and assign action ID to struct
			s.onTapAction = RegisterCallback(onTap);

			// Assign elevation
			if (elevation.HasValue)
			{
				s.Haselevation = 1;
				s.elevation = elevation.Value;
			}

			// Assign type
			if (type.HasValue)
			{
				s.type = type.Value;
			}
			else
			{
				// Default behavior based on item count
				s.type = items.Count <= 3 ? BottomNavigationBarType.@Fixed : BottomNavigationBarType.Shifting;
			}

			// Assign backgroundColor
			if (backgroundColor.HasValue)
			{
				s.HasbackgroundColor = 1;
				s.backgroundColor = (int)backgroundColor.Value;
			}

			// Assign iconSize
			if (iconSize.HasValue)
			{
				s.HasiconSize = 1;
				s.iconSize = iconSize.Value;
			}

			// Assign selectedItemColor
			if (selectedItemColor.HasValue)
			{
				s.HasselectedItemColor = 1;
				s.selectedItemColor = (int)selectedItemColor.Value;
			}

			// Assign unselectedItemColor
			if (unselectedItemColor.HasValue)
			{
				s.HasunselectedItemColor = 1;
				s.unselectedItemColor = (int)unselectedItemColor.Value;
			}

			// Assign selectedFontSize
			if (selectedFontSize.HasValue)
			{
				s.HasselectedFontSize = 1;
				s.selectedFontSize = selectedFontSize.Value;
			}

			// Assign unselectedFontSize
			if (unselectedFontSize.HasValue)
			{
				s.HasunselectedFontSize = 1;
				s.unselectedFontSize = unselectedFontSize.Value;
			}

			// Assign showSelectedLabels
			if (showSelectedLabels.HasValue)
			{
				s.HasshowSelectedLabels = 1;
				s.showSelectedLabels = showSelectedLabels.Value;
			}

			// Assign showUnselectedLabels
			if (showUnselectedLabels.HasValue)
			{
				s.HasshowUnselectedLabels = 1;
				s.showUnselectedLabels = showUnselectedLabels.Value;
			}

			// Assign enableFeedback
			s.enableFeedback = (byte)(enableFeedback ? 1 : 0);

			// Assign landscapeLayout
			s.landscapeLayout = landscapeLayout;

			// Assign useLegacyColorScheme
			s.useLegacyColorScheme = (byte)(useLegacyColorScheme ? 1 : 0);
		}

		/// <summary>
		/// Prepares this widget for sending to Dart by serializing items array.
		/// </summary>
		internal new void PrepareForSending()
		{
			var s = GetBackingStruct<BottomNavigationBarStruct>();

			// Prepare and serialize items array
			if (_items.Count > 0)
			{
				var itemPointers = new IntPtr[_items.Count];
				for (int i = 0; i < _items.Count; i++)
				{
					// Get the widget handle for each item - this prepares it for sending
					itemPointers[i] = GetWidgetHandle(_items[i]);
				}

				// Allocate unmanaged memory for items array
				int size = IntPtr.Size * _items.Count;
				s.items = Marshal.AllocHGlobal(size);
				Marshal.Copy(itemPointers, 0, s.items, _items.Count);
				s.itemCount = _items.Count;
			}

			base.PrepareForSending();
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new BottomNavigationBarStruct();
	}
}
