// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections;
using System.Collections.Generic;
using Flutter;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;
using Flutter.Services;
using Flutter.Navigation;

namespace Flutter.Material
{
/// Applies a checkbox theme to descendant [Checkbox] widgets.
/// 
/// Descendant widgets obtain the current theme's [CheckboxTheme] object using
/// [CheckboxTheme.of]. When a widget uses [CheckboxTheme.of], it is
/// automatically rebuilt if the theme later changes.
/// 
/// A checkbox theme can be specified as part of the overall Material theme
/// using [ThemeData.checkboxTheme].
/// 
/// See also:
/// 
/// * [CheckboxThemeData], which describes the actual configuration of a
/// checkbox theme.
	public class CheckboxTheme : InheritedWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="CheckboxTheme"/> class.
		/// </summary>
		public CheckboxTheme(
			Widget child,
			object data = null
		)
		{
			var s = GetBackingStruct<CheckboxThemeStruct>();
			// Complex type: object - skipped (requires marshaling)
			s.child = child;
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new CheckboxThemeStruct();
	}
}
