// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections.Generic;
using Flutter;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;

namespace Flutter.Widgets
{
/// A specialized [AbstractLayoutBuilder] whose widget subtree depends on the
/// incoming [ConstraintType] that will be imposed on the widget.
/// 
/// {@template flutter.widgets.ConstrainedLayoutBuilder}
/// The [builder] function is called in the following situations:
/// 
/// * The first time the widget is laid out.
/// * When the parent widget passes different layout constraints.
/// * When the parent widget updates this widget and [updateShouldRebuild] returns `true`.
/// * When the dependencies that the [builder] function subscribes to change.
/// 
/// The [builder] function is _not_ called during layout if the parent passes
/// the same constraints repeatedly.
/// 
/// In the event that an ancestor skips the layout of this subtree so the
/// constraints become outdated, the `builder` rebuilds with the last known
/// constraints.
/// {@endtemplate}
	public abstract class ConstrainedLayoutBuilder<ConstraintType> : Widget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="ConstrainedLayoutBuilder"/> class.
		/// </summary>
		public ConstrainedLayoutBuilder(
			Func<BuildContext, ConstraintType, Widget> _builder

		)
		{
			// TODO: Property assignments will be handled by a proper FFI marshaling layer
			// For now, constructors accept parameters but don't assign them
			// This avoids type mismatch errors where C# objects would be assigned to nint struct fields
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new ConstrainedLayoutBuilderStruct();
	}
}
