// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections;
using System.Collections.Generic;
using Flutter;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;
using Flutter.Services;
using Flutter.Navigation;

namespace Flutter.Cupertino
{
/// An iOS-style activity indicator that spins clockwise.
/// 
/// {@youtube 560 315 https://www.youtube.com/watch?v=AENVH-ZqKDQ}
/// 
/// {@tool dartpad}
/// This example shows how [CupertinoActivityIndicator] can be customized.
/// 
/// ** See code in examples/api/lib/cupertino/activity_indicator/cupertino_activity_indicator.0.dart **
/// {@end-tool}
/// 
/// See also:
/// 
/// * [CupertinoLinearActivityIndicator], which displays progress along a line.
/// * <https://developer.apple.com/design/human-interface-guidelines/progress-indicators/>
	public class CupertinoActivityIndicator : StatefulWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="CupertinoActivityIndicator"/> class.
		/// </summary>
		public CupertinoActivityIndicator(
			double progress,
			Color? color = null,
			bool animating = true,
			double? radius = null
		)
		{
			var s = GetBackingStruct<CupertinoActivityIndicatorStruct>();
			// Complex type: Color? - skipped (requires marshaling)
			s.animating = animating;
			if (radius.HasValue)
				s.radius = radius.Value;
			s.progress = progress;
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new CupertinoActivityIndicatorStruct();
	}
}
