// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections;
using System.Collections.Generic;
using Flutter;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;
using Flutter.Services;
using Flutter.Navigation;

namespace Flutter.Cupertino
{
/// Applies a visual styling theme to descendant Cupertino widgets.
/// 
/// Affects the color and text styles of Cupertino widgets whose styling
/// are not overridden when constructing the respective widgets instances.
/// 
/// Descendant widgets can retrieve the current [CupertinoThemeData] by calling
/// [CupertinoTheme.of]. An [InheritedWidget] dependency is created when
/// an ancestor [CupertinoThemeData] is retrieved via [CupertinoTheme.of].
/// 
/// The [CupertinoTheme] widget implies an [IconTheme] widget, whose
/// [IconTheme.data] has the same color as [CupertinoThemeData.primaryColor]
/// 
/// See also:
/// 
/// * [CupertinoThemeData], specifies the theme's visual styling.
/// * [CupertinoApp], which will automatically add a [CupertinoTheme] based on the
/// value of [CupertinoApp.theme].
/// * [Theme], a Material theme which will automatically add a [CupertinoTheme]
/// with a [CupertinoThemeData] derived from the Material [ThemeData].
	public class CupertinoTheme : StatelessWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="CupertinoTheme"/> class.
		/// </summary>
		public CupertinoTheme(
			Widget child,
			object data = null
		)
		{
			var s = GetBackingStruct<CupertinoThemeStruct>();
			// Complex type: object - skipped (requires marshaling)
			s.child = child;
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new CupertinoThemeStruct();
	}
}
