// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections;
using System.Collections.Generic;
using Flutter;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;
using Flutter.Services;
using Flutter.Navigation;

namespace Flutter.Widgets
{
/// A container for a [Scrollable] that responds to drag gestures by resizing
/// the scrollable until a limit is reached, and then scrolling.
/// 
/// {@youtube 560 315 https://www.youtube.com/watch?v=Hgw819mL_78}
/// 
/// This widget can be dragged along the vertical axis between its
/// [minChildSize], which defaults to `0.25` and [maxChildSize], which defaults
/// to `1.0`. These sizes are percentages of the height of the parent container.
/// 
/// The widget coordinates resizing and scrolling of the widget returned by
/// builder as the user drags along the horizontal axis.
/// 
/// The widget will initially be displayed at its initialChildSize which
/// defaults to `0.5`, meaning half the height of its parent. Dragging will work
/// between the range of minChildSize and maxChildSize (as percentages of the
/// parent container's height) as long as the builder creates a widget which
/// uses the provided [ScrollController]. If the widget created by the
/// [ScrollableWidgetBuilder] does not use the provided [ScrollController], the
/// sheet will remain at the initialChildSize.
/// 
/// By default, the widget will stay at whatever size the user drags it to. To
/// make the widget snap to specific sizes whenever they lift their finger
/// during a drag, set [snap] to `true`. The sheet will snap between
/// [minChildSize] and [maxChildSize]. Use [snapSizes] to add more sizes for
/// the sheet to snap between.
/// 
/// The snapping effect is only applied on user drags. Programmatically
/// manipulating the sheet size via [DraggableScrollableController.animateTo] or
/// [DraggableScrollableController.jumpTo] will ignore [snap] and [snapSizes].
/// 
/// By default, the widget will expand its non-occupied area to fill available
/// space in the parent. If this is not desired, e.g. because the parent wants
/// to position sheet based on the space it is taking, the [expand] property
/// may be set to false.
/// 
/// {@tool dartpad}
/// 
/// This is a sample widget which shows a [ListView] that has 25 [ListTile]s.
/// It starts out as taking up half the body of the [Scaffold], and can be
/// dragged up to the full height of the scaffold or down to 25% of the height
/// of the scaffold. Upon reaching full height, the list contents will be
/// scrolled up or down, until they reach the top of the list again and the user
/// drags the sheet back down.
/// 
/// On desktop and web running on desktop platforms, dragging to scroll with a mouse is disabled by default
/// to align with the natural behavior found in other desktop applications.
/// 
/// This behavior is dictated by the [ScrollBehavior], and can be changed by adding
/// [PointerDeviceKind.mouse] to [ScrollBehavior.dragDevices].
/// For more info on this, please refer to https://docs.flutter.dev/release/breaking-changes/default-scroll-behavior-drag
/// 
/// Alternatively, this example illustrates how to add a drag handle for desktop applications.
/// 
/// ** See code in examples/api/lib/widgets/draggable_scrollable_sheet/draggable_scrollable_sheet.0.dart **
/// {@end-tool}
	public class DraggableScrollableSheet : StatefulWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="DraggableScrollableSheet"/> class.
		/// </summary>
		public DraggableScrollableSheet(
			double initialChildSize = 0.5,
			double minChildSize = 0.25,
			double maxChildSize = 1.0,
			bool expand = true,
			bool snap = false,
			List<double>? snapSizes = null,
			TimeSpan? snapAnimationDuration = null,
			object? controller = null,
			bool shouldCloseOnMinExtent = true,
			Func<BuildContext, ScrollController, Widget> builder = null
		)
		{
			var s = GetBackingStruct<DraggableScrollableSheetStruct>();
			s.initialChildSize = initialChildSize;
			s.minChildSize = minChildSize;
			s.maxChildSize = maxChildSize;
			s.expand = expand;
			s.snap = snap;
			// Complex type: List<double>? - skipped (requires marshaling)
			// Complex type: TimeSpan? - skipped (requires marshaling)
			// Complex type: object? - skipped (requires marshaling)
			s.shouldCloseOnMinExtent = shouldCloseOnMinExtent;
			// Complex callback type: Func<BuildContext, ScrollController, Widget> - skipped (requires specific marshaling)
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new DraggableScrollableSheetStruct();
	}
}
