// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections;
using System.Collections.Generic;
using Flutter;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;
using Flutter.Services;
using Flutter.Navigation;

namespace Flutter.Material
{
/// A "drawer" icon that's appropriate for the current [TargetPlatform].
/// 
/// The current platform is determined by querying for the ambient [Theme].
/// 
/// See also:
/// 
/// * [DrawerButton], an [IconButton] with a [DrawerButtonIcon] that calls
/// [ScaffoldState.openDrawer] to open the [Scaffold.drawer].
/// * [EndDrawerButton], an [IconButton] with an [EndDrawerButtonIcon] that
/// calls [ScaffoldState.openEndDrawer] to open the [Scaffold.endDrawer].
/// * [IconButton], which is a more general widget for creating buttons
/// with icons.
/// * [Icon], a Material Design icon.
/// * [ThemeData.platform], which specifies the current platform.
	public class DrawerButtonIcon : StatelessWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="DrawerButtonIcon"/> class.
		/// </summary>
		public DrawerButtonIcon(
		)
		{
			var s = GetBackingStruct<DrawerButtonIconStruct>();
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new DrawerButtonIconStruct();
	}
}
