// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections;
using System.Collections.Generic;
using Flutter;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;
using Flutter.Services;
using Flutter.Navigation;

namespace Flutter.Material
{
/// A Material Design "elevated button".
/// 
/// Use elevated buttons to add dimension to otherwise mostly flat
/// layouts, e.g. in long busy lists of content, or in wide
/// spaces. Avoid using elevated buttons on already-elevated content
/// such as dialogs or cards.
/// 
/// An elevated button is a label [child] displayed on a [Material]
/// widget whose [Material.elevation] increases when the button is
/// pressed. The label's [Text] and [Icon] widgets are displayed in
/// [style]'s [ButtonStyle.foregroundColor] and the button's filled
/// background is the [ButtonStyle.backgroundColor].
/// 
/// The elevated button's default style is defined by
/// [defaultStyleOf]. The style of this elevated button can be
/// overridden with its [style] parameter. The style of all elevated
/// buttons in a subtree can be overridden with the
/// [ElevatedButtonTheme], and the style of all of the elevated
/// buttons in an app can be overridden with the [Theme]'s
/// [ThemeData.elevatedButtonTheme] property.
/// 
/// The static [styleFrom] method is a convenient way to create a
/// elevated button [ButtonStyle] from simple values.
/// 
/// If [onPressed] and [onLongPress] callbacks are null, then the
/// button will be disabled.
/// 
/// {@tool dartpad}
/// This sample produces an enabled and a disabled ElevatedButton.
/// 
/// ** See code in examples/api/lib/material/elevated_button/elevated_button.0.dart **
/// {@end-tool}
/// 
/// See also:
/// 
/// * [FilledButton], a filled button that doesn't elevate when pressed.
/// * [FilledButton.tonal], a filled button variant that uses a secondary fill color.
/// * [OutlinedButton], a button with an outlined border and no fill color.
/// * [TextButton], a button with no outline or fill color.
/// * <https://material.io/design/components/buttons.html>
/// * <https://m3.material.io/components/buttons>
	public class ElevatedButton : StatefulWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="ElevatedButton"/> class.
		/// </summary>
		public ElevatedButton(
			Action onPressed = null,
			Action onLongPress = null,
			Action<bool> onHover = null,
			Action<bool> onFocusChange = null,
			object? style = null,
			FocusNode? focusNode = null,
			bool autofocus = false,
			Clip? clipBehavior = Clip.None,
			object? statesController = null,
			Widget? child = null
		)
		{
			var s = GetBackingStruct<ElevatedButtonStruct>();
			// Callback: onPressed - registered with cleanup tracking
			s.onPressedAction = RegisterCallback(onPressed);
			// Callback: onLongPress - registered with cleanup tracking
			s.onLongPressAction = RegisterCallback(onLongPress);
			// Callback: onHover - registered with cleanup tracking
			s.onHoverAction = RegisterCallback(onHover);
			// Callback: onFocusChange - registered with cleanup tracking
			s.onFocusChangeAction = RegisterCallback(onFocusChange);
			// Complex type: object? - skipped (requires marshaling)
			// Complex type: FocusNode? - skipped (requires marshaling)
			s.autofocus = autofocus;
			if (clipBehavior.HasValue)
				s.clipBehavior = clipBehavior.Value;
			// Complex type: object? - skipped (requires marshaling)
			s.child = child;
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new ElevatedButtonStruct();
	}
}
