// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections;
using System.Collections.Generic;
using Flutter;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;
using Flutter.Services;
using Flutter.Navigation;

namespace Flutter.Material
{
/// Overrides the default [ExpansionTileTheme] of its [ExpansionTile] descendants.
/// 
/// See also:
/// 
/// * [ExpansionTileThemeData], which is used to configure this theme.
/// * [ThemeData.expansionTileTheme], which can be used to override the default
/// [ExpansionTileTheme] for [ExpansionTile]s below the overall [Theme].
	public class ExpansionTileTheme : InheritedWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="ExpansionTileTheme"/> class.
		/// </summary>
		public ExpansionTileTheme(
			Widget child,
			object data = null
		)
		{
			var s = GetBackingStruct<ExpansionTileThemeStruct>();
			// Complex type: object - skipped (requires marshaling)
			s.child = child;
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new ExpansionTileThemeStruct();
	}
}
