// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections.Generic;
using Flutter;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;

namespace Flutter.Widgets
{
/// Applies a translation transformation before painting its child.
/// 
/// The translation is expressed as a [Offset] scaled to the child's size. For
/// example, an [Offset] with a `dx` of 0.25 will result in a horizontal
/// translation of one quarter the width of the child.
/// 
/// Hit tests will only be detected inside the bounds of the
/// [FractionalTranslation], even if the contents are offset such that
/// they overflow.
/// 
/// See also:
/// 
/// * [Transform], which applies an arbitrary transform to its child widget at
/// paint time.
/// * [Transform.translate], which applies an absolute offset translation
/// transformation instead of an offset scaled to the child.
/// * The [catalog of layout widgets](https://flutter.dev/widgets/layout/).
	public class FractionalTranslation : SingleChildRenderObjectWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="FractionalTranslation"/> class.
		/// </summary>
		public FractionalTranslation(
		)
		{
			var backingStruct = GetBackingStruct<FractionalTranslationStruct>();
			backingStruct.translation = _translation;
			backingStruct.transformHitTests = _transformHitTests;
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new FractionalTranslationStruct();
	}
}