// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections.Generic;
using Flutter;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;

namespace Flutter.Widgets
{
/// An icon that comes from an [ImageProvider], e.g. an [AssetImage].
/// 
/// See also:
/// 
/// * [IconButton], for interactive icons.
/// * [IconTheme], which provides ambient configuration for icons.
/// * [Icon], for icons based on glyphs from fonts instead of images.
/// * [Icons], the library of Material Icons.
	public class ImageIcon : StatelessWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="ImageIcon"/> class.
		/// </summary>
		public ImageIcon(
			double? _size = null,
			string? _semanticLabel = null
		)
		{
			var backingStruct = GetBackingStruct<ImageIconStruct>();
			backingStruct.image = _image;
			backingStruct.size = _size;
			backingStruct.color = _color;
			backingStruct.semanticLabel = _semanticLabel;
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new ImageIconStruct();
	}
}