// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections;
using System.Collections.Generic;
using Flutter;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;

namespace Flutter.Widgets
{
/// A box in which children on a wheel can be scrolled.
/// 
/// This widget is similar to a [ListView] but with the restriction that all
/// children must be the same size along the scrolling axis.
/// 
/// {@youtube 560 315 https://www.youtube.com/watch?v=dUhmWAz4C7Y}
/// 
/// When the list is at the zero scroll offset, the first child is aligned with
/// the middle of the viewport. When the list is at the final scroll offset,
/// the last child is aligned with the middle of the viewport.
/// 
/// The children are rendered as if rotating on a wheel instead of scrolling on
/// a plane.
	public class ListWheelScrollView : StatefulWidget, IEnumerable<Widget>
	{
		/// <summary>
		/// Internal list for collection initializer support
		/// </summary>
		private List<Widget> _childrenList = new List<Widget>();

		/// <summary>
		/// Adds a child widget. Supports collection initializer syntax.
		/// </summary>
		public void Add(Widget child)
		{
			_childrenList.Add(child);
		}

		/// <summary>
		/// Adds multiple child widgets.
		/// </summary>
		public void AddRange(IEnumerable<Widget> children)
		{
			_childrenList.AddRange(children);
		}

		/// <summary>
		/// Gets the enumerator for child widgets.
		/// </summary>
		public IEnumerator<Widget> GetEnumerator() => _childrenList.GetEnumerator();

		/// <summary>
		/// Gets the enumerator for child widgets.
		/// </summary>
		IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

		/// <summary>
		/// Initializes a new instance of the <see cref="ListWheelScrollView"/> class.
		/// Use collection initializer syntax: new ListWheelScrollView { child1, child2, child3 }
		/// </summary>
		public ListWheelScrollView()
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="ListWheelScrollView"/> class.
		/// </summary>
		public ListWheelScrollView(
			double diameterRatio,
			double perspective,
			double offAxisFraction,
			bool useMagnifier,
			double magnification,
			double overAndUnderCenterOpacity,
			double itemExtent,
			double squeeze,
			Action onSelectedItemChanged,
			bool renderChildrenOutsideViewport,
			ListWheelChildDelegate childDelegate,
			Clip clipBehavior,
			PlatformViewHitTestBehavior hitTestBehavior,
			DragStartBehavior dragStartBehavior,
			List<Widget> children
,
			ScrollController? controller = null,
			ScrollPhysics? physics = null,
			string? restorationId = null,
			ScrollBehavior? scrollBehavior = null
		)
		{
			if (children != null)
				_childrenList.AddRange(children);
			var s = GetBackingStruct<ListWheelScrollViewStruct>();
			// Complex type: ScrollController? - skipped (requires marshaling)
			// Complex type: ScrollPhysics? - skipped (requires marshaling)
			s.diameterRatio = diameterRatio;
			s.perspective = perspective;
			s.offAxisFraction = offAxisFraction;
			s.useMagnifier = useMagnifier;
			s.magnification = magnification;
			s.overAndUnderCenterOpacity = overAndUnderCenterOpacity;
			s.itemExtent = itemExtent;
			s.squeeze = squeeze;
			// Complex type: Action - skipped (requires marshaling)
			s.renderChildrenOutsideViewport = renderChildrenOutsideViewport;
			// Complex type: ListWheelChildDelegate - skipped (requires marshaling)
			s.clipBehavior = clipBehavior;
			s.hitTestBehavior = hitTestBehavior;
			s.restorationId = restorationId;
			// Complex type: ScrollBehavior? - skipped (requires marshaling)
			s.dragStartBehavior = dragStartBehavior;
			// Children are set in PrepareForSending to support collection initializers
		}

		/// <summary>
		/// Prepares the widget for sending to Flutter, including setting children.
		/// </summary>
		internal new void PrepareForSending()
		{
			var s = GetBackingStruct<ListWheelScrollViewStruct>();
			s.children = SetChildrenAndGetPointer(_childrenList);
			base.PrepareForSending();
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new ListWheelScrollViewStruct();
	}
}
