// <auto-generated>
// This file was manually created for FlutterSharp Phase 4 - ListTile implementation
// </auto-generated>

using System;
using System.Collections;
using System.Collections.Generic;
using Flutter;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;

namespace Flutter.Widgets
{
/// A single fixed-height row that typically contains some text as well as
/// a leading or trailing icon.
///
/// A list tile contains one to three lines of text optionally flanked by icons or
/// other widgets, such as check boxes. The icons (or other widgets) for the
/// tile are defined with the [leading] and [trailing] parameters. The first line
/// of text is not optional and is specified with [title]. The value of [subtitle],
/// which is optional, will occupy the space allocated for an additional line of
/// text, or two lines if [isThreeLine] is true.
///
/// List tiles are typically used in [ListView]s, or arranged in [Column]s in
/// [Drawer]s and [Card]s.
///
/// See also:
///  * [ListTileTheme], which defines visual properties for [ListTile]s.
///  * [ListView], which can display an arbitrary number of [ListTile]s.
///  * [Card], which can be used to display a single [ListTile].
///  * [Drawer], which can be used to display a list of [ListTile]s.
	public class ListTile : StatelessWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="ListTile"/> class.
		/// </summary>
		/// <param name="leading">A widget to display before the title.</param>
		/// <param name="title">The primary content of the list tile.</param>
		/// <param name="subtitle">Additional content displayed below the title.</param>
		/// <param name="trailing">A widget to display after the title.</param>
		/// <param name="isThreeLine">Whether this list tile is intended to display three lines of text.</param>
		/// <param name="dense">Whether this list tile is part of a vertically dense list.</param>
		/// <param name="enabled">Whether this list tile is interactive.</param>
		/// <param name="selected">If this tile is also enabled then icons and text are rendered with the same color.</param>
		/// <param name="onTap">Called when the user taps this list tile.</param>
		/// <param name="onLongPress">Called when the user long-presses on this list tile.</param>
		/// <param name="onFocusChange">Called when the focus changes.</param>
		/// <param name="tileColor">Defines the background color of ListTile when selected is false (ARGB format).</param>
		/// <param name="selectedTileColor">Defines the background color of ListTile when selected is true (ARGB format).</param>
		/// <param name="iconColor">Defines the default color for leading and trailing icons (ARGB format).</param>
		/// <param name="textColor">Defines the default color for the title and subtitle (ARGB format).</param>
		/// <param name="focusColor">The color for the tile's Material when it has the input focus (ARGB format).</param>
		/// <param name="hoverColor">The color for the tile's Material when a pointer is hovering over it (ARGB format).</param>
		/// <param name="splashColor">The color of splash for the tile's Material (ARGB format).</param>
		/// <param name="autofocus">True if this widget will be selected as the initial focus.</param>
		/// <param name="enableFeedback">Whether detected gestures should provide acoustic and/or haptic feedback.</param>
		/// <param name="horizontalTitleGap">The horizontal gap between the titles and the leading/trailing widgets.</param>
		/// <param name="minVerticalPadding">The minimum padding on the top and bottom of the title and subtitle widgets.</param>
		/// <param name="minLeadingWidth">The minimum width allocated for the leading widget.</param>
		/// <param name="minTileHeight">The minimum height allocated for the ListTile widget.</param>
		/// <param name="titleAlignment">Defines how leading and trailing are vertically aligned.</param>
		/// <param name="style">Defines the font used for the title.</param>
		public ListTile(
			Widget? leading = null,
			Widget? title = null,
			Widget? subtitle = null,
			Widget? trailing = null,
			bool isThreeLine = false,
			bool? dense = null,
			bool enabled = true,
			bool selected = false,
			Action? onTap = null,
			Action? onLongPress = null,
			Action<bool>? onFocusChange = null,
			uint? tileColor = null,
			uint? selectedTileColor = null,
			uint? iconColor = null,
			uint? textColor = null,
			uint? focusColor = null,
			uint? hoverColor = null,
			uint? splashColor = null,
			bool autofocus = false,
			bool? enableFeedback = null,
			double? horizontalTitleGap = null,
			double? minVerticalPadding = null,
			double? minLeadingWidth = null,
			double? minTileHeight = null,
			ListTileTitleAlignment? titleAlignment = null,
			ListTileStyle? style = null
		)
		{
			var s = GetBackingStruct<ListTileStruct>();

			// Widget properties
			s.leading = GetWidgetHandle(leading);
			s.title = GetWidgetHandle(title);
			s.subtitle = GetWidgetHandle(subtitle);
			s.trailing = GetWidgetHandle(trailing);

			// Boolean properties
			s.HasisThreeLine = 1;
			s.isThreeLine = isThreeLine;

			if (dense.HasValue)
			{
				s.Hasdense = 1;
				s.dense = dense.Value;
			}

			s.Hasenabled = 1;
			s.enabled = enabled;

			s.Hasselected = 1;
			s.selected = selected;

			s.Hasautofocus = 1;
			s.autofocus = autofocus;

			if (enableFeedback.HasValue)
			{
				s.HasenableFeedback = 1;
				s.enableFeedback = enableFeedback.Value;
			}

			// Callback properties
			s.onTapAction = RegisterCallback(onTap);
			s.onLongPressAction = RegisterCallback(onLongPress);
			s.onFocusChangeAction = RegisterCallback(onFocusChange);

			// Color properties (ARGB format)
			if (tileColor.HasValue)
			{
				s.HastileColor = 1;
				s.tileColor = tileColor.Value;
			}

			if (selectedTileColor.HasValue)
			{
				s.HasselectedTileColor = 1;
				s.selectedTileColor = selectedTileColor.Value;
			}

			if (iconColor.HasValue)
			{
				s.HasiconColor = 1;
				s.iconColor = iconColor.Value;
			}

			if (textColor.HasValue)
			{
				s.HastextColor = 1;
				s.textColor = textColor.Value;
			}

			if (focusColor.HasValue)
			{
				s.HasfocusColor = 1;
				s.focusColor = focusColor.Value;
			}

			if (hoverColor.HasValue)
			{
				s.HashoverColor = 1;
				s.hoverColor = hoverColor.Value;
			}

			if (splashColor.HasValue)
			{
				s.HassplashColor = 1;
				s.splashColor = splashColor.Value;
			}

			// Numeric properties
			if (horizontalTitleGap.HasValue)
			{
				s.HashorizontalTitleGap = 1;
				s.horizontalTitleGap = horizontalTitleGap.Value;
			}

			if (minVerticalPadding.HasValue)
			{
				s.HasminVerticalPadding = 1;
				s.minVerticalPadding = minVerticalPadding.Value;
			}

			if (minLeadingWidth.HasValue)
			{
				s.HasminLeadingWidth = 1;
				s.minLeadingWidth = minLeadingWidth.Value;
			}

			if (minTileHeight.HasValue)
			{
				s.HasminTileHeight = 1;
				s.minTileHeight = minTileHeight.Value;
			}

			// Enum properties
			if (titleAlignment.HasValue)
			{
				s.titleAlignment = (int)titleAlignment.Value;
			}
			else
			{
				s.titleAlignment = -1; // Sentinel for null
			}

			if (style.HasValue)
			{
				s.style = (int)style.Value;
			}
			else
			{
				s.style = -1; // Sentinel for null
			}
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new ListTileStruct();
	}
}
