// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections;
using System.Collections.Generic;
using Flutter;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;
using Flutter.Services;
using Flutter.Navigation;

namespace Flutter.Material
{
/// An inherited widget that defines color and style parameters for [ListTile]s
/// in this widget's subtree.
/// 
/// Values specified here are used for [ListTile] properties that are not given
/// an explicit non-null value.
/// 
/// The [Drawer] widget specifies a tile theme for its children which sets
/// [style] to [ListTileStyle.drawer].
	public class ListTileTheme : InheritedWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="ListTileTheme"/> class.
		/// </summary>
		public ListTileTheme(
			Widget child,
			object data = null,
			bool? dense = null,
			object? shape = null,
			object? style = null,
			Color? selectedColor = null,
			Color? iconColor = null,
			Color? textColor = null,
			EdgeInsetsGeometry? contentPadding = null,
			Color? tileColor = null,
			Color? selectedTileColor = null,
			double? horizontalTitleGap = null,
			double? minVerticalPadding = null,
			double? minLeadingWidth = null,
			bool? enableFeedback = null,
			object? controlAffinity = null,
			object? mouseCursor = null
		)
		{
			var s = GetBackingStruct<ListTileThemeStruct>();
			// Complex type: object - skipped (requires marshaling)
			if (dense.HasValue)
				s.dense = dense.Value;
			// Complex type: object? - skipped (requires marshaling)
			// Complex type: object? - skipped (requires marshaling)
			// Complex type: Color? - skipped (requires marshaling)
			// Complex type: Color? - skipped (requires marshaling)
			// Complex type: Color? - skipped (requires marshaling)
			s.contentPadding = MarshalEdgeInsetsGeometry(contentPadding);
			// Complex type: Color? - skipped (requires marshaling)
			// Complex type: Color? - skipped (requires marshaling)
			if (horizontalTitleGap.HasValue)
				s.horizontalTitleGap = horizontalTitleGap.Value;
			if (minVerticalPadding.HasValue)
				s.minVerticalPadding = minVerticalPadding.Value;
			if (minLeadingWidth.HasValue)
				s.minLeadingWidth = minLeadingWidth.Value;
			if (enableFeedback.HasValue)
				s.enableFeedback = enableFeedback.Value;
			// Complex type: object? - skipped (requires marshaling)
			// Complex type: object? - skipped (requires marshaling)
			s.child = child;
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new ListTileThemeStruct();
	}
}
