// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections;
using System.Collections.Generic;
using Flutter;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;
using Flutter.Services;
using Flutter.Navigation;

namespace Flutter.Material
{
/// A button for use in a [MenuBar], in a menu created with [MenuAnchor], or on
/// its own, that can be activated by click or keyboard navigation.
/// 
/// This widget represents a leaf entry in a menu hierarchy that is typically
/// part of a [MenuBar], but may be used independently, or as part of a menu
/// created with a [MenuAnchor].
/// 
/// {@macro flutter.material.MenuBar.shortcuts_note}
/// 
/// See also:
/// 
/// * [MenuBar], a class that creates a top level menu bar in a Material Design
/// style.
/// * [MenuAnchor], a widget that creates a region with a submenu and shows it
/// when requested.
/// * [SubmenuButton], a menu item similar to this one which manages a submenu.
/// * [PlatformMenuBar], which creates a menu bar that is rendered by the host
/// platform instead of by Flutter (on macOS, for example).
/// * [ShortcutRegistry], a registry of shortcuts that apply for the entire
/// application.
/// * [VoidCallbackIntent], to define intents that will call a [VoidCallback] and
/// work with the [Actions] and [Shortcuts] system.
/// * [CallbackShortcuts] to define shortcuts that call a callback without
/// involving [Actions].
	public class MenuItemButton : StatefulWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="MenuItemButton"/> class.
		/// </summary>
		public MenuItemButton(
			bool enabled,
			Action onPressed = null,
			Action<bool> onHover = null,
			bool requestFocusOnHover = true,
			Action<bool> onFocusChange = null,
			FocusNode? focusNode = null,
			bool autofocus = false,
			object? shortcut = null,
			string? semanticsLabel = null,
			object? style = null,
			object? statesController = null,
			Clip clipBehavior = Clip.None,
			Widget? leadingIcon = null,
			Widget? trailingIcon = null,
			bool closeOnActivate = true,
			Axis overflowAxis = Axis.Horizontal,
			Widget? child = null
		)
		{
			var s = GetBackingStruct<MenuItemButtonStruct>();
			// Callback: onPressed - registered with cleanup tracking
			s.onPressedAction = RegisterCallback(onPressed);
			// Callback: onHover - registered with cleanup tracking
			s.onHoverAction = RegisterCallback(onHover);
			s.requestFocusOnHover = requestFocusOnHover;
			// Callback: onFocusChange - registered with cleanup tracking
			s.onFocusChangeAction = RegisterCallback(onFocusChange);
			// Complex type: FocusNode? - skipped (requires marshaling)
			s.autofocus = autofocus;
			// Complex type: object? - skipped (requires marshaling)
			s.semanticsLabel = semanticsLabel;
			// Complex type: object? - skipped (requires marshaling)
			// Complex type: object? - skipped (requires marshaling)
			s.clipBehavior = clipBehavior;
			s.leadingIcon = GetWidgetHandle(leadingIcon);
			s.trailingIcon = GetWidgetHandle(trailingIcon);
			s.closeOnActivate = closeOnActivate;
			s.overflowAxis = overflowAxis;
			s.child = child;
			s.enabled = enabled;
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new MenuItemButtonStruct();
	}
}
