// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections;
using System.Collections.Generic;
using Flutter;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;

namespace Flutter.Widgets
{
/// A widget that imposes different constraints on its child than it gets
/// from its parent, possibly allowing the child to overflow the parent.
/// 
/// {@tool dartpad}
/// This example shows how an [OverflowBox] is used, and what its effect is.
/// 
/// ** See code in examples/api/lib/widgets/basic/overflowbox.0.dart **
/// {@end-tool}
/// 
/// See also:
/// 
/// * [RenderConstrainedOverflowBox] for details about how [OverflowBox] is
/// rendered.
/// * [SizedOverflowBox], a widget that is a specific size but passes its
/// original constraints through to its child, which may then overflow.
/// * [ConstrainedBox], a widget that imposes additional constraints on its
/// child.
/// * [UnconstrainedBox], a container that tries to let its child draw without
/// constraints.
/// * [SizedBox], a box with a specified size.
/// * The [catalog of layout widgets](https://flutter.dev/widgets/layout/).
	public class OverflowBox : SingleChildRenderObjectWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="OverflowBox"/> class.
		/// </summary>
		public OverflowBox(
			AlignmentGeometry? _alignment,
			BoxFit _fit
,
			double? _minWidth = null,
			double? _maxWidth = null,
			double? _minHeight = null,
			double? _maxHeight = null,
			Widget? _child = null
		)
		{
			var s = GetBackingStruct<OverflowBoxStruct>();
			// Complex type: AlignmentGeometry? - skipped (requires marshaling)
			if (_minWidth.HasValue)
				s.minWidth = _minWidth.Value;
			if (_maxWidth.HasValue)
				s.maxWidth = _maxWidth.Value;
			if (_minHeight.HasValue)
				s.minHeight = _minHeight.Value;
			if (_maxHeight.HasValue)
				s.maxHeight = _maxHeight.Value;
			s.fit = _fit;
			s.child = _child;
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new OverflowBoxStruct();
	}
}
