// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections;
using System.Collections.Generic;
using Flutter;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;
using Flutter.Services;
using Flutter.Navigation;

namespace Flutter.Material
{
/// A base class for entries in a Material Design popup menu.
/// 
/// The popup menu widget uses this interface to interact with the menu items.
/// To show a popup menu, use the [showMenu] function. To create a button that
/// shows a popup menu, consider using [PopupMenuButton].
/// 
/// The type `T` is the type of the value(s) the entry represents. All the
/// entries in a given menu must represent values with consistent types.
/// 
/// A [PopupMenuEntry] may represent multiple values, for example a row with
/// several icons, or a single entry, for example a menu item with an icon (see
/// [PopupMenuItem]), or no value at all (for example, [PopupMenuDivider]).
/// 
/// See also:
/// 
/// * [PopupMenuItem], a popup menu entry for a single value.
/// * [PopupMenuDivider], a popup menu entry that is just a horizontal line.
/// * [CheckedPopupMenuItem], a popup menu item with a checkmark.
/// * [showMenu], a method to dynamically show a popup menu at a given location.
/// * [PopupMenuButton], an [IconButton] that automatically shows a menu when
/// it is tapped.
	public abstract class PopupMenuEntry<T> : StatefulWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="PopupMenuEntry"/> class.
		/// </summary>
		protected PopupMenuEntry()
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="PopupMenuEntry"/> class.
		/// </summary>
		public PopupMenuEntry(
			double height
		)
		{
			var s = GetBackingStruct<PopupMenuEntryStruct>();
			s.height = height;
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new PopupMenuEntryStruct();
	}
}
