// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections;
using System.Collections.Generic;
using Flutter;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;

namespace Flutter.Widgets
{
/// A widget that detects gestures described by the given gesture
/// factories.
/// 
/// For common gestures, use a [GestureDetector].
/// [RawGestureDetector] is useful primarily when developing your
/// own gesture recognizers.
/// 
/// Configuring the gesture recognizers requires a carefully constructed map, as
/// described in [gestures] and as shown in the example below.
/// 
/// {@tool snippet}
/// 
/// This example shows how to hook up a [TapGestureRecognizer]. It assumes that
/// the code is being used inside a [State] object with a `_last` field that is
/// then displayed as the child of the gesture detector.
/// 
/// ```dart
/// RawGestureDetector(
/// gestures: <Type, GestureRecognizerFactory>{
/// TapGestureRecognizer: GestureRecognizerFactoryWithHandlers<TapGestureRecognizer>(
/// () => TapGestureRecognizer(),
/// (TapGestureRecognizer instance) {
/// instance
/// ..onTapDown = (TapDownDetails details) { setState(() { _last = 'down'; }); }
/// ..onTapUp = (TapUpDetails details) { setState(() { _last = 'up'; }); }
/// ..onTap = () { setState(() { _last = 'tap'; }); }
/// ..onTapCancel = () { setState(() { _last = 'cancel'; }); };
/// },
/// ),
/// },
/// child: Container(width: 300.0, height: 300.0, color: Colors.yellow, child: Text(_last)),
/// )
/// ```
/// {@end-tool}
/// 
/// See also:
/// 
/// * [GestureDetector], a less flexible but much simpler widget that does the same thing.
/// * [Listener], a widget that reports raw pointer events.
/// * [GestureRecognizer], the class that you extend to create a custom gesture recognizer.
	public class RawGestureDetector : StatefulWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="RawGestureDetector"/> class.
		/// </summary>
		public RawGestureDetector(
			HitTestBehavior behavior,
			Widget? child = null,
			Dictionary<object, object> gestures = null,
			bool excludeFromSemantics = false,
			SemanticsGestureDelegate? semantics = null
		)
		{
			var s = GetBackingStruct<RawGestureDetectorStruct>();
			s.child = child;
			// Complex type: Dictionary<object, object> - skipped (requires marshaling)
			s.behavior = behavior;
			s.excludeFromSemantics = excludeFromSemantics;
			// Complex type: SemanticsGestureDelegate? - skipped (requires marshaling)
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new RawGestureDetectorStruct();
	}
}
