// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections;
using System.Collections.Generic;
using Flutter;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;

namespace Flutter.Widgets
{
/// A common base class for magnifiers.
/// 
/// {@tool dartpad}
/// This sample demonstrates what a magnifier is, and how it can be used.
/// 
/// ** See code in examples/api/lib/widgets/magnifier/magnifier.0.dart **
/// {@end-tool}
/// 
/// {@template flutter.widgets.magnifier.intro}
/// This magnifying glass is useful for scenarios on mobile devices where
/// the user's finger may be covering part of the screen where a granular
/// action is being performed, such as navigating a small cursor with a drag
/// gesture, on an image or text.
/// {@endtemplate}
/// 
/// A magnifier can be conveniently managed by [MagnifierController], which handles
/// showing and hiding the magnifier, with an optional entry / exit animation.
/// 
/// See:
/// * [MagnifierController], a controller to handle magnifiers in an overlay.
	public class RawMagnifier : StatelessWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="RawMagnifier"/> class.
		/// </summary>
		public RawMagnifier(
			MagnifierDecoration _decoration,
			Clip _clipBehavior,
			object _focalPointOffset,
			double _magnificationScale,
			Size _size
,
			Widget? _child = null
		)
		{
			var s = GetBackingStruct<RawMagnifierStruct>();
			s.child = _child;
			// Complex type: MagnifierDecoration - skipped (requires marshaling)
			s.clipBehavior = _clipBehavior;
			// Complex type: object - skipped (requires marshaling)
			s.magnificationScale = _magnificationScale;
			// Complex type: Size - skipped (requires marshaling)
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new RawMagnifierStruct();
	}
}
