// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections.Generic;
using Flutter;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;

namespace Flutter.Widgets
{
/// A wrapper widget that will recognize the start of a drag on the wrapped
/// widget by a [PointerDownEvent], and immediately initiate dragging the
/// wrapped item to a new location in a reorderable list.
/// 
/// See also:
/// 
/// * [ReorderableDelayedDragStartListener], a similar wrapper that will
/// only recognize the start after a long press event.
/// * [ReorderableList], a widget list that allows the user to reorder
/// its items.
/// * [SliverReorderableList], a sliver list that allows the user to reorder
/// its items.
/// * [ReorderableListView], a Material Design list that allows the user to
/// reorder its items.
	public class ReorderableDragStartListener : StatelessWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="ReorderableDragStartListener"/> class.
		/// </summary>
		public ReorderableDragStartListener(
			Widget _child,
			int _index,
			bool _enabled

		)
		{
			// TODO: Property assignments will be handled by a proper FFI marshaling layer
			// For now, constructors accept parameters but don't assign them
			// This avoids type mismatch errors where C# objects would be assigned to nint struct fields
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new ReorderableDragStartListenerStruct();
	}
}
