// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections.Generic;
using Flutter;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;

namespace Flutter.Widgets
{
/// Animates the rotation of a widget.
/// 
/// Here's an illustration of the [RotationTransition] widget, with it's [turns]
/// animated by a [CurvedAnimation] set to [Curves.elasticOut]:
/// {@animation 300 378 https://flutter.github.io/assets-for-api-docs/assets/widgets/rotation_transition.mp4}
/// 
/// {@tool dartpad}
/// The following code implements the [RotationTransition] as seen in the video
/// above:
/// 
/// ** See code in examples/api/lib/widgets/transitions/rotation_transition.0.dart **
/// {@end-tool}
/// 
/// See also:
/// 
/// * [ScaleTransition], a widget that animates the scale of a transformed
/// widget.
/// * [SizeTransition], a widget that animates its own size and clips and
/// aligns its child.
	public class RotationTransition : StatefulWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="RotationTransition"/> class.
		/// </summary>
		public RotationTransition(
			InvalidType _turns

		)
		{
			// TODO: Property assignments will be handled by a proper FFI marshaling layer
			// For now, constructors accept parameters but don't assign them
			// This avoids type mismatch errors where C# objects would be assigned to nint struct fields
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new RotationTransitionStruct();
	}
}
