// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections.Generic;
using Flutter;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;

namespace Flutter.Widgets
{
/// A [SelectionContainer] that allows the user to access the [SelectionDetails] and
/// listen to selection changes for the child subtree it wraps under a [SelectionArea]
/// or [SelectableRegion].
/// 
/// The selection updates are provided through the [selectionNotifier], to listen
/// to these updates attach a listener through [SelectionListenerNotifier.addListener].
/// 
/// This widget does not listen to selection changes of nested [SelectionArea]s
/// or [SelectableRegion]s in its subtree because those widgets are self-contained
/// and do not bubble up their selection. To listen to selection changes of a
/// [SelectionArea] or [SelectableRegion] under this [SelectionListener], add
/// an additional [SelectionListener] under each one.
/// 
/// {@tool dartpad}
/// This example shows how to use [SelectionListener] to access the [SelectionDetails]
/// under a [SelectionArea] or [SelectableRegion].
/// 
/// ** See code in examples/api/lib/material/selection_area/selection_area.1.dart **
/// {@end-tool}
/// 
/// {@tool dartpad}
/// This example shows how to color the active selection red under a
/// [SelectionArea] or [SelectableRegion].
/// 
/// ** See code in examples/api/lib/material/selection_area/selection_area.2.dart **
/// {@end-tool}
/// 
/// See also:
/// 
/// * [SelectableRegion], which provides an overview of the selection system.
	public class SelectionListener : StatefulWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="SelectionListener"/> class.
		/// </summary>
		public SelectionListener(
		)
		{
			var backingStruct = GetBackingStruct<SelectionListenerStruct>();
			backingStruct.selectionNotifier = _selectionNotifier;
			backingStruct.child = _child;
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new SelectionListenerStruct();
	}
}