// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections;
using System.Collections.Generic;
using Flutter;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;

namespace Flutter.Widgets
{
/// Builds a sliver widget tree that can depend on its own [SliverConstraints].
/// 
/// Similar to the [LayoutBuilder] widget except its builder should return a sliver
/// widget, and [SliverLayoutBuilder] is itself a sliver. The framework calls the
/// [builder] function at layout time and provides the current [SliverConstraints].
/// The [SliverLayoutBuilder]'s final [SliverGeometry] will match the [SliverGeometry]
/// of its child.
/// 
/// {@macro flutter.widgets.ConstrainedLayoutBuilder}
/// 
/// See also:
/// 
/// * [LayoutBuilder], the non-sliver version of this widget.
	public class SliverLayoutBuilder : Widget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="SliverLayoutBuilder"/> class.
		/// </summary>
		public SliverLayoutBuilder(
			Action? builder = null
		)
		{
			var s = GetBackingStruct<SliverLayoutBuilderStruct>();
			// Callback: builder
			if (builder != null)
			{
				var actionId = CallbackRegistry.Register(builder);
				s.builderAction = $"action_{actionId}";
			}
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new SliverLayoutBuilderStruct();
	}
}
