// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections.Generic;
using Flutter;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;

namespace Flutter.Widgets
{
/// A sliver that insets another sliver by sufficient padding to avoid
/// intrusions by the operating system.
/// 
/// For example, this will indent the sliver by enough to avoid the status bar
/// at the top of the screen.
/// 
/// It will also indent the sliver by the amount necessary to avoid The Notch
/// on the iPhone X, or other similar creative physical features of the
/// display.
/// 
/// When a [minimum] padding is specified, the greater of the minimum padding
/// or the safe area padding will be applied.
/// 
/// See also:
/// 
/// * [SafeArea], for insetting box widgets to avoid operating system intrusions.
/// * [SliverPadding], for insetting slivers in general.
/// * [MediaQuery], from which the window padding is obtained.
/// * [dart:ui.FlutterView.padding], which reports the padding from the operating
/// system.
	public class SliverSafeArea : StatelessWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="SliverSafeArea"/> class.
		/// </summary>
		public SliverSafeArea(
			bool _left,
			bool _top,
			bool _right,
			bool _bottom,
			object _minimum,
			Widget _sliver

		)
		{
			// TODO: Property assignments will be handled by a proper FFI marshaling layer
			// For now, constructors accept parameters but don't assign them
			// This avoids type mismatch errors where C# objects would be assigned to nint struct fields
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new SliverSafeAreaStruct();
	}
}
