// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections.Generic;
using Flutter;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;

namespace Flutter.Widgets
{
/// A sliver whose size varies when the sliver is scrolled to the edge
/// of the viewport opposite the sliver's [GrowthDirection].
/// 
/// In the normal case of a [CustomScrollView] with no centered sliver, this
/// sliver will vary its size when scrolled to the leading edge of the viewport.
/// 
/// This is the layout primitive that [SliverAppBar] uses for its
/// shrinking/growing effect.
/// 
/// _To learn more about slivers, see [CustomScrollView.slivers]._
	public class SliverPersistentHeader : StatelessWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="SliverPersistentHeader"/> class.
		/// </summary>
		public SliverPersistentHeader(
		)
		{
			var backingStruct = GetBackingStruct<SliverPersistentHeaderStruct>();
			backingStruct.@delegate = _delegate;
			backingStruct.pinned = _pinned;
			backingStruct.floating = _floating;
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new SliverPersistentHeaderStruct();
	}
}