// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections;
using System.Collections.Generic;
using Flutter;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;
using Flutter.Services;
using Flutter.Navigation;

namespace Flutter.Widgets
{
/// A [SliverList] that animates items when they are inserted or removed.
/// 
/// This widget's [SliverAnimatedListState] can be used to dynamically insert or
/// remove items. To refer to the [SliverAnimatedListState] either provide a
/// [GlobalKey] or use the static [SliverAnimatedList.of] method from a list item's
/// input callback.
/// 
/// {@tool dartpad}
/// This sample application uses a [SliverAnimatedList] to create an animated
/// effect when items are removed or added to the list.
/// 
/// ** See code in examples/api/lib/widgets/animated_list/sliver_animated_list.0.dart **
/// {@end-tool}
/// 
/// See also:
/// 
/// * [SliverList], which does not animate items when they are inserted or
/// removed.
/// * [AnimatedList], a non-sliver scrolling container that animates items when
/// they are inserted or removed.
/// * [SliverAnimatedGrid], a sliver which animates items when they are
/// inserted into or removed from a grid.
/// * [AnimatedGrid], a non-sliver scrolling container that animates items when
/// they are inserted into or removed from a grid.
	public class SliverAnimatedList : StatefulWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="SliverAnimatedList"/> class.
		/// </summary>
		public SliverAnimatedList(
			Func<BuildContext, int, Animation, Widget> itemBuilder = null,
			Func<string, int?> findChildIndexCallback = null,
			int initialItemCount = 0
		)
		{
			var s = GetBackingStruct<SliverAnimatedListStruct>();
			// Complex callback type: Func<BuildContext, int, Animation, Widget> - skipped (requires specific marshaling)
			// Complex callback type: Func<string, int?> - skipped (requires specific marshaling)
			s.initialItemCount = initialItemCount;
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new SliverAnimatedListStruct();
	}
}
