// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections.Generic;
using Flutter;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;

namespace Flutter.Widgets
{
/// A Material Design visual indication that a scroll view has overscrolled.
/// 
/// A [StretchingOverscrollIndicator] listens for [ScrollNotification]s in order
/// to stretch the content of the [Scrollable]. These notifications are typically
/// generated by a [ScrollView], such as a [ListView] or a [GridView].
/// 
/// When triggered, the [StretchingOverscrollIndicator] generates an
/// [OverscrollIndicatorNotification] before showing an overscroll indication.
/// To prevent the indicator from showing the indication, call
/// [OverscrollIndicatorNotification.disallowIndicator] on the notification.
/// 
/// Created by [MaterialScrollBehavior.buildOverscrollIndicator] on platforms
/// (e.g., Android) that commonly use this type of overscroll indication when
/// [ThemeData.useMaterial3] is true. Otherwise, when [ThemeData.useMaterial3]
/// is false, a [GlowingOverscrollIndicator] is used instead.=
/// 
/// See also:
/// 
/// * [OverscrollIndicatorNotification], which can be used to prevent the
/// stretch effect from being applied at all.
/// * [NotificationListener], to listen for the
/// [OverscrollIndicatorNotification].
/// * [GlowingOverscrollIndicator], the default overscroll indicator for
/// [TargetPlatform.android] and [TargetPlatform.fuchsia].
	public class StretchingOverscrollIndicator : StatefulWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="StretchingOverscrollIndicator"/> class.
		/// </summary>
		public StretchingOverscrollIndicator(
			Widget? _child = null
		)
		{
			var backingStruct = GetBackingStruct<StretchingOverscrollIndicatorStruct>();
			backingStruct.axisDirection = _axisDirection;
			backingStruct.notificationPredicate = _notificationPredicate;
			backingStruct.clipBehavior = _clipBehavior;
			backingStruct.child = _child;
			backingStruct.axis = _axis;
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new StretchingOverscrollIndicatorStruct();
	}
}