// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections;
using System.Collections.Generic;
using Flutter;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;
using Flutter.Services;
using Flutter.Navigation;

namespace Flutter.Material
{
/// An inherited widget that defines the configuration for time pickers
/// displayed using [showTimePicker] in this widget's subtree.
/// 
/// Values specified here are used for time picker properties that are not
/// given an explicit non-null value.
	public class TimePickerTheme : InheritedWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="TimePickerTheme"/> class.
		/// </summary>
		public TimePickerTheme(
			Widget child,
			object data = null
		)
		{
			var s = GetBackingStruct<TimePickerThemeStruct>();
			// Complex type: object - skipped (requires marshaling)
			s.child = child;
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new TimePickerThemeStruct();
	}
}
