// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Collections.Generic;
using Flutter;
using Flutter.Structs;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;

namespace Flutter.Widgets
{
/// A widget through which a portion of larger content can be viewed, typically
/// in combination with a [TwoDimensionalScrollable].
/// 
/// [TwoDimensionalViewport] is the visual workhorse of the two dimensional
/// scrolling machinery. It displays a subset of its children according to its
/// own dimensions and the given [horizontalOffset] an [verticalOffset]. As the
/// offsets vary, different children are visible through the viewport.
/// 
/// Subclasses must implement [createRenderObject] and [updateRenderObject].
/// Both of these methods require the render object to be a subclass of
/// [RenderTwoDimensionalViewport]. This class will create its own
/// [RenderObjectElement] which already implements the
/// [TwoDimensionalChildManager], which means subclasses should cast the
/// [BuildContext] to provide as the child manager to the
/// [RenderTwoDimensionalViewport].
/// 
/// {@tool snippet}
/// This is an example of a subclass implementation of [TwoDimensionalViewport],
/// `SimpleTwoDimensionalViewport`. The `RenderSimpleTwoDimensionalViewport` is
/// a subclass of [RenderTwoDimensionalViewport].
/// 
/// ```dart
/// class SimpleTwoDimensionalViewport extends TwoDimensionalViewport {
/// const SimpleTwoDimensionalViewport({
/// super.key,
/// required super.verticalOffset,
/// required super.verticalAxisDirection,
/// required super.horizontalOffset,
/// required super.horizontalAxisDirection,
/// required super.delegate,
/// required super.mainAxis,
/// super.cacheExtent,
/// super.clipBehavior = Clip.hardEdge,
/// });
/// 
/// @override
/// RenderSimpleTwoDimensionalViewport createRenderObject(BuildContext context) {
/// return RenderSimpleTwoDimensionalViewport(
/// horizontalOffset: horizontalOffset,
/// horizontalAxisDirection: horizontalAxisDirection,
/// verticalOffset: verticalOffset,
/// verticalAxisDirection: verticalAxisDirection,
/// mainAxis: mainAxis,
/// delegate: delegate,
/// childManager: context as TwoDimensionalChildManager,
/// cacheExtent: cacheExtent,
/// clipBehavior: clipBehavior,
/// );
/// }
/// 
/// @override
/// void updateRenderObject(BuildContext context, RenderSimpleTwoDimensionalViewport renderObject) {
/// renderObject
/// ..horizontalOffset = horizontalOffset
/// ..horizontalAxisDirection = horizontalAxisDirection
/// ..verticalOffset = verticalOffset
/// ..verticalAxisDirection = verticalAxisDirection
/// ..mainAxis = mainAxis
/// ..delegate = delegate
/// ..cacheExtent = cacheExtent
/// ..clipBehavior = clipBehavior;
/// }
/// }
/// ```
/// {@end-tool}
/// 
/// See also:
/// 
/// * [Viewport], the equivalent of this widget that scrolls in only one
/// dimension.
	public abstract class TwoDimensionalViewport : RenderObjectWidget
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="TwoDimensionalViewport"/> class.
		/// </summary>
		public TwoDimensionalViewport(
			double? _cacheExtent = null
		)
		{
			var backingStruct = GetBackingStruct<TwoDimensionalViewportStruct>();
			backingStruct.verticalOffset = _verticalOffset;
			backingStruct.verticalAxisDirection = _verticalAxisDirection;
			backingStruct.horizontalOffset = _horizontalOffset;
			backingStruct.horizontalAxisDirection = _horizontalAxisDirection;
			backingStruct.mainAxis = _mainAxis;
			backingStruct.cacheExtent = _cacheExtent;
			backingStruct.clipBehavior = _clipBehavior;
			backingStruct.@delegate = _delegate;
		}

		protected override FlutterObjectStruct CreateBackingStruct() => new TwoDimensionalViewportStruct();
	}
}