// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Widgets;

namespace Flutter.Structs
{
/// Animated version of [Container] that gradually changes its values over a period of time.
/// 
/// The [AnimatedContainer] will automatically animate between the old and
/// new values of properties when they change using the provided curve and
/// duration. Properties that are null are not animated. Its child and
/// descendants are not animated.
/// 
/// This class is useful for generating simple implicit transitions between
/// different parameters to [Container] with its internal [AnimationController].
/// For more complex animations, you'll likely want to use a subclass of
/// [AnimatedWidget] such as the [DecoratedBoxTransition] or use your own
/// [AnimationController].
/// 
/// {@youtube 560 315 https://www.youtube.com/watch?v=yI-8QHpGIP4}
/// 
/// {@tool dartpad}
/// The following example (depicted above) transitions an AnimatedContainer
/// between two states. It adjusts the `height`, `width`, `color`, and
/// [alignment] properties when tapped.
/// 
/// ** See code in examples/api/lib/widgets/implicit_animations/animated_container.0.dart **
/// {@end-tool}
/// 
/// See also:
/// 
/// * [AnimatedPadding], which is a subset of this widget that only
/// supports animating the [padding].
/// * The [catalog of layout widgets](https://flutter.dev/widgets/layout/).
/// * [AnimatedPositioned], which, as a child of a [Stack], automatically
/// transitions its child's position over a given duration whenever the given
/// position changes.
/// * [AnimatedAlign], which automatically transitions its child's
/// position over a given duration whenever the given [AnimatedAlign.alignment] changes.
/// * [AnimatedSwitcher], which switches out a child for a new one with a customizable transition.
/// * [AnimatedCrossFade], which fades between two children and interpolates their sizes.
	[StructLayout(LayoutKind.Sequential)]
	internal class AnimatedContainerStruct : SingleChildRenderObjectWidgetStruct
	{
		// Simple field: alignment
/// Align the [child] within the container.
/// 
/// If non-null, the container will expand to fill its parent and position its
/// child within itself according to the given value. If the incoming
/// constraints are unbounded, then the child will be shrink-wrapped instead.
/// 
/// Ignored if [child] is null.
/// 
/// See also:
/// 
/// * [Alignment], a class with convenient constants typically used to
/// specify an [AlignmentGeometry].
/// * [AlignmentDirectional], like [Alignment] for specifying alignments
/// relative to text direction.
		public IntPtr alignment { get; set; }

		// Simple field: padding
/// Empty space to inscribe inside the [decoration]. The [child], if any, is
/// placed inside this padding.
		public IntPtr padding { get; set; }

		// Simple field: decoration
/// The decoration to paint behind the [child].
/// 
/// A shorthand for specifying just a solid color is available in the
/// constructor: set the `color` argument instead of the `decoration`
/// argument.
		public IntPtr decoration { get; set; }

		// Simple field: foregroundDecoration
/// The decoration to paint in front of the child.
		public IntPtr foregroundDecoration { get; set; }

		// Simple field: constraints
/// Additional constraints to apply to the child.
/// 
/// The constructor `width` and `height` arguments are combined with the
/// `constraints` argument to set this property.
/// 
/// The [padding] goes inside the constraints.
		public IntPtr constraints { get; set; }

		// Simple field: margin
/// Empty space to surround the [decoration] and [child].
		public IntPtr margin { get; set; }

		// Simple field: transform
/// The transformation matrix to apply before painting the container.
		public IntPtr transform { get; set; }

		// Simple field: transformAlignment
/// The alignment of the origin, relative to the size of the container, if [transform] is specified.
/// 
/// When [transform] is null, the value of this property is ignored.
/// 
/// See also:
/// 
/// * [Transform.alignment], which is set by this property.
		public IntPtr transformAlignment { get; set; }

		// Simple field: clipBehavior
/// The clip behavior when [AnimatedContainer.decoration] is not null.
/// 
/// Defaults to [Clip.none]. Must be [Clip.none] if [decoration] is null.
/// 
/// Unlike other properties of [AnimatedContainer], changes to this property
/// apply immediately and have no animation.
/// 
/// If a clip is to be applied, the [Decoration.getClipPath] method
/// for the provided decoration must return a clip path. (This is not
/// supported by all decorations; the default implementation of that
/// method throws an [UnsupportedError].)
		public Clip clipBehavior { get; set; }

		// Simple field: color
		public IntPtr color { get; set; }

		// Has flag for nullable property: width
		public byte Haswidth { get; set; }

		// Nullable value type: width
		public NativeNullable<double> width { get; set; }

		// Has flag for nullable property: height
		public byte Hasheight { get; set; }

		// Nullable value type: height
		public NativeNullable<double> height { get; set; }

		// Simple field: curve
		public IntPtr curve { get; set; }

		// Simple field: duration
		public IntPtr duration { get; set; }

		// Callback field: onEnd
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _onEnd;

		/// <summary>
		/// Action identifier for onEnd callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? onEndAction
		{
			get => GetString(_onEnd);
			set => SetString(ref _onEnd, value);
		}

	}
}
