// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using Flutter;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;

namespace Flutter.Structs
{
/// Animated version of [Transform.rotate] which automatically transitions the child's
/// rotation over a given duration whenever the given rotation changes.
/// 
/// {@tool snippet}
/// 
/// This code defines a widget that uses [AnimatedRotation] to rotate a [FlutterLogo]
/// gradually by an eighth of a turn (45 degrees) with each press of the button.
/// 
/// ```dart
/// class LogoRotate extends StatefulWidget {
/// const LogoRotate({super.key});
/// 
/// @override
/// State<LogoRotate> createState() => LogoRotateState();
/// }
/// 
/// class LogoRotateState extends State<LogoRotate> {
/// double turns = 0.0;
/// 
/// void _changeRotation() {
/// setState(() => turns += 1.0 / 8.0);
/// }
/// 
/// @override
/// Widget build(BuildContext context) {
/// return Column(
/// mainAxisAlignment: MainAxisAlignment.center,
/// children: <Widget>[
/// ElevatedButton(
/// onPressed: _changeRotation,
/// child: const Text('Rotate Logo'),
/// ),
/// Padding(
/// padding: const EdgeInsets.all(50),
/// child: AnimatedRotation(
/// turns: turns,
/// duration: const Duration(seconds: 1),
/// child: const FlutterLogo(),
/// ),
/// ),
/// ],
/// );
/// }
/// }
/// ```
/// {@end-tool}
/// 
/// See also:
/// 
/// * [AnimatedScale], for animating the scale of a child.
/// * [RotationTransition], an explicitly animated version of this widget, where
/// an [Animation] is provided by the caller instead of being built in.
	[StructLayout(LayoutKind.Sequential)]
	internal class AnimatedRotationStruct : SingleChildRenderObjectWidgetStruct
	{
		IntPtr _child;
/// The widget below this widget in the tree.
/// 
/// {@macro flutter.widgets.ProxyWidget.child}
		public Widget? child
		{
			set => SetIntPtr(ref _child, value);
		}

/// The animation that controls the rotation of the child.
/// 
/// If the current value of the turns animation is v, the child will be
/// rotated v * 2 * pi radians before being painted.
		public double turns { get; set; }

/// The alignment of the origin of the coordinate system in which the rotation
/// takes place, relative to the size of the box.
/// 
/// For example, to set the origin of the rotation to bottom middle, you can use
/// an alignment of (0.0, 1.0).
		public IntPtr alignment { get; set; }

/// The filter quality with which to apply the transform as a bitmap operation.
/// 
/// {@macro flutter.widgets.Transform.optional.FilterQuality}
		public IntPtr filterQuality { get; set; }

		public IntPtr curve { get; set; }

		public IntPtr duration { get; set; }

		public IntPtr onEnd { get; set; }

	}
}