// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;
using Flutter.Services;
using Flutter.Navigation;

namespace Flutter.Structs
{
/// Defines default property values for descendant [AppBar] widgets.
/// 
/// Descendant widgets obtain the current [AppBarThemeData] object with
/// [AppBarTheme.of]. Instances of [AppBarThemeData] can be customized
/// with [AppBarThemeData.copyWith].
/// 
/// Typically an [AppBarThemeData] is specified as part of the overall [Theme] with
/// [ThemeData.appBarTheme].
/// 
/// All [AppBarTheme] properties are `null` by default. When null, the
/// 
/// See also:
/// 
/// * [ThemeData], which describes the overall theme information for the
/// application.
	[StructLayout(LayoutKind.Sequential)]
	internal class AppBarThemeStruct : SingleChildRenderObjectWidgetStruct
	{
		// Has flag for nullable property: backgroundColor
		public byte HasbackgroundColor { get; set; }

		// Nullable field: backgroundColor
		private IntPtr _backgroundColor;

		public IntPtr backgroundColor
		{
			get => _backgroundColor;
			set { _backgroundColor = value; HasbackgroundColor = 1; }
		}

		// Has flag for nullable property: foregroundColor
		public byte HasforegroundColor { get; set; }

		// Nullable field: foregroundColor
		private IntPtr _foregroundColor;

		public IntPtr foregroundColor
		{
			get => _foregroundColor;
			set { _foregroundColor = value; HasforegroundColor = 1; }
		}

		// Has flag for nullable property: elevation
		public byte Haselevation { get; set; }

		// Nullable field: elevation
		private double _elevation;

		public double elevation
		{
			get => _elevation;
			set { _elevation = value; Haselevation = 1; }
		}

		// Has flag for nullable property: scrolledUnderElevation
		public byte HasscrolledUnderElevation { get; set; }

		// Nullable field: scrolledUnderElevation
		private double _scrolledUnderElevation;

		public double scrolledUnderElevation
		{
			get => _scrolledUnderElevation;
			set { _scrolledUnderElevation = value; HasscrolledUnderElevation = 1; }
		}

		// Has flag for nullable property: shadowColor
		public byte HasshadowColor { get; set; }

		// Nullable field: shadowColor
		private IntPtr _shadowColor;

		public IntPtr shadowColor
		{
			get => _shadowColor;
			set { _shadowColor = value; HasshadowColor = 1; }
		}

		// Has flag for nullable property: surfaceTintColor
		public byte HassurfaceTintColor { get; set; }

		// Nullable field: surfaceTintColor
		private IntPtr _surfaceTintColor;

		public IntPtr surfaceTintColor
		{
			get => _surfaceTintColor;
			set { _surfaceTintColor = value; HassurfaceTintColor = 1; }
		}

		// Has flag for nullable property: shape
		public byte Hasshape { get; set; }

		// Nullable field: shape
		private IntPtr _shape;

		public IntPtr shape
		{
			get => _shape;
			set { _shape = value; Hasshape = 1; }
		}

		// Has flag for nullable property: iconTheme
		public byte HasiconTheme { get; set; }

		// Nullable field: iconTheme
		private IntPtr _iconTheme;

		public IntPtr iconTheme
		{
			get => _iconTheme;
			set { _iconTheme = value; HasiconTheme = 1; }
		}

		// Has flag for nullable property: actionsIconTheme
		public byte HasactionsIconTheme { get; set; }

		// Nullable field: actionsIconTheme
		private IntPtr _actionsIconTheme;

		public IntPtr actionsIconTheme
		{
			get => _actionsIconTheme;
			set { _actionsIconTheme = value; HasactionsIconTheme = 1; }
		}

		// Has flag for nullable property: centerTitle
		public byte HascenterTitle { get; set; }

		// Nullable field: centerTitle
		private bool _centerTitle;

		public bool centerTitle
		{
			get => _centerTitle;
			set { _centerTitle = value; HascenterTitle = 1; }
		}

		// Has flag for nullable property: titleSpacing
		public byte HastitleSpacing { get; set; }

		// Nullable field: titleSpacing
		private double _titleSpacing;

		public double titleSpacing
		{
			get => _titleSpacing;
			set { _titleSpacing = value; HastitleSpacing = 1; }
		}

		// Has flag for nullable property: leadingWidth
		public byte HasleadingWidth { get; set; }

		// Nullable field: leadingWidth
		private double _leadingWidth;

		public double leadingWidth
		{
			get => _leadingWidth;
			set { _leadingWidth = value; HasleadingWidth = 1; }
		}

		// Has flag for nullable property: toolbarHeight
		public byte HastoolbarHeight { get; set; }

		// Nullable field: toolbarHeight
		private double _toolbarHeight;

		public double toolbarHeight
		{
			get => _toolbarHeight;
			set { _toolbarHeight = value; HastoolbarHeight = 1; }
		}

		// Has flag for nullable property: toolbarTextStyle
		public byte HastoolbarTextStyle { get; set; }

		// Nullable field: toolbarTextStyle
		private IntPtr _toolbarTextStyle;

		public IntPtr toolbarTextStyle
		{
			get => _toolbarTextStyle;
			set { _toolbarTextStyle = value; HastoolbarTextStyle = 1; }
		}

		// Has flag for nullable property: titleTextStyle
		public byte HastitleTextStyle { get; set; }

		// Nullable field: titleTextStyle
		private IntPtr _titleTextStyle;

		public IntPtr titleTextStyle
		{
			get => _titleTextStyle;
			set { _titleTextStyle = value; HastitleTextStyle = 1; }
		}

		// Has flag for nullable property: systemOverlayStyle
		public byte HassystemOverlayStyle { get; set; }

		// Nullable field: systemOverlayStyle
		private IntPtr _systemOverlayStyle;

		public IntPtr systemOverlayStyle
		{
			get => _systemOverlayStyle;
			set { _systemOverlayStyle = value; HassystemOverlayStyle = 1; }
		}

		// Has flag for nullable property: actionsPadding
		public byte HasactionsPadding { get; set; }

		// Nullable field: actionsPadding
		private IntPtr _actionsPadding;

		public IntPtr actionsPadding
		{
			get => _actionsPadding;
			set { _actionsPadding = value; HasactionsPadding = 1; }
		}

		// Simple field: data
		public IntPtr data { get; set; }

		// Has flag for nullable property: color
		public byte Hascolor { get; set; }

		// Nullable field: color
		private IntPtr _color;

		public IntPtr color
		{
			get => _color;
			set { _color = value; Hascolor = 1; }
		}

	}
}
