// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;
using Flutter.Services;
using Flutter.Navigation;

namespace Flutter.Structs
{
/// An inherited widget that overrides the default color style, and size
/// parameters for [Badge]s in this widget's subtree.
/// 
/// Values specified here override the defaults for [Badge] properties which
/// are not given an explicit non-null value.
	[StructLayout(LayoutKind.Sequential)]
	internal class BadgeThemeStruct : SingleChildRenderObjectWidgetStruct
	{
		// Simple field: data
/// Specifies the default color and size overrides for descendant [Badge] widgets.
		public IntPtr data { get; set; }

	}
}
