// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;
using Flutter.Services;
using Flutter.Navigation;

namespace Flutter.Structs
{
/// Displays a grid of days for a given month and allows the user to select a
/// date.
/// 
/// Days are arranged in a rectangular grid with one column for each day of the
/// week. Controls are provided to change the year and month that the grid is
/// showing.
/// 
/// The calendar picker widget is rarely used directly. Instead, consider using
/// [showDatePicker], which will create a dialog that uses this as well as
/// provides a text entry option.
/// 
/// See also:
/// 
/// * [showDatePicker], which creates a Dialog that contains a
/// [CalendarDatePicker] and provides an optional compact view where the
/// user can enter a date as a line of text.
/// * [showTimePicker], which shows a dialog that contains a Material Design
/// time picker.
	[StructLayout(LayoutKind.Sequential)]
	internal class CalendarDatePickerStruct : WidgetStruct
	{
		// Has flag for nullable property: initialDate
		public byte HasinitialDate { get; set; }

		// Nullable field: initialDate
		private IntPtr _initialDate;

/// The initially selected [DateTime] that the picker should display.
/// 
/// Subsequently changing this has no effect. To change the selected date,
/// change the [key] to create a new instance of the [CalendarDatePicker], and
/// provide that widget the new [initialDate]. This will reset the widget's
/// interactive state.
		public IntPtr initialDate
		{
			get => _initialDate;
			set { _initialDate = value; HasinitialDate = 1; }
		}

		// Simple field: firstDate
/// The earliest allowable [DateTime] that the user can select.
		public IntPtr firstDate { get; set; }

		// Simple field: lastDate
/// The latest allowable [DateTime] that the user can select.
		public IntPtr lastDate { get; set; }

		// Simple field: currentDate
/// The [DateTime] representing today. It will be highlighted in the day grid.
		public IntPtr currentDate { get; set; }

		// Callback field: onDateChanged
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _onDateChanged;

/// Called when the user selects a date in the picker.
		/// <summary>
		/// Action identifier for onDateChanged callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? onDateChangedAction
		{
			get => GetString(_onDateChanged);
			set { SetString(ref _onDateChanged, value); }
		}

		// Has flag for nullable property: onDisplayedMonthChanged
		public byte HasonDisplayedMonthChanged { get; set; }

		// Callback field: onDisplayedMonthChanged
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _onDisplayedMonthChanged;

/// Called when the user navigates to a new month/year in the picker.
		/// <summary>
		/// Action identifier for onDisplayedMonthChanged callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? onDisplayedMonthChangedAction
		{
			get => GetString(_onDisplayedMonthChanged);
			set { SetString(ref _onDisplayedMonthChanged, value); HasonDisplayedMonthChanged = (byte)(value != null ? 1 : 0); }
		}

		// Simple field: initialCalendarMode
/// The initial display of the calendar picker.
/// 
/// Subsequently changing this has no effect. To change the calendar mode,
/// change the [key] to create a new instance of the [CalendarDatePicker], and
/// provide that widget a new [initialCalendarMode]. This will reset the
/// widget's interactive state.
		public IntPtr initialCalendarMode { get; set; }

		// Has flag for nullable property: selectableDayPredicate
		public byte HasselectableDayPredicate { get; set; }

		// Callback field: selectableDayPredicate
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _selectableDayPredicate;

/// Function to provide full control over which dates in the calendar can be selected.
		/// <summary>
		/// Action identifier for selectableDayPredicate callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? selectableDayPredicateAction
		{
			get => GetString(_selectableDayPredicate);
			set { SetString(ref _selectableDayPredicate, value); HasselectableDayPredicate = (byte)(value != null ? 1 : 0); }
		}

		// Simple field: calendarDelegate
/// {@macro flutter.material.calendar_date_picker.calendarDelegate}
		public IntPtr calendarDelegate { get; set; }

	}
}
