// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;
using Flutter.Services;
using Flutter.Navigation;

namespace Flutter.Structs
{
/// An iOS-style linear activity indicator.
/// 
/// The [CupertinoLinearActivityIndicator] is a linear progress bar that
/// displays a colored bar to indicate the progress of an ongoing task.
/// 
/// {@tool dartpad}
/// This example shows how [CupertinoLinearActivityIndicator] can be customized.
/// 
/// ** See code in examples/api/lib/cupertino/activity_indicator/cupertino_linear_activity_indicator.0.dart **
/// {@end-tool}
/// 
/// See also:
/// 
/// * [CupertinoActivityIndicator], which is an iOS-style activity indicator that spins clockwise.
/// * <https://developer.apple.com/design/human-interface-guidelines/progress-indicators/>
	[StructLayout(LayoutKind.Sequential)]
	internal class CupertinoLinearActivityIndicatorStruct : WidgetStruct
	{
		// Simple field: progress
/// The current progress of the linear activity indicator.
/// 
/// This value must be between 0.0 and 1.0. A value of 0.0 means no progress
/// and 1.0 means that progress is complete.
		public double progress { get; set; }

		// Simple field: height
/// The height of the line used to draw the linear activity indicator.
/// 
/// Defaults to 4.5 units. Must be positive.
		public double height { get; set; }

		// Has flag for nullable property: color
		public byte Hascolor { get; set; }

		// Nullable field: color
		private IntPtr _color;

/// The color of the progress bar.
/// 
/// This color represents the portion of the bar that indicates progress.
/// 
/// Defaults to [CupertinoColors.activeBlue] if no color is specified.
		public IntPtr color
		{
			get => _color;
			set { _color = value; Hascolor = 1; }
		}

	}
}
