// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;
using Flutter.Services;
using Flutter.Navigation;

namespace Flutter.Structs
{
/// Creates a [CupertinoFormRow] containing a [FormField] that wraps
/// a [CupertinoTextField].
/// 
/// A [Form] ancestor is not required. The [Form] allows one to
/// save, reset, or validate multiple fields at once. To use without a [Form],
/// pass a [GlobalKey] to the constructor and use [GlobalKey.currentState] to
/// save or reset the form field.
/// 
/// When a [controller] is specified, its [TextEditingController.text]
/// defines the [initialValue]. If this [FormField] is part of a scrolling
/// container that lazily constructs its children, like a [ListView] or a
/// [CustomScrollView], then a [controller] should be specified.
/// The controller's lifetime should be managed by a stateful widget ancestor
/// of the scrolling container.
/// 
/// The [prefix] parameter is displayed at the start of the row. Standard iOS
/// guidelines encourage passing a [Text] widget to [prefix] to detail the
/// nature of the input.
/// 
/// The [padding] parameter is used to pad the contents of the row. It is
/// directly passed to [CupertinoFormRow]. If the [padding]
/// parameter is null, [CupertinoFormRow] constructs its own default
/// padding (which is the standard form row padding in iOS.) If no edge
/// insets are intended, explicitly pass [EdgeInsets.zero] to [padding].
/// 
/// If a [controller] is not specified, [initialValue] can be used to give
/// the automatically generated controller an initial value.
/// 
/// Consider calling [TextEditingController.dispose] of the [controller], if one
/// is specified, when it is no longer needed. This will ensure we discard any
/// resources used by the object.
/// 
/// For documentation about the various parameters, see the
/// [CupertinoTextField] class and [CupertinoTextField.borderless],
/// the constructor.
/// 
/// {@tool snippet}
/// 
/// Creates a [CupertinoTextFormFieldRow] with a leading text and validator
/// function.
/// 
/// If the user enters valid text, the CupertinoTextField appears normally
/// without any warnings to the user.
/// 
/// If the user enters invalid text, the error message returned from the
/// validator function is displayed in dark red underneath the input.
/// 
/// ```dart
/// CupertinoTextFormFieldRow(
/// prefix: const Text('Username'),
/// onSaved: (String? value) {
/// This optional block of code can be used to run
/// code when the user saves the form.
/// },
/// validator: (String? value) {
/// return (value != null && value.contains('@')) ? 'Do not use the @ char.' : null;
/// },
/// )
/// ```
/// {@end-tool}
/// 
/// {@tool dartpad}
/// This example shows how to move the focus to the next field when the user
/// presses the SPACE key.
/// 
/// ** See code in examples/api/lib/cupertino/text_form_field_row/cupertino_text_form_field_row.1.dart **
/// {@end-tool}
	[StructLayout(LayoutKind.Sequential)]
	internal class CupertinoTextFormFieldRowStruct : WidgetStruct
	{
		// Has flag for nullable property: prefix
		public byte Hasprefix { get; set; }

		// Widget field: prefix
		private IntPtr _prefix;

/// A widget that is displayed at the start of the row.
/// 
/// The [prefix] widget is displayed at the start of the row. Standard iOS
/// guidelines encourage passing a [Text] widget to [prefix] to detail the
/// nature of the input.
		public IntPtr? prefix
		{
			get => _prefix != IntPtr.Zero ? (IntPtr)_prefix : null;
			set { SetIntPtr(ref _prefix, value); Hasprefix = (byte)(value != null ? 1 : 0); }
		}

		// Has flag for nullable property: padding
		public byte Haspadding { get; set; }

		// Nullable field: padding
		private IntPtr _padding;

/// Content padding for the row.
/// 
/// The [padding] widget is passed to [CupertinoFormRow]. If the [padding]
/// parameter is null, [CupertinoFormRow] constructs its own default
/// padding, which is the standard form row padding in iOS.
/// 
/// If no edge insets are intended, explicitly pass [EdgeInsets.zero] to
/// [padding].
		public IntPtr padding
		{
			get => _padding;
			set { _padding = value; Haspadding = 1; }
		}

		// Has flag for nullable property: controller
		public byte Hascontroller { get; set; }

		// Nullable field: controller
		private IntPtr _controller;

/// Controls the text being edited.
/// 
/// If null, this widget will create its own [TextEditingController] and
/// initialize its [TextEditingController.text] with [initialValue].
		public IntPtr controller
		{
			get => _controller;
			set { _controller = value; Hascontroller = 1; }
		}

		// Has flag for nullable property: onChanged
		public byte HasonChanged { get; set; }

		// Callback field: onChanged
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _onChanged;

/// {@macro flutter.material.TextFormField.onChanged}
		/// <summary>
		/// Action identifier for onChanged callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? onChangedAction
		{
			get => GetString(_onChanged);
			set { SetString(ref _onChanged, value); HasonChanged = (byte)(value != null ? 1 : 0); }
		}

		// Has flag for nullable property: initialValue
		public byte HasinitialValue { get; set; }

		// String field: initialValue
		private IntPtr _initialValue;

		public string? initialValue
		{
			get => GetString(_initialValue);
			set { SetString(ref _initialValue, value); HasinitialValue = (byte)(value != null ? 1 : 0); }
		}

		// Has flag for nullable property: focusNode
		public byte HasfocusNode { get; set; }

		// Nullable field: focusNode
		private IntPtr _focusNode;

		public IntPtr focusNode
		{
			get => _focusNode;
			set { _focusNode = value; HasfocusNode = 1; }
		}

		// Has flag for nullable property: decoration
		public byte Hasdecoration { get; set; }

		// Nullable field: decoration
		private IntPtr _decoration;

		public IntPtr decoration
		{
			get => _decoration;
			set { _decoration = value; Hasdecoration = 1; }
		}

		// Has flag for nullable property: keyboardType
		public byte HaskeyboardType { get; set; }

		// Nullable field: keyboardType
		private IntPtr _keyboardType;

		public IntPtr keyboardType
		{
			get => _keyboardType;
			set { _keyboardType = value; HaskeyboardType = 1; }
		}

		// Simple field: textCapitalization
		public TextCapitalization textCapitalization { get; set; }

		// Has flag for nullable property: textInputAction
		public byte HastextInputAction { get; set; }

		// Nullable field: textInputAction
		private TextInputAction _textInputAction;

		public TextInputAction textInputAction
		{
			get => _textInputAction;
			set { _textInputAction = value; HastextInputAction = 1; }
		}

		// Has flag for nullable property: style
		public byte Hasstyle { get; set; }

		// Nullable field: style
		private IntPtr _style;

		public IntPtr style
		{
			get => _style;
			set { _style = value; Hasstyle = 1; }
		}

		// Has flag for nullable property: strutStyle
		public byte HasstrutStyle { get; set; }

		// Nullable field: strutStyle
		private IntPtr _strutStyle;

		public IntPtr strutStyle
		{
			get => _strutStyle;
			set { _strutStyle = value; HasstrutStyle = 1; }
		}

		// Has flag for nullable property: textDirection
		public byte HastextDirection { get; set; }

		// Nullable field: textDirection
		private TextDirection _textDirection;

		public TextDirection textDirection
		{
			get => _textDirection;
			set { _textDirection = value; HastextDirection = 1; }
		}

		// Simple field: textAlign
		public TextAlign textAlign { get; set; }

		// Has flag for nullable property: textAlignVertical
		public byte HastextAlignVertical { get; set; }

		// Nullable field: textAlignVertical
		private IntPtr _textAlignVertical;

		public IntPtr textAlignVertical
		{
			get => _textAlignVertical;
			set { _textAlignVertical = value; HastextAlignVertical = 1; }
		}

		// Simple field: autofocus
		public bool autofocus { get; set; }

		// Simple field: @readOnly
		public bool @readOnly { get; set; }

		// Has flag for nullable property: toolbarOptions
		public byte HastoolbarOptions { get; set; }

		// Nullable field: toolbarOptions
		private IntPtr _toolbarOptions;

		public IntPtr toolbarOptions
		{
			get => _toolbarOptions;
			set { _toolbarOptions = value; HastoolbarOptions = 1; }
		}

		// Has flag for nullable property: showCursor
		public byte HasshowCursor { get; set; }

		// Nullable field: showCursor
		private bool _showCursor;

		public bool showCursor
		{
			get => _showCursor;
			set { _showCursor = value; HasshowCursor = 1; }
		}

		// String field: obscuringCharacter
		private IntPtr _obscuringCharacter;

		public string obscuringCharacter
		{
			get => GetString(_obscuringCharacter);
			set => SetString(ref _obscuringCharacter, value);
		}

		// Simple field: obscureText
		public bool obscureText { get; set; }

		// Simple field: autocorrect
		public bool autocorrect { get; set; }

		// Has flag for nullable property: smartDashesType
		public byte HassmartDashesType { get; set; }

		// Nullable field: smartDashesType
		private IntPtr _smartDashesType;

		public IntPtr smartDashesType
		{
			get => _smartDashesType;
			set { _smartDashesType = value; HassmartDashesType = 1; }
		}

		// Has flag for nullable property: smartQuotesType
		public byte HassmartQuotesType { get; set; }

		// Nullable field: smartQuotesType
		private IntPtr _smartQuotesType;

		public IntPtr smartQuotesType
		{
			get => _smartQuotesType;
			set { _smartQuotesType = value; HassmartQuotesType = 1; }
		}

		// Simple field: enableSuggestions
		public bool enableSuggestions { get; set; }

		// Has flag for nullable property: maxLines
		public byte HasmaxLines { get; set; }

		// Nullable field: maxLines
		private int _maxLines;

		public int maxLines
		{
			get => _maxLines;
			set { _maxLines = value; HasmaxLines = 1; }
		}

		// Has flag for nullable property: minLines
		public byte HasminLines { get; set; }

		// Nullable field: minLines
		private int _minLines;

		public int minLines
		{
			get => _minLines;
			set { _minLines = value; HasminLines = 1; }
		}

		// Simple field: expands
		public bool expands { get; set; }

		// Has flag for nullable property: maxLength
		public byte HasmaxLength { get; set; }

		// Nullable field: maxLength
		private int _maxLength;

		public int maxLength
		{
			get => _maxLength;
			set { _maxLength = value; HasmaxLength = 1; }
		}

		// Has flag for nullable property: onTap
		public byte HasonTap { get; set; }

		// Callback field: onTap
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _onTap;

		/// <summary>
		/// Action identifier for onTap callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? onTapAction
		{
			get => GetString(_onTap);
			set { SetString(ref _onTap, value); HasonTap = (byte)(value != null ? 1 : 0); }
		}

		// Has flag for nullable property: onEditingComplete
		public byte HasonEditingComplete { get; set; }

		// Callback field: onEditingComplete
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _onEditingComplete;

		/// <summary>
		/// Action identifier for onEditingComplete callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? onEditingCompleteAction
		{
			get => GetString(_onEditingComplete);
			set { SetString(ref _onEditingComplete, value); HasonEditingComplete = (byte)(value != null ? 1 : 0); }
		}

		// Has flag for nullable property: onFieldSubmitted
		public byte HasonFieldSubmitted { get; set; }

		// Callback field: onFieldSubmitted
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _onFieldSubmitted;

		/// <summary>
		/// Action identifier for onFieldSubmitted callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? onFieldSubmittedAction
		{
			get => GetString(_onFieldSubmitted);
			set { SetString(ref _onFieldSubmitted, value); HasonFieldSubmitted = (byte)(value != null ? 1 : 0); }
		}

		// Has flag for nullable property: onSaved
		public byte HasonSaved { get; set; }

		// Callback field: onSaved
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _onSaved;

		/// <summary>
		/// Action identifier for onSaved callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? onSavedAction
		{
			get => GetString(_onSaved);
			set { SetString(ref _onSaved, value); HasonSaved = (byte)(value != null ? 1 : 0); }
		}

		// Has flag for nullable property: validator
		public byte Hasvalidator { get; set; }

		// Callback field: validator
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _validator;

		/// <summary>
		/// Action identifier for validator callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? validatorAction
		{
			get => GetString(_validator);
			set { SetString(ref _validator, value); Hasvalidator = (byte)(value != null ? 1 : 0); }
		}

		// Has flag for nullable property: inputFormatters
		public byte HasinputFormatters { get; set; }

		// Nullable field: inputFormatters
		private IntPtr _inputFormatters;

		public IntPtr inputFormatters
		{
			get => _inputFormatters;
			set { _inputFormatters = value; HasinputFormatters = 1; }
		}

		// Has flag for nullable property: enabled
		public byte Hasenabled { get; set; }

		// Nullable field: enabled
		private bool _enabled;

		public bool enabled
		{
			get => _enabled;
			set { _enabled = value; Hasenabled = 1; }
		}

		// Simple field: cursorWidth
		public double cursorWidth { get; set; }

		// Has flag for nullable property: cursorHeight
		public byte HascursorHeight { get; set; }

		// Nullable field: cursorHeight
		private double _cursorHeight;

		public double cursorHeight
		{
			get => _cursorHeight;
			set { _cursorHeight = value; HascursorHeight = 1; }
		}

		// Has flag for nullable property: cursorColor
		public byte HascursorColor { get; set; }

		// Nullable field: cursorColor
		private IntPtr _cursorColor;

		public IntPtr cursorColor
		{
			get => _cursorColor;
			set { _cursorColor = value; HascursorColor = 1; }
		}

		// Has flag for nullable property: keyboardAppearance
		public byte HaskeyboardAppearance { get; set; }

		// Nullable field: keyboardAppearance
		private Brightness _keyboardAppearance;

		public Brightness keyboardAppearance
		{
			get => _keyboardAppearance;
			set { _keyboardAppearance = value; HaskeyboardAppearance = 1; }
		}

		// Simple field: scrollPadding
		public IntPtr scrollPadding { get; set; }

		// Simple field: enableInteractiveSelection
		public bool enableInteractiveSelection { get; set; }

		// Has flag for nullable property: selectionControls
		public byte HasselectionControls { get; set; }

		// Nullable field: selectionControls
		private IntPtr _selectionControls;

		public IntPtr selectionControls
		{
			get => _selectionControls;
			set { _selectionControls = value; HasselectionControls = 1; }
		}

		// Has flag for nullable property: scrollPhysics
		public byte HasscrollPhysics { get; set; }

		// Nullable field: scrollPhysics
		private IntPtr _scrollPhysics;

		public IntPtr scrollPhysics
		{
			get => _scrollPhysics;
			set { _scrollPhysics = value; HasscrollPhysics = 1; }
		}

		// Has flag for nullable property: autofillHints
		public byte HasautofillHints { get; set; }

		// Nullable field: autofillHints
		private IntPtr _autofillHints;

		public IntPtr autofillHints
		{
			get => _autofillHints;
			set { _autofillHints = value; HasautofillHints = 1; }
		}

		// Simple field: autovalidateMode
		public AutovalidateMode autovalidateMode { get; set; }

		// Has flag for nullable property: placeholder
		public byte Hasplaceholder { get; set; }

		// String field: placeholder
		private IntPtr _placeholder;

		public string? placeholder
		{
			get => GetString(_placeholder);
			set { SetString(ref _placeholder, value); Hasplaceholder = (byte)(value != null ? 1 : 0); }
		}

		// Has flag for nullable property: placeholderStyle
		public byte HasplaceholderStyle { get; set; }

		// Nullable field: placeholderStyle
		private IntPtr _placeholderStyle;

		public IntPtr placeholderStyle
		{
			get => _placeholderStyle;
			set { _placeholderStyle = value; HasplaceholderStyle = 1; }
		}

		// Has flag for nullable property: contextMenuBuilder
		public byte HascontextMenuBuilder { get; set; }

		// Callback field: contextMenuBuilder
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _contextMenuBuilder;

		/// <summary>
		/// Action identifier for contextMenuBuilder callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? contextMenuBuilderAction
		{
			get => GetString(_contextMenuBuilder);
			set { SetString(ref _contextMenuBuilder, value); HascontextMenuBuilder = (byte)(value != null ? 1 : 0); }
		}

		// Has flag for nullable property: spellCheckConfiguration
		public byte HasspellCheckConfiguration { get; set; }

		// Nullable field: spellCheckConfiguration
		private IntPtr _spellCheckConfiguration;

		public IntPtr spellCheckConfiguration
		{
			get => _spellCheckConfiguration;
			set { _spellCheckConfiguration = value; HasspellCheckConfiguration = 1; }
		}

		// Has flag for nullable property: selectionHeightStyle
		public byte HasselectionHeightStyle { get; set; }

		// Nullable field: selectionHeightStyle
		private BoxHeightStyle _selectionHeightStyle;

		public BoxHeightStyle selectionHeightStyle
		{
			get => _selectionHeightStyle;
			set { _selectionHeightStyle = value; HasselectionHeightStyle = 1; }
		}

		// Has flag for nullable property: selectionWidthStyle
		public byte HasselectionWidthStyle { get; set; }

		// Nullable field: selectionWidthStyle
		private BoxWidthStyle _selectionWidthStyle;

		public BoxWidthStyle selectionWidthStyle
		{
			get => _selectionWidthStyle;
			set { _selectionWidthStyle = value; HasselectionWidthStyle = 1; }
		}

		// Has flag for nullable property: restorationId
		public byte HasrestorationId { get; set; }

		// String field: restorationId
		private IntPtr _restorationId;

		public string? restorationId
		{
			get => GetString(_restorationId);
			set { SetString(ref _restorationId, value); HasrestorationId = (byte)(value != null ? 1 : 0); }
		}

	}
}
