// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;
using Flutter.Services;
using Flutter.Navigation;

namespace Flutter.Structs
{
/// A Material Design dialog.
/// 
/// This dialog widget does not have any opinion about the contents of the
/// dialog. Rather than using this widget directly, consider using [AlertDialog]
/// or [SimpleDialog], which implement specific kinds of Material Design
/// dialogs.
/// 
/// {@tool dartpad}
/// This sample shows the creation of [Dialog] and [Dialog.fullscreen] widgets.
/// 
/// ** See code in examples/api/lib/material/dialog/dialog.0.dart **
/// {@end-tool}
/// 
/// ## Contraints
/// The Material 3 guideline recommends that a dialog should have a maximal width of 560dp.
/// For historical reasons, Flutter's [Dialog] widget does not come with this constraint by default.
/// For applications targeting large screens such as desktop or Web, it is recommended to
/// set the [constraints] property.
/// 
/// {@tool snippet}
/// This sample shows a [Dialog] using [BoxConstraints] defined by the Material 3 specification.
/// 
/// ```dart
/// const Dialog(constraints: BoxConstraints(maxWidth: 560, minHeight: 280));
/// ```
/// {@end-tool}
/// 
/// See also:
/// 
/// * [AlertDialog], for dialogs that have a message and some buttons.
/// * [SimpleDialog], for dialogs that offer a variety of options.
/// * [showDialog], which actually displays the dialog and returns its result.
/// * <https://material.io/design/components/dialogs.html>
	[StructLayout(LayoutKind.Sequential)]
	internal class DialogStruct : SingleChildRenderObjectWidgetStruct
	{
		// Has flag for nullable property: backgroundColor
		public byte HasbackgroundColor { get; set; }

		// Nullable field: backgroundColor
		private IntPtr _backgroundColor;

/// {@template flutter.material.dialog.backgroundColor}
/// The background color of the surface of this [Dialog].
/// 
/// This sets the [Material.color] on this [Dialog]'s [Material].
/// 
/// If null, then the [DialogThemeData.backgroundColor] is used. If that is
/// also null, defaults to [ColorScheme.surfaceContainerHigh]. If
/// [ThemeData.useMaterial3] is false, defaults to [Colors.grey] with a shade
/// of 800 in dark theme and [Colors.white] in light theme.
/// 
/// If [Dialog.fullscreen] is used, defaults to [ColorScheme.surface].
/// {@endtemplate}
		public IntPtr backgroundColor
		{
			get => _backgroundColor;
			set { _backgroundColor = value; HasbackgroundColor = 1; }
		}

		// Has flag for nullable property: elevation
		public byte Haselevation { get; set; }

		// Nullable field: elevation
		private double _elevation;

/// {@template flutter.material.dialog.elevation}
/// The z-coordinate of this [Dialog].
/// 
/// Controls how far above the parent the dialog will appear. Elevation is
/// represented by a drop shadow if [shadowColor] is non null,
/// and a surface tint overlay on the background color if [surfaceTintColor] is
/// non null.
/// 
/// If null then [DialogThemeData.elevation] is used, and if that is null then
/// the elevation will match the Material Design specification for Dialogs.
/// 
/// See also:
/// * [Material.elevation], which describes how [elevation] effects the
/// drop shadow or surface tint overlay.
/// * [shadowColor], color of the drop shadow used to indicate the elevation.
/// * [surfaceTintColor], color of an overlay on top of the background
/// color used to indicate the elevation.
/// * <https://m3.material.io/components/dialogs/overview>, the Material
/// Design specification for dialogs.
/// {@endtemplate}
		public double elevation
		{
			get => _elevation;
			set { _elevation = value; Haselevation = 1; }
		}

		// Has flag for nullable property: shadowColor
		public byte HasshadowColor { get; set; }

		// Nullable field: shadowColor
		private IntPtr _shadowColor;

/// {@template flutter.material.dialog.shadowColor}
/// The color used to paint a drop shadow under the dialog's [Material],
/// which reflects the dialog's [elevation].
/// 
/// If null and [ThemeData.useMaterial3] is true then no drop shadow will
/// be rendered.
/// 
/// If null and [ThemeData.useMaterial3] is false then it will default to
/// [ThemeData.shadowColor].
/// 
/// See also:
/// * [Material.shadowColor], which describes how the drop shadow is painted.
/// * [elevation], which affects how the drop shadow is painted.
/// * [surfaceTintColor], which can be used to indicate elevation through
/// tinting the background color.
/// {@endtemplate}
		public IntPtr shadowColor
		{
			get => _shadowColor;
			set { _shadowColor = value; HasshadowColor = 1; }
		}

		// Has flag for nullable property: surfaceTintColor
		public byte HassurfaceTintColor { get; set; }

		// Nullable field: surfaceTintColor
		private IntPtr _surfaceTintColor;

/// {@template flutter.material.dialog.surfaceTintColor}
/// The color used as a surface tint overlay on the dialog's background color,
/// which reflects the dialog's [elevation].
/// 
/// If [ThemeData.useMaterial3] is false property has no effect.
/// 
/// This is not recommended for use. [Material 3 spec](https://m3.material.io/styles/color/the-color-system/color-roles)
/// introduced a set of tone-based surfaces and surface containers in its [ColorScheme],
/// which provide more flexibility. The intention is to eventually remove surface tint color from
/// the framework.
/// 
/// defaults to [Colors.transparent].
/// 
/// To disable this feature, set [surfaceTintColor] to [Colors.transparent].
/// 
/// See also:
/// * [Material.surfaceTintColor], which describes how the surface tint will
/// be applied to the background color of the dialog.
/// * [elevation], which affects the opacity of the surface tint.
/// * [shadowColor], which can be used to indicate elevation through
/// a drop shadow.
/// {@endtemplate}
		public IntPtr surfaceTintColor
		{
			get => _surfaceTintColor;
			set { _surfaceTintColor = value; HassurfaceTintColor = 1; }
		}

		// Simple field: insetAnimationDuration
/// {@template flutter.material.dialog.insetAnimationDuration}
/// The duration of the animation to show when the system keyboard intrudes
/// into the space that the dialog is placed in.
/// 
/// Defaults to 100 milliseconds when [Dialog] is used, and [Duration.zero]
/// when [Dialog.fullscreen] is used.
/// {@endtemplate}
		public IntPtr insetAnimationDuration { get; set; }

		// Simple field: insetAnimationCurve
/// {@template flutter.material.dialog.insetAnimationCurve}
/// The curve to use for the animation shown when the system keyboard intrudes
/// into the space that the dialog is placed in.
/// 
/// Defaults to [Curves.decelerate].
/// {@endtemplate}
		public IntPtr insetAnimationCurve { get; set; }

		// Has flag for nullable property: insetPadding
		public byte HasinsetPadding { get; set; }

		// Nullable field: insetPadding
		private IntPtr _insetPadding;

/// {@template flutter.material.dialog.insetPadding}
/// The amount of padding added to [MediaQueryData.viewInsets] on the outside
/// of the dialog. This defines the minimum space between the screen's edges
/// and the dialog.
/// 
/// Defaults to `EdgeInsets.symmetric(horizontal: 40.0, vertical: 24.0)`.
/// {@endtemplate}
		public IntPtr insetPadding
		{
			get => _insetPadding;
			set { _insetPadding = value; HasinsetPadding = 1; }
		}

		// Has flag for nullable property: clipBehavior
		public byte HasclipBehavior { get; set; }

		// Nullable field: clipBehavior
		private Clip _clipBehavior;

/// {@template flutter.material.dialog.clipBehavior}
/// Controls how the contents of the dialog are clipped (or not) to the given
/// [shape].
/// 
/// See the enum [Clip] for details of all possible options and their common
/// use cases.
/// 
/// If null, then [DialogThemeData.clipBehavior] is used. If that is also null,
/// defaults to [Clip.none].
/// {@endtemplate}
		public Clip clipBehavior
		{
			get => _clipBehavior;
			set { _clipBehavior = value; HasclipBehavior = 1; }
		}

		// Has flag for nullable property: shape
		public byte Hasshape { get; set; }

		// Nullable field: shape
		private IntPtr _shape;

/// {@template flutter.material.dialog.shape}
/// The shape of this dialog's border.
/// 
/// Defines the dialog's [Material.shape].
/// 
/// The default shape is a [RoundedRectangleBorder] with a radius of 4.0
/// {@endtemplate}
		public IntPtr shape
		{
			get => _shape;
			set { _shape = value; Hasshape = 1; }
		}

		// Has flag for nullable property: alignment
		public byte Hasalignment { get; set; }

		// Nullable field: alignment
		private IntPtr _alignment;

/// {@template flutter.material.dialog.alignment}
/// How to align the [Dialog].
/// 
/// If null, then [DialogThemeData.alignment] is used. If that is also null, the
/// default is [Alignment.center].
/// {@endtemplate}
		public IntPtr alignment
		{
			get => _alignment;
			set { _alignment = value; Hasalignment = 1; }
		}

		// Simple field: semanticsRole
/// The role this dialog represent in assist technologies.
/// 
/// Defaults to [SemanticsRole.dialog].
		public IntPtr semanticsRole { get; set; }

		// Has flag for nullable property: constraints
		public byte Hasconstraints { get; set; }

		// Nullable field: constraints
		private IntPtr _constraints;

/// {@template flutter.material.dialog.constraints}
/// Constrains the size of the dialog.
/// 
/// If null, then [DialogThemeData.constraints] is used. If that is also null, the
/// default is `const BoxConstraints(minWidth: 280.0)`.
/// {@endtemplate}
		public IntPtr constraints
		{
			get => _constraints;
			set { _constraints = value; Hasconstraints = 1; }
		}

	}
}
