// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Widgets;

namespace Flutter.Structs
{
/// A widget that combines the functionality of [Actions], [Shortcuts],
/// [MouseRegion] and a [Focus] widget to create a detector that defines actions
/// and key bindings, and provides callbacks for handling focus and hover
/// highlights.
/// 
/// {@youtube 560 315 https://www.youtube.com/watch?v=R84AGg0lKs8}
/// 
/// This widget can be used to give a control the required detection modes for
/// focus and hover handling. It is most often used when authoring a new control
/// widget, and the new control should be enabled for keyboard traversal and
/// activation.
/// 
/// {@tool dartpad}
/// This example shows how keyboard interaction can be added to a custom control
/// that changes color when hovered and focused, and can toggle a light when
/// activated, either by touch or by hitting the `X` key on the keyboard when
/// the "And Me" button has the keyboard focus (be sure to use TAB to move the
/// focus to the "And Me" button before trying it out).
/// 
/// This example defines its own key binding for the `X` key, but in this case,
/// there is also a default key binding for [ActivateAction] in the default key
/// bindings created by [WidgetsApp] (the parent for [MaterialApp], and
/// [CupertinoApp]), so the `ENTER` key will also activate the buttons.
/// 
/// ** See code in examples/api/lib/widgets/actions/focusable_action_detector.0.dart **
/// {@end-tool}
/// 
/// This widget doesn't have any visual representation, it is just a detector that
/// provides focus and hover capabilities.
/// 
/// It hosts its own [FocusNode] or uses [focusNode], if given.
	[StructLayout(LayoutKind.Sequential)]
	internal class FocusableActionDetectorStruct : SingleChildRenderObjectWidgetStruct
	{
		// Simple field: enabled
/// Is this widget enabled or not.
/// 
/// If disabled, will not send any notifications needed to update highlight or
/// focus state, and will not define or respond to any actions or shortcuts.
/// 
/// When disabled, adds [Focus] to the widget tree, but sets
/// [Focus.canRequestFocus] to false.
		public bool enabled { get; set; }

		// Has flag for nullable property: focusNode
		public byte HasfocusNode { get; set; }

		// Simple field: focusNode
/// {@macro flutter.widgets.Focus.focusNode}
		public IntPtr? focusNode { get; set; }

		// Simple field: autofocus
/// {@macro flutter.widgets.Focus.autofocus}
		public bool autofocus { get; set; }

		// Simple field: descendantsAreFocusable
/// {@macro flutter.widgets.Focus.descendantsAreFocusable}
		public bool descendantsAreFocusable { get; set; }

		// Simple field: descendantsAreTraversable
/// {@macro flutter.widgets.Focus.descendantsAreTraversable}
		public bool descendantsAreTraversable { get; set; }

		// Has flag for nullable property: actions
		public byte Hasactions { get; set; }

		// Simple field: actions
/// {@macro flutter.widgets.actions.actions}
		public IntPtr? actions { get; set; }

		// Has flag for nullable property: shortcuts
		public byte Hasshortcuts { get; set; }

		// Simple field: shortcuts
/// {@macro flutter.widgets.shortcuts.shortcuts}
		public IntPtr? shortcuts { get; set; }

		// Callback field: onShowFocusHighlight
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _onShowFocusHighlight;

/// A function that will be called when the focus highlight should be shown or
/// hidden.
/// 
/// This method is not triggered at the unmount of the widget.
		/// <summary>
		/// Action identifier for onShowFocusHighlight callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? onShowFocusHighlightAction
		{
			get => GetString(_onShowFocusHighlight);
			set => SetString(ref _onShowFocusHighlight, value);
		}

		// Callback field: onShowHoverHighlight
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _onShowHoverHighlight;

/// A function that will be called when the hover highlight should be shown or hidden.
/// 
/// This method is not triggered at the unmount of the widget.
		/// <summary>
		/// Action identifier for onShowHoverHighlight callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? onShowHoverHighlightAction
		{
			get => GetString(_onShowHoverHighlight);
			set => SetString(ref _onShowHoverHighlight, value);
		}

		// Callback field: onFocusChange
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _onFocusChange;

/// A function that will be called when the focus changes.
/// 
/// Called with true if the [focusNode] has primary focus.
		/// <summary>
		/// Action identifier for onFocusChange callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? onFocusChangeAction
		{
			get => GetString(_onFocusChange);
			set => SetString(ref _onFocusChange, value);
		}

		// Simple field: mouseCursor
/// The cursor for a mouse pointer when it enters or is hovering over the
/// widget.
/// 
/// The [mouseCursor] defaults to [MouseCursor.defer], deferring the choice of
/// cursor to the next region behind it in hit-test order.
		public object mouseCursor { get; set; }

		// Simple field: includeFocusSemantics
/// Whether to include semantics from [Focus].
/// 
/// Defaults to true.
		public bool includeFocusSemantics { get; set; }

		// Widget field: child
		private IntPtr _child;

/// The child widget for this [FocusableActionDetector] widget.
/// 
/// {@macro flutter.widgets.ProxyWidget.child}
		public IntPtr child
		{
			get => (IntPtr)_child;
			set => SetIntPtr(ref _child, value);
		}

	}
}
