// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Widgets;

namespace Flutter.Structs
{
/// A description of an icon fulfilled by a font glyph.
/// 
/// See [Icons] for a number of predefined icons available for material
/// design applications.
/// 
/// In release builds, the Flutter tool will tree shake out of bundled fonts
/// the code points (or instances of [IconData]) which are not referenced from
/// Dart app code. See the [staticIconProvider] annotation for more details.
	[StructLayout(LayoutKind.Sequential)]
	internal class IconDataStruct : WidgetStruct
	{
		// Simple field: codePoint
/// The Unicode code point at which this icon is stored in the icon font.
		public int codePoint { get; set; }

		// Has flag for nullable property: fontFamily
		public byte HasfontFamily { get; set; }

		// String field: fontFamily
		private IntPtr _fontFamily;

/// The font family from which the glyph for the [codePoint] will be selected.
		public string? fontFamily
		{
			get => GetString(_fontFamily);
			set => SetString(ref _fontFamily, value);
		}

		// Has flag for nullable property: fontPackage
		public byte HasfontPackage { get; set; }

		// String field: fontPackage
		private IntPtr _fontPackage;

/// The name of the package from which the font family is included.
/// 
/// The name is used by the [Icon] widget when configuring the [TextStyle] so
/// that the given [fontFamily] is obtained from the appropriate asset.
/// 
/// See also:
/// 
/// * [TextStyle], which describes how to use fonts from other packages.
		public string? fontPackage
		{
			get => GetString(_fontPackage);
			set => SetString(ref _fontPackage, value);
		}

		// Simple field: matchTextDirection
/// Whether this icon should be automatically mirrored in right-to-left
/// environments.
/// 
/// The [Icon] widget respects this value by mirroring the icon when the
/// [Directionality] is [TextDirection.rtl].
		public bool matchTextDirection { get; set; }

		// Has flag for nullable property: fontFamilyFallback
		public byte HasfontFamilyFallback { get; set; }

		// Simple field: fontFamilyFallback
/// The ordered list of font families to fall back on when a glyph cannot be found in a higher priority font family.
/// 
/// For more details, refer to the documentation of [TextStyle]
		public IntPtr? fontFamilyFallback { get; set; }

		// Simple field: hashCode
		public int hashCode { get; set; }

	}
}
