// <auto-generated>
// This file was manually updated for FlutterSharp Phase 4 - ListView implementation
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Widgets;

namespace Flutter.Structs
{
/// A scrollable list of widgets arranged linearly.
///
/// ListView is the most commonly used scrolling widget. It displays its
/// children one after another in the scroll direction.
///
/// For lists with a large number of items, use ListViewBuilder instead.
	[StructLayout(LayoutKind.Sequential)]
	internal class ListViewStruct : MultiChildRenderObjectWidgetStruct
	{
		// Has flag for nullable property: scrollDirection
		public byte HasscrollDirection { get; set; }

		/// The axis along which the scroll view scrolls.
		/// Defaults to Axis.vertical.
		public Axis scrollDirection { get; set; }

		// Has flag for nullable property: reverse
		public byte Hasreverse { get; set; }

		/// Whether the scroll view scrolls in the reading direction.
		/// Defaults to false.
		public bool reverse { get; set; }

		// Has flag for nullable property: shrinkWrap
		public byte HasshrinkWrap { get; set; }

		/// Whether the extent of the scroll view in the scrollDirection should be
		/// determined by the contents being viewed.
		/// Defaults to false.
		public bool shrinkWrap { get; set; }

		// Has flag for nullable property: itemExtent
		public byte HasitemExtent { get; set; }

		/// If non-null, forces the children to have the given extent in the scroll
		/// direction. More efficient than letting children determine their own extent.
		public double itemExtent { get; set; }

		// Has flag for nullable property: cacheExtent
		public byte HascacheExtent { get; set; }

		/// The viewport has an area before and after the visible area to cache items
		/// that are about to become visible when the user scrolls.
		public double cacheExtent { get; set; }

		// Has flag for nullable property: primary
		public byte Hasprimary { get; set; }

		/// Whether this is the primary scroll view associated with the parent
		/// PrimaryScrollController.
		public bool primary { get; set; }

		// Has flag for nullable property: addAutomaticKeepAlives
		public byte HasaddAutomaticKeepAlives { get; set; }

		/// Whether to wrap each child in an AutomaticKeepAlive.
		/// Defaults to true.
		public bool addAutomaticKeepAlives { get; set; }

		// Has flag for nullable property: addRepaintBoundaries
		public byte HasaddRepaintBoundaries { get; set; }

		/// Whether to wrap each child in a RepaintBoundary.
		/// Defaults to true.
		public bool addRepaintBoundaries { get; set; }

		// Has flag for nullable property: addSemanticIndexes
		public byte HasaddSemanticIndexes { get; set; }

		/// Whether to wrap each child in an IndexedSemantics.
		/// Defaults to true.
		public bool addSemanticIndexes { get; set; }

		// Has flag for nullable property: controller
		public byte Hascontroller { get; set; }

		/// The ScrollController ID for tracking scroll position.
		/// Links to a registered ScrollController instance.
		private IntPtr _controllerId;

		/// <summary>
		/// The ScrollController ID string.
		/// </summary>
		public string controllerId
		{
			get => GetString(_controllerId);
			set { SetString(ref _controllerId, value); Hascontroller = (byte)(value != null ? 1 : 0); }
		}
	}
}
