// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using Flutter;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;

namespace Flutter.Structs
{
/// A widget that prevents the user from interacting with widgets behind itself.
/// 
/// The modal barrier is the scrim that is rendered behind each route, which
/// generally prevents the user from interacting with the route below the
/// current route, and normally partially obscures such routes.
/// 
/// For example, when a dialog is on the screen, the page below the dialog is
/// usually darkened by the modal barrier.
/// 
/// See also:
/// 
/// * [ModalRoute], which indirectly uses this widget.
/// * [AnimatedModalBarrier], which is similar but takes an animated [color]
/// instead of a single color value.
	[StructLayout(LayoutKind.Sequential)]
	internal class ModalBarrierStruct : WidgetStruct
	{
/// If non-null, fill the barrier with this color.
/// 
/// See also:
/// 
/// * [ModalRoute.barrierColor], which controls this property for the
/// [ModalBarrier] built by [ModalRoute] pages.
		public IntPtr color { get; set; }

/// Specifies if the barrier will be dismissed when the user taps on it.
/// 
/// If true, and [onDismiss] is non-null, [onDismiss] will be called,
/// otherwise the current route will be popped from the ambient [Navigator].
/// 
/// If false, tapping on the barrier will do nothing.
/// 
/// See also:
/// 
/// * [ModalRoute.barrierDismissible], which controls this property for the
/// [ModalBarrier] built by [ModalRoute] pages.
		public bool dismissible { get; set; }

/// {@template flutter.widgets.ModalBarrier.onDismiss}
/// Called when the barrier is being dismissed.
/// 
/// If non-null [onDismiss] will be called in place of popping the current
/// route. It is up to the callback to handle dismissing the barrier.
/// 
/// If null, the ambient [Navigator]'s current route will be popped.
/// 
/// This field is ignored if [dismissible] is false.
/// {@endtemplate}
		public IntPtr onDismiss { get; set; }

/// Whether the modal barrier semantics are included in the semantics tree.
/// 
/// See also:
/// 
/// * [ModalRoute.semanticsDismissible], which controls this property for
/// the [ModalBarrier] built by [ModalRoute] pages.
		public NativeNullable<bool> barrierSemanticsDismissible { get; set; }

		IntPtr _semanticsLabel;
/// Semantics label used for the barrier if it is [dismissible].
/// 
/// The semantics label is read out by accessibility tools (e.g. TalkBack
/// on Android and VoiceOver on iOS) when the barrier is focused.
/// 
/// See also:
/// 
/// * [ModalRoute.barrierLabel], which controls this property for the
/// [ModalBarrier] built by [ModalRoute] pages.
		public string? semanticsLabel
		{
			get => GetString(_semanticsLabel);
			set => SetString(ref _semanticsLabel, value);
		}

/// {@template flutter.widgets.ModalBarrier.clipDetailsNotifier}
/// Contains a value of type [EdgeInsets] that specifies how the
/// [SemanticsNode.rect] of the widget should be clipped.
/// 
/// See also:
/// 
/// * [_SemanticsClipper], which utilizes the value inside to update the
/// [SemanticsNode.rect] for its child.
/// {@endtemplate}
		public IntPtr clipDetailsNotifier { get; set; }

		IntPtr _semanticsOnTapHint;
/// {@macro flutter.material.ModalBottomSheetRoute.barrierOnTapHint}
		public string? semanticsOnTapHint
		{
			get => GetString(_semanticsOnTapHint);
			set => SetString(ref _semanticsOnTapHint, value);
		}

	}
}