// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using Flutter;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;

namespace Flutter.Structs
{
/// The [Viewport] variant used by [NestedScrollView].
/// 
/// This viewport takes a [SliverOverlapAbsorberHandle] and notifies it any time
/// the viewport needs to recompute its layout (e.g. when it is scrolled).
	[StructLayout(LayoutKind.Sequential)]
	internal class NestedScrollViewViewportStruct : MultiChildRenderObjectWidgetStruct
	{
/// The handle to the [SliverOverlapAbsorber] that is feeding this injector.
		public IntPtr handle { get; set; }

	}
}