// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;
using Flutter.Services;
using Flutter.Navigation;

namespace Flutter.Structs
{
/// A scrolling container that allows the user to interactively reorder the
/// list items.
/// 
/// This widget is similar to one created by [ListView.builder], and uses
/// an [IndexedWidgetBuilder] to create each item.
/// 
/// It is up to the application to wrap each child (or an internal part of the
/// child such as a drag handle) with a drag listener that will recognize
/// the start of an item drag and then start the reorder by calling
/// [ReorderableListState.startItemDragReorder]. This is most easily achieved
/// by wrapping each child in a [ReorderableDragStartListener] or a
/// [ReorderableDelayedDragStartListener]. These will take care of recognizing
/// the start of a drag gesture and call the list state's
/// [ReorderableListState.startItemDragReorder] method.
/// 
/// This widget's [ReorderableListState] can be used to manually start an item
/// reorder, or cancel a current drag. To refer to the
/// [ReorderableListState] either provide a [GlobalKey] or use the static
/// [ReorderableList.of] method from an item's build method.
/// 
/// See also:
/// 
/// * [SliverReorderableList], a sliver list that allows the user to reorder
/// its items.
/// * [ReorderableListView], a Material Design list that allows the user to
/// reorder its items.
	[StructLayout(LayoutKind.Sequential)]
	internal class ReorderableListStruct : WidgetStruct
	{
		// Callback field: itemBuilder
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _itemBuilder;

/// {@template flutter.widgets.reorderable_list.itemBuilder}
/// Called, as needed, to build list item widgets.
/// 
/// List items are only built when they're scrolled into view.
/// 
/// The [IndexedWidgetBuilder] index parameter indicates the item's
/// position in the list. The value of the index parameter will be between
/// zero and one less than [itemCount]. All items in the list must have a
/// unique [Key], and should have some kind of listener to start the drag
/// (usually a [ReorderableDragStartListener] or
/// [ReorderableDelayedDragStartListener]).
/// {@endtemplate}
		/// <summary>
		/// Action identifier for itemBuilder callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? itemBuilderAction
		{
			get => GetString(_itemBuilder);
			set { SetString(ref _itemBuilder, value); }
		}

		// Simple field: itemCount
/// {@template flutter.widgets.reorderable_list.itemCount}
/// The number of items in the list.
/// 
/// It must be a non-negative integer. When zero, nothing is displayed and
/// the widget occupies no space.
/// {@endtemplate}
		public int itemCount { get; set; }

		// Callback field: onReorder
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _onReorder;

/// {@template flutter.widgets.reorderable_list.onReorder}
/// A callback used by the list to report that a list item has been dragged
/// to a new location in the list and the application should update the order
/// of the items.
/// {@endtemplate}
		/// <summary>
		/// Action identifier for onReorder callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? onReorderAction
		{
			get => GetString(_onReorder);
			set { SetString(ref _onReorder, value); }
		}

		// Has flag for nullable property: onReorderStart
		public byte HasonReorderStart { get; set; }

		// Callback field: onReorderStart
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _onReorderStart;

/// {@template flutter.widgets.reorderable_list.onReorderStart}
/// A callback that is called when an item drag has started.
/// 
/// The index parameter of the callback is the index of the selected item.
/// 
/// See also:
/// 
/// * [onReorderEnd], which is a called when the dragged item is dropped.
/// * [onReorder], which reports that a list item has been dragged to a new
/// location.
/// {@endtemplate}
		/// <summary>
		/// Action identifier for onReorderStart callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? onReorderStartAction
		{
			get => GetString(_onReorderStart);
			set { SetString(ref _onReorderStart, value); HasonReorderStart = (byte)(value != null ? 1 : 0); }
		}

		// Has flag for nullable property: onReorderEnd
		public byte HasonReorderEnd { get; set; }

		// Callback field: onReorderEnd
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _onReorderEnd;

/// {@template flutter.widgets.reorderable_list.onReorderEnd}
/// A callback that is called when the dragged item is dropped.
/// 
/// The index parameter of the callback is the index where the item is
/// dropped. Unlike [onReorder], this is called even when the list item is
/// dropped in the same location.
/// 
/// See also:
/// 
/// * [onReorderStart], which is a called when an item drag has started.
/// * [onReorder], which reports that a list item has been dragged to a new
/// location.
/// {@endtemplate}
		/// <summary>
		/// Action identifier for onReorderEnd callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? onReorderEndAction
		{
			get => GetString(_onReorderEnd);
			set { SetString(ref _onReorderEnd, value); HasonReorderEnd = (byte)(value != null ? 1 : 0); }
		}

		// Has flag for nullable property: proxyDecorator
		public byte HasproxyDecorator { get; set; }

		// Callback field: proxyDecorator
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _proxyDecorator;

/// {@template flutter.widgets.reorderable_list.proxyDecorator}
/// A callback that allows the app to add an animated decoration around
/// an item when it is being dragged.
/// {@endtemplate}
		/// <summary>
		/// Action identifier for proxyDecorator callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? proxyDecoratorAction
		{
			get => GetString(_proxyDecorator);
			set { SetString(ref _proxyDecorator, value); HasproxyDecorator = (byte)(value != null ? 1 : 0); }
		}

		// Has flag for nullable property: padding
		public byte Haspadding { get; set; }

		// Nullable field: padding
		private IntPtr _padding;

/// {@template flutter.widgets.reorderable_list.padding}
/// The amount of space by which to inset the list contents.
/// 
/// It defaults to `EdgeInsets.all(0)`.
/// {@endtemplate}
		public IntPtr padding
		{
			get => _padding;
			set { _padding = value; Haspadding = 1; }
		}

		// Simple field: scrollDirection
/// {@macro flutter.widgets.scroll_view.scrollDirection}
		public Axis scrollDirection { get; set; }

		// Simple field: reverse
/// {@macro flutter.widgets.scroll_view.reverse}
		public bool reverse { get; set; }

		// Has flag for nullable property: controller
		public byte Hascontroller { get; set; }

		// Nullable field: controller
		private IntPtr _controller;

/// {@macro flutter.widgets.scroll_view.controller}
		public IntPtr controller
		{
			get => _controller;
			set { _controller = value; Hascontroller = 1; }
		}

		// Has flag for nullable property: primary
		public byte Hasprimary { get; set; }

		// Nullable field: primary
		private bool _primary;

/// {@macro flutter.widgets.scroll_view.primary}
		public bool primary
		{
			get => _primary;
			set { _primary = value; Hasprimary = 1; }
		}

		// Has flag for nullable property: physics
		public byte Hasphysics { get; set; }

		// Nullable field: physics
		private IntPtr _physics;

/// {@macro flutter.widgets.scroll_view.physics}
		public IntPtr physics
		{
			get => _physics;
			set { _physics = value; Hasphysics = 1; }
		}

		// Simple field: shrinkWrap
/// {@macro flutter.widgets.scroll_view.shrinkWrap}
		public bool shrinkWrap { get; set; }

		// Simple field: anchor
/// {@macro flutter.widgets.scroll_view.anchor}
		public double anchor { get; set; }

		// Has flag for nullable property: cacheExtent
		public byte HascacheExtent { get; set; }

		// Nullable field: cacheExtent
		private double _cacheExtent;

/// {@macro flutter.rendering.RenderViewportBase.cacheExtent}
		public double cacheExtent
		{
			get => _cacheExtent;
			set { _cacheExtent = value; HascacheExtent = 1; }
		}

		// Simple field: dragStartBehavior
/// {@macro flutter.widgets.scrollable.dragStartBehavior}
		public DragStartBehavior dragStartBehavior { get; set; }

		// Has flag for nullable property: keyboardDismissBehavior
		public byte HaskeyboardDismissBehavior { get; set; }

		// Nullable field: keyboardDismissBehavior
		private ScrollViewKeyboardDismissBehavior _keyboardDismissBehavior;

/// {@macro flutter.widgets.scroll_view.keyboardDismissBehavior}
/// 
/// If [keyboardDismissBehavior] is null then it will fallback to the inherited
/// [ScrollBehavior.getKeyboardDismissBehavior].
		public ScrollViewKeyboardDismissBehavior keyboardDismissBehavior
		{
			get => _keyboardDismissBehavior;
			set { _keyboardDismissBehavior = value; HaskeyboardDismissBehavior = 1; }
		}

		// Has flag for nullable property: restorationId
		public byte HasrestorationId { get; set; }

		// String field: restorationId
		private IntPtr _restorationId;

/// {@macro flutter.widgets.scrollable.restorationId}
		public string? restorationId
		{
			get => GetString(_restorationId);
			set { SetString(ref _restorationId, value); HasrestorationId = (byte)(value != null ? 1 : 0); }
		}

		// Simple field: clipBehavior
/// {@macro flutter.material.Material.clipBehavior}
/// 
/// Defaults to [Clip.hardEdge].
		public Clip clipBehavior { get; set; }

		// Has flag for nullable property: itemExtent
		public byte HasitemExtent { get; set; }

		// Nullable field: itemExtent
		private double _itemExtent;

/// {@macro flutter.widgets.list_view.itemExtent}
		public double itemExtent
		{
			get => _itemExtent;
			set { _itemExtent = value; HasitemExtent = 1; }
		}

		// Has flag for nullable property: itemExtentBuilder
		public byte HasitemExtentBuilder { get; set; }

		// Callback field: itemExtentBuilder
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _itemExtentBuilder;

/// {@macro flutter.widgets.list_view.itemExtentBuilder}
		/// <summary>
		/// Action identifier for itemExtentBuilder callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? itemExtentBuilderAction
		{
			get => GetString(_itemExtentBuilder);
			set { SetString(ref _itemExtentBuilder, value); HasitemExtentBuilder = (byte)(value != null ? 1 : 0); }
		}

		// Has flag for nullable property: prototypeItem
		public byte HasprototypeItem { get; set; }

		// Widget field: prototypeItem
		private IntPtr _prototypeItem;

/// {@macro flutter.widgets.list_view.prototypeItem}
		public IntPtr? prototypeItem
		{
			get => _prototypeItem != IntPtr.Zero ? (IntPtr)_prototypeItem : null;
			set { SetIntPtr(ref _prototypeItem, value); HasprototypeItem = (byte)(value != null ? 1 : 0); }
		}

		// Has flag for nullable property: autoScrollerVelocityScalar
		public byte HasautoScrollerVelocityScalar { get; set; }

		// Nullable field: autoScrollerVelocityScalar
		private double _autoScrollerVelocityScalar;

/// {@macro flutter.widgets.EdgeDraggingAutoScroller.velocityScalar}
/// 
/// {@macro flutter.widgets.SliverReorderableList.autoScrollerVelocityScalar.default}
		public double autoScrollerVelocityScalar
		{
			get => _autoScrollerVelocityScalar;
			set { _autoScrollerVelocityScalar = value; HasautoScrollerVelocityScalar = 1; }
		}

		// Has flag for nullable property: dragBoundaryProvider
		public byte HasdragBoundaryProvider { get; set; }

		// Callback field: dragBoundaryProvider
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _dragBoundaryProvider;

/// {@template flutter.widgets.reorderable_list.dragBoundaryProvider}
/// A callback used to provide drag boundaries during drag-and-drop reordering.
/// 
/// If null, the delegate returned by `DragBoundary.forRectMaybeOf` will be used.
/// Defaults to null.
/// {@endtemplate}
		/// <summary>
		/// Action identifier for dragBoundaryProvider callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? dragBoundaryProviderAction
		{
			get => GetString(_dragBoundaryProvider);
			set { SetString(ref _dragBoundaryProvider, value); HasdragBoundaryProvider = (byte)(value != null ? 1 : 0); }
		}

	}
}
