// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Widgets;

namespace Flutter.Structs
{
/// A wrapper widget that will recognize the start of a drag on the wrapped
/// widget by a [PointerDownEvent], and immediately initiate dragging the
/// wrapped item to a new location in a reorderable list.
/// 
/// See also:
/// 
/// * [ReorderableDelayedDragStartListener], a similar wrapper that will
/// only recognize the start after a long press event.
/// * [ReorderableList], a widget list that allows the user to reorder
/// its items.
/// * [SliverReorderableList], a sliver list that allows the user to reorder
/// its items.
/// * [ReorderableListView], a Material Design list that allows the user to
/// reorder its items.
	[StructLayout(LayoutKind.Sequential)]
	internal class ReorderableDragStartListenerStruct : SingleChildRenderObjectWidgetStruct
	{
		// Simple field: index
/// The index of the associated item that will be dragged in the list.
		public int index { get; set; }

		// Simple field: enabled
/// Whether the [child] item can be dragged and moved in the list.
/// 
/// If true, the item can be moved to another location in the list when the
/// user taps on the child. If false, tapping on the child will be ignored.
		public bool enabled { get; set; }

	}
}
