// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;
using Flutter.Services;
using Flutter.Navigation;

namespace Flutter.Structs
{
/// A widget that rotates its child by a integral number of quarter turns.
/// 
/// Unlike [Transform], which applies a transform just prior to painting,
/// this object applies its rotation prior to layout, which means the entire
/// rotated box consumes only as much space as required by the rotated child.
/// 
/// {@youtube 560 315 https://www.youtube.com/watch?v=BFE6_UglLfQ}
/// 
/// {@tool snippet}
/// 
/// This snippet rotates the child (some [Text]) so that it renders from bottom
/// to top, like an axis label on a graph:
/// 
/// ```dart
/// const RotatedBox(
/// quarterTurns: 3,
/// child: Text('Hello World!'),
/// )
/// ```
/// {@end-tool}
/// 
/// See also:
/// 
/// * [Transform], which is a paint effect that allows you to apply an
/// arbitrary transform to a child.
/// * [Transform.rotate], which applies a rotation paint effect.
/// * The [catalog of layout widgets](https://flutter.dev/widgets/layout/).
	[StructLayout(LayoutKind.Sequential)]
	internal class RotatedBoxStruct : SingleChildRenderObjectWidgetStruct
	{
		// Simple field: quarterTurns
/// The number of clockwise quarter turns the child should be rotated.
		public int quarterTurns { get; set; }

	}
}
