// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Widgets;

namespace Flutter.Structs
{
/// A widget that applies a mask generated by a [Shader] to its child.
/// 
/// For example, [ShaderMask] can be used to gradually fade out the edge
/// of a child by using a [RadialGradient] mask.
/// 
/// {@youtube 560 315 https://www.youtube.com/watch?v=7sUL66pTQ7Q}
/// 
/// {@tool snippet}
/// 
/// This example makes the text look like it is on fire:
/// 
/// ```dart
/// ShaderMask(
/// shaderCallback: (Rect bounds) {
/// return RadialGradient(
/// center: Alignment.topLeft,
/// radius: 1.0,
/// colors: <Color>[Colors.yellow, Colors.deepOrange.shade900],
/// tileMode: TileMode.mirror,
/// ).createShader(bounds);
/// },
/// child: const Text(
/// "I'm burning the memories",
/// style: TextStyle(color: Colors.white),
/// ),
/// )
/// ```
/// {@end-tool}
/// 
/// See also:
/// 
/// * [Opacity], which can apply a uniform alpha effect to its child.
/// * [CustomPaint], which lets you draw directly on the canvas.
/// * [DecoratedBox], for another approach at decorating child widgets.
/// * [BackdropFilter], which applies an image filter to the background.
	[StructLayout(LayoutKind.Sequential)]
	internal class ShaderMaskStruct : SingleChildRenderObjectWidgetStruct
	{
		// Callback field: shaderCallback
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _shaderCallback;

/// Called to create the [dart:ui.Shader] that generates the mask.
/// 
/// The shader callback is called with the current size of the child so that
/// it can customize the shader to the size and location of the child.
/// 
/// Typically this will use a [LinearGradient], [RadialGradient], or
/// [SweepGradient] to create the [dart:ui.Shader], though the
/// [dart:ui.ImageShader] class could also be used.
		/// <summary>
		/// Action identifier for shaderCallback callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? shaderCallbackAction
		{
			get => GetString(_shaderCallback);
			set => SetString(ref _shaderCallback, value);
		}

		// Simple field: blendMode
/// The [BlendMode] to use when applying the shader to the child.
/// 
/// The default, [BlendMode.modulate], is useful for applying an alpha blend
/// to the child. Other blend modes can be used to create other effects.
		public BlendMode blendMode { get; set; }

	}
}
