// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;
using Flutter.Services;
using Flutter.Navigation;

namespace Flutter.Structs
{
/// An option used in a [SimpleDialog].
/// 
/// A simple dialog offers the user a choice between several options. This
/// widget is commonly used to represent each of the options. If the user
/// selects this option, the widget will call the [onPressed] callback, which
/// typically uses [Navigator.pop] to close the dialog.
/// 
/// The padding on a [SimpleDialogOption] is configured to combine with the
/// default [SimpleDialog.contentPadding] so that each option ends up 8 pixels
/// from the other vertically, with 20 pixels of spacing between the dialog's
/// title and the first option, and 24 pixels of spacing between the last option
/// and the bottom of the dialog.
/// 
/// {@tool snippet}
/// 
/// ```dart
/// SimpleDialogOption(
/// onPressed: () { Navigator.pop(context, Department.treasury); },
/// child: const Text('Treasury department'),
/// )
/// ```
/// {@end-tool}
/// 
/// See also:
/// 
/// * [SimpleDialog], for a dialog in which to use this widget.
/// * [showDialog], which actually displays the dialog and returns its result.
/// * [TextButton], which are commonly used as actions in other kinds of
/// dialogs, such as [AlertDialog]s.
/// * <https://material.io/design/components/dialogs.html#simple-dialog>
	[StructLayout(LayoutKind.Sequential)]
	internal class SimpleDialogOptionStruct : SingleChildRenderObjectWidgetStruct
	{
		// Has flag for nullable property: onPressed
		public byte HasonPressed { get; set; }

		// Callback field: onPressed
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _onPressed;

/// The callback that is called when this option is selected.
/// 
/// If this is set to null, the option cannot be selected.
/// 
/// When used in a [SimpleDialog], this will typically call [Navigator.pop]
/// with a value for [showDialog] to complete its future with.
		/// <summary>
		/// Action identifier for onPressed callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? onPressedAction
		{
			get => GetString(_onPressed);
			set { SetString(ref _onPressed, value); HasonPressed = (byte)(value != null ? 1 : 0); }
		}

		// Has flag for nullable property: padding
		public byte Haspadding { get; set; }

		// Nullable field: padding
		private IntPtr _padding;

/// The amount of space to surround the [child] with.
/// 
/// Defaults to EdgeInsets.symmetric(vertical: 8.0, horizontal: 24.0).
		public IntPtr padding
		{
			get => _padding;
			set { _padding = value; Haspadding = 1; }
		}

	}
}
