// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Widgets;

namespace Flutter.Structs
{
/// Holds a 2D floating-point size.
/// 
/// You can think of this as an [Offset] from the origin.
	[StructLayout(LayoutKind.Sequential)]
	internal class SizeStruct : WidgetStruct
	{
		// Simple field: width
/// The horizontal extent of this size.
		public double width { get; set; }

		// Simple field: height
/// The vertical extent of this size.
		public double height { get; set; }

	}
}
