// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;
using Flutter.Services;
using Flutter.Navigation;

namespace Flutter.Structs
{
/// A [SliverGrid] that animates items when they are inserted or removed.
/// 
/// This widget's [SliverAnimatedGridState] can be used to dynamically insert or
/// remove items. To refer to the [SliverAnimatedGridState] either provide a
/// [GlobalKey] or use the static [SliverAnimatedGrid.of] method from an item's
/// input callback.
/// 
/// {@tool dartpad}
/// This sample application uses a [SliverAnimatedGrid] to create an animated
/// effect when items are removed or added to the grid.
/// 
/// ** See code in examples/api/lib/widgets/animated_grid/sliver_animated_grid.0.dart **
/// {@end-tool}
/// 
/// See also:
/// 
/// * [AnimatedGrid], a non-sliver scrolling container that animates items when
/// they are inserted into or removed from a grid.
/// * [SliverGrid], which does not animate items when they are inserted or
/// removed from a grid.
/// * [SliverList], which displays a non-animated list of items.
/// * [SliverAnimatedList], which animates items added and removed from a list
/// instead of a grid.
	[StructLayout(LayoutKind.Sequential)]
	internal class SliverAnimatedGridStruct : WidgetStruct
	{
		// Simple field: gridDelegate
/// {@macro flutter.widgets.AnimatedGrid.gridDelegate}
		public IntPtr gridDelegate { get; set; }

		// Callback field: itemBuilder
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _itemBuilder;

		/// <summary>
		/// Action identifier for itemBuilder callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? itemBuilderAction
		{
			get => GetString(_itemBuilder);
			set { SetString(ref _itemBuilder, value); }
		}

		// Has flag for nullable property: findChildIndexCallback
		public byte HasfindChildIndexCallback { get; set; }

		// Callback field: findChildIndexCallback
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _findChildIndexCallback;

		/// <summary>
		/// Action identifier for findChildIndexCallback callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? findChildIndexCallbackAction
		{
			get => GetString(_findChildIndexCallback);
			set { SetString(ref _findChildIndexCallback, value); HasfindChildIndexCallback = (byte)(value != null ? 1 : 0); }
		}

		// Simple field: initialItemCount
		public int initialItemCount { get; set; }

	}
}
