// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;
using Flutter.Services;
using Flutter.Navigation;

namespace Flutter.Structs
{
/// A sliver that places multiple box children in a linear array along the main
/// axis.
/// 
/// _To learn more about slivers, see [CustomScrollView.slivers]._
/// 
/// Each child is forced to have the [SliverConstraints.crossAxisExtent] in the
/// cross axis but determines its own main axis extent.
/// 
/// [SliverList] determines its scroll offset by "dead reckoning" because
/// children outside the visible part of the sliver are not materialized, which
/// means [SliverList] cannot learn their main axis extent. Instead, newly
/// materialized children are placed adjacent to existing children.
/// 
/// {@youtube 560 315 https://www.youtube.com/watch?v=ORiTTaVY6mM}
/// 
/// If the children have a fixed extent in the main axis, consider using
/// [SliverFixedExtentList] rather than [SliverList] because
/// [SliverFixedExtentList] does not need to perform layout on its children to
/// obtain their extent in the main axis and is therefore more efficient.
/// 
/// {@macro flutter.widgets.SliverChildDelegate.lifecycle}
/// 
/// {@tool dartpad}
/// 
/// This example shows a [SliverList] with a dynamic number of items.
/// 
/// ** See code in examples/api/lib/widgets/sliver/sliver_list.0.dart **
/// {@end-tool}
/// 
/// See also:
/// 
/// * <https://docs.flutter.dev/ui/layout/scrolling/slivers>, a description
/// of what slivers are and how to use them.
/// * [CustomScrollView], which accepts slivers like [SliverList]
/// to create custom scroll effects.
/// * [SliverFixedExtentList], which is more efficient for children with
/// the same extent in the main axis.
/// * [SliverPrototypeExtentList], which is similar to [SliverFixedExtentList]
/// except that it uses a prototype list item instead of a pixel value to define
/// the main axis extent of each item.
/// * [SliverAnimatedList], which animates items added to or removed from a
/// list.
/// * [SliverGrid], which places multiple children in a two dimensional grid.
/// * [SliverAnimatedGrid], a sliver which animates items when they are
/// inserted into or removed from a grid.
	[StructLayout(LayoutKind.Sequential)]
	internal class SliverListStruct : WidgetStruct
	{
		// Simple field: @delegate
		public IntPtr @delegate { get; set; }

	}
}
