// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;
using Flutter.Services;
using Flutter.Navigation;

namespace Flutter.Structs
{
/// A sliver that places its box children in a linear array and constrains them
/// to have the corresponding extent returned by [itemExtentBuilder].
/// 
/// _To learn more about slivers, see [CustomScrollView.slivers]._
/// 
/// [SliverVariedExtentList] arranges its children in a line along
/// the main axis starting at offset zero and without gaps. Each child is
/// constrained to the corresponding extent along the main axis
/// and the [SliverConstraints.crossAxisExtent] along the cross axis.
/// 
/// [SliverVariedExtentList] is more efficient than [SliverList] because
/// [SliverVariedExtentList] does not need to lay out its children to obtain
/// their extent along the main axis. It's a little more flexible than
/// [SliverFixedExtentList] because this allow the children to have different extents.
/// 
/// See also:
/// 
/// * [SliverFixedExtentList], whose children are forced to a given pixel
/// extent.
/// * [SliverPrototypeExtentList], which is similar to [SliverFixedExtentList]
/// except that it uses a prototype list item instead of a pixel value to define
/// the main axis extent of each item.
/// * [SliverList], which does not require its children to have the same
/// extent in the main axis.
/// * [SliverFillViewport], which sizes its children based on the
/// size of the viewport, regardless of what else is in the scroll view.
	[StructLayout(LayoutKind.Sequential)]
	internal class SliverVariedExtentListStruct : WidgetStruct
	{
		// Callback field: itemExtentBuilder
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _itemExtentBuilder;

/// The children extent builder.
/// 
/// Should return null if asked to build an item extent with a greater index than
/// exists.
		/// <summary>
		/// Action identifier for itemExtentBuilder callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? itemExtentBuilderAction
		{
			get => GetString(_itemExtentBuilder);
			set { SetString(ref _itemExtentBuilder, value); }
		}

		// Simple field: @delegate
		public IntPtr @delegate { get; set; }

	}
}
