// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using Flutter;
using Flutter.Widgets;
using Flutter.Material;
using Flutter.Cupertino;

namespace Flutter.Structs
{
/// A Material Design visual indication that a scroll view has overscrolled.
/// 
/// A [StretchingOverscrollIndicator] listens for [ScrollNotification]s in order
/// to stretch the content of the [Scrollable]. These notifications are typically
/// generated by a [ScrollView], such as a [ListView] or a [GridView].
/// 
/// When triggered, the [StretchingOverscrollIndicator] generates an
/// [OverscrollIndicatorNotification] before showing an overscroll indication.
/// To prevent the indicator from showing the indication, call
/// [OverscrollIndicatorNotification.disallowIndicator] on the notification.
/// 
/// Created by [MaterialScrollBehavior.buildOverscrollIndicator] on platforms
/// (e.g., Android) that commonly use this type of overscroll indication when
/// [ThemeData.useMaterial3] is true. Otherwise, when [ThemeData.useMaterial3]
/// is false, a [GlowingOverscrollIndicator] is used instead.=
/// 
/// See also:
/// 
/// * [OverscrollIndicatorNotification], which can be used to prevent the
/// stretch effect from being applied at all.
/// * [NotificationListener], to listen for the
/// [OverscrollIndicatorNotification].
/// * [GlowingOverscrollIndicator], the default overscroll indicator for
/// [TargetPlatform.android] and [TargetPlatform.fuchsia].
	[StructLayout(LayoutKind.Sequential)]
	internal class StretchingOverscrollIndicatorStruct : SingleChildRenderObjectWidgetStruct
	{
/// {@macro flutter.overscroll.axisDirection}
		public IntPtr axisDirection { get; set; }

/// {@macro flutter.overscroll.notificationPredicate}
		public IntPtr notificationPredicate { get; set; }

/// {@macro flutter.material.Material.clipBehavior}
/// 
/// Defaults to [Clip.hardEdge].
		public Clip clipBehavior { get; set; }

		IntPtr _child;
/// The widget below this widget in the tree.
/// 
/// The overscroll indicator will apply a stretch effect to this child. This
/// child (and its subtree) should include a source of [ScrollNotification]
/// notifications.
		public Widget? child
		{
			set => SetIntPtr(ref _child, value);
		}

		public IntPtr axis { get; set; }

	}
}