// <auto-generated>
// This file was manually created for FlutterSharp Phase 4 - Input Widgets
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using Flutter;
using Flutter.Enums;
using Flutter.Widgets;
using Flutter.Material;

namespace Flutter.Structs
{
	/// <summary>
	/// FFI struct representation of the Material Design Switch widget.
	///
	/// A Material Design switch.
	///
	/// Used to toggle the on/off state of a single setting. The switch itself does not
	/// maintain any state. Instead, when the state of the switch changes, the widget calls
	/// the onChanged callback. Most widgets that use a switch will listen for the onChanged
	/// callback and rebuild the switch with a new value to update the visual appearance.
	/// </summary>
	[StructLayout(LayoutKind.Sequential)]
	internal class SwitchStruct : WidgetStruct
	{
		/// <summary>
		/// Whether this switch is on or off.
		/// </summary>
		public byte value { get; set; }

		// Has flag for nullable callback: onChanged
		public byte HasonChanged { get; set; }

		// Callback field: onChanged
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _onChanged;

		/// <summary>
		/// Action identifier for onChanged callback.
		/// Called when the user toggles the switch on or off.
		/// The callback passes the new value: true or false.
		/// </summary>
		public string? onChangedAction
		{
			get => GetString(_onChanged);
			set { SetString(ref _onChanged, value); HasonChanged = (byte)(value != null ? 1 : 0); }
		}

		// Has flag for nullable property: activeColor
		public byte HasactiveColor { get; set; }

		/// <summary>
		/// The color to use when this switch is on.
		/// Defaults to ThemeData.colorScheme.secondary.
		/// </summary>
		public int activeColor { get; set; }

		// Has flag for nullable property: activeTrackColor
		public byte HasactiveTrackColor { get; set; }

		/// <summary>
		/// The color to use on the track when this switch is on.
		/// </summary>
		public int activeTrackColor { get; set; }

		// Has flag for nullable property: inactiveThumbColor
		public byte HasinactiveThumbColor { get; set; }

		/// <summary>
		/// The color to use on the thumb when this switch is off.
		/// </summary>
		public int inactiveThumbColor { get; set; }

		// Has flag for nullable property: inactiveTrackColor
		public byte HasinactiveTrackColor { get; set; }

		/// <summary>
		/// The color to use on the track when this switch is off.
		/// </summary>
		public int inactiveTrackColor { get; set; }

		// Has flag for nullable property: focusColor
		public byte HasfocusColor { get; set; }

		/// <summary>
		/// The color for the switch's Material when it has the input focus.
		/// </summary>
		public int focusColor { get; set; }

		// Has flag for nullable property: hoverColor
		public byte HashoverColor { get; set; }

		/// <summary>
		/// The color for the switch's Material when a pointer is hovering over it.
		/// </summary>
		public int hoverColor { get; set; }

		// Has flag for nullable property: splashRadius
		public byte HassplashRadius { get; set; }

		/// <summary>
		/// The splash radius of the circular Material ink response.
		/// </summary>
		public double splashRadius { get; set; }

		// Has flag for nullable property: materialTapTargetSize
		public byte HasmaterialTapTargetSize { get; set; }

		/// <summary>
		/// Configures the minimum size of the tap target.
		/// </summary>
		public int materialTapTargetSize { get; set; }

		/// <summary>
		/// True if this widget will be selected as the initial focus.
		/// Defaults to false.
		/// </summary>
		public byte autofocus { get; set; }
	}
}
