// <auto-generated>
// This file was automatically generated by FlutterSharp.CodeGen
// Do not modify this file directly
// </auto-generated>

using System;
using System.Runtime.InteropServices;
using Flutter.Enums;
using Flutter.Gestures;
using Flutter.UI;
using Flutter.Widgets;

namespace Flutter.Structs
{
/// A [TapRegion] that adds its children to the tap region group for widgets
/// based on the [EditableText] text editing widget, such as [TextField] and
/// [CupertinoTextField].
/// 
/// Widgets that are wrapped with a [TextFieldTapRegion] are considered to be
/// part of a text field for purposes of unfocus behavior. So, when the user
/// taps on them, the currently focused text field won't be unfocused by
/// default. This allows controls like spinners, copy buttons, and formatting
/// buttons to be associated with a text field without causing the text field to
/// lose focus when they are interacted with.
/// 
/// {@tool dartpad}
/// This example shows how to use a [TextFieldTapRegion] to wrap a set of
/// "spinner" buttons that increment and decrement a value in the text field
/// without causing the text field to lose keyboard focus.
/// 
/// This example includes a generic `SpinnerField<T>` class that you can copy/paste
/// into your own project and customize.
/// 
/// ** See code in examples/api/lib/widgets/tap_region/text_field_tap_region.0.dart **
/// {@end-tool}
/// 
/// See also:
/// 
/// * [TapRegion], the widget that this widget uses to add widgets to the group
/// of text fields.
	[StructLayout(LayoutKind.Sequential)]
	internal class TextFieldTapRegionStruct : SingleChildRenderObjectWidgetStruct
	{
		// Has flag for nullable property: child
		public byte Haschild { get; set; }

		// Widget field: child
		private IntPtr _child;

		public IntPtr? child
		{
			get => _child != IntPtr.Zero ? (IntPtr)_child : null;
			set => SetIntPtr(ref _child, value);
		}

		// Simple field: enabled
		public bool enabled { get; set; }

		// Has flag for nullable property: onTapOutside
		public byte HasonTapOutside { get; set; }

		// Callback field: onTapOutside
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _onTapOutside;

		/// <summary>
		/// Action identifier for onTapOutside callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? onTapOutsideAction
		{
			get => GetString(_onTapOutside);
			set => SetString(ref _onTapOutside, value);
		}

		// Has flag for nullable property: onTapInside
		public byte HasonTapInside { get; set; }

		// Callback field: onTapInside
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _onTapInside;

		/// <summary>
		/// Action identifier for onTapInside callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? onTapInsideAction
		{
			get => GetString(_onTapInside);
			set => SetString(ref _onTapInside, value);
		}

		// Has flag for nullable property: onTapUpOutside
		public byte HasonTapUpOutside { get; set; }

		// Callback field: onTapUpOutside
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _onTapUpOutside;

		/// <summary>
		/// Action identifier for onTapUpOutside callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? onTapUpOutsideAction
		{
			get => GetString(_onTapUpOutside);
			set => SetString(ref _onTapUpOutside, value);
		}

		// Has flag for nullable property: onTapUpInside
		public byte HasonTapUpInside { get; set; }

		// Callback field: onTapUpInside
		// Using action string pattern - Dart will dispatch action to C# via method channel
		IntPtr _onTapUpInside;

		/// <summary>
		/// Action identifier for onTapUpInside callback.
		/// When this action is triggered in Dart, it will be dispatched to C# via method channel.
		/// Set to a string identifier (e.g., "button_pressed_main") that your C# action handler will recognize.
		/// </summary>
		public string? onTapUpInsideAction
		{
			get => GetString(_onTapUpInside);
			set => SetString(ref _onTapUpInside, value);
		}

		// Simple field: consumeOutsideTaps
		public bool consumeOutsideTaps { get; set; }

		// Has flag for nullable property: debugLabel
		public byte HasdebugLabel { get; set; }

		// String field: debugLabel
		private IntPtr _debugLabel;

		public string? debugLabel
		{
			get => GetString(_debugLabel);
			set => SetString(ref _debugLabel, value);
		}

		// Has flag for nullable property: groupId
		public byte HasgroupId { get; set; }

		// Simple field: groupId
		public IntPtr? groupId { get; set; }

	}
}
