// <auto-generated>
// This file was automatically generated on 2026-04-09 15:38:14 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi';
import 'package:ffi/ffi.dart';
import '../flutter_sharp_structs.dart';

/// Displays a grid of days for a given month and allows the user to select a
/// date.
///
/// Days are arranged in a rectangular grid with one column for each day of the
/// week. Controls are provided to change the year and month that the grid is
/// showing.
///
/// The calendar picker widget is rarely used directly. Instead, consider using
/// [showDatePicker], which will create a dialog that uses this as well as
/// provides a text entry option.
///
/// See also:
///
/// [showDatePicker], which creates a Dialog that contains a
/// [CalendarDatePicker] and provides an optional compact view where the
/// user can enter a date as a line of text.
/// [showTimePicker], which shows a dialog that contains a Material Design
/// time picker.
/// FFI struct representation of CalendarDatePicker widget.
/// This struct is used to pass widget data across the FFI boundary.
final class CalendarDatePickerStruct extends Struct {
  //FlutterObject Struct
  external Pointer handle;
  external Pointer managedHandle;
  external Pointer<Utf8> widgetType;
  //WidgetStruct
  external Pointer<Utf8> id;

  @Int8()
  external int hasInitialDate;

  /// The initially selected [DateTime] that the picker should display.
  ///
  /// Subsequently changing this has no effect. To change the selected date,
  /// change the [key] to create a new instance of the [CalendarDatePicker], and
  /// provide that widget the new [initialDate]. This will reset the widget's
  /// interactive state.
  @Int64()
  external int initialDate;

  /// The earliest allowable [DateTime] that the user can select.
  @Int64()
  external int firstDate;

  /// The latest allowable [DateTime] that the user can select.
  @Int64()
  external int lastDate;

  /// The [DateTime] representing today. It will be highlighted in the day grid.
  @Int64()
  external int currentDate;

  /// Called when the user selects a date in the picker.
  external Pointer<Utf8> onDateChangedAction;

  @Int8()
  external int hasOnDisplayedMonthChangedAction;

  /// Called when the user navigates to a new month/year in the picker.
  external Pointer<Utf8> onDisplayedMonthChangedAction;

  /// The initial display of the calendar picker.
  ///
  /// Subsequently changing this has no effect. To change the calendar mode,
  /// change the [key] to create a new instance of the [CalendarDatePicker], and
  /// provide that widget a new [initialCalendarMode]. This will reset the
  /// widget's interactive state.
  external Pointer<Void> initialCalendarMode;

  @Int8()
  external int hasSelectableDayPredicateAction;

  /// Function to provide full control over which dates in the calendar can be selected.
  external Pointer<Utf8> selectableDayPredicateAction;

  /// {@macro flutter.material.calendar_date_picker.calendarDelegate}
  external Pointer<Void> calendarDelegate;

}
