// <auto-generated>
// This file was automatically generated on 2026-04-09 15:38:14 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi';
import 'package:ffi/ffi.dart';
import '../flutter_sharp_structs.dart';
import 'borderradiusgeometry_struct.dart';

/// A widget that clips its child using a rounded rectangle.
///
/// By default, [ClipRRect] uses its own bounds as the base rectangle for the
/// clip, but the size and location of the clip can be customized using a custom
/// [clipper].
///
/// {@youtube 560 315 https://www.youtube.com/watch?v=eI43jkQkrvs}
///
/// {@tool dartpad}
/// This example shows various [ClipRRect]s applied to containers.
///
/// See code in examples/api/lib/widgets/basic/clip_rrect.0.dart **
/// {@end-tool}
///
/// ## Troubleshooting
///
/// ### Why doesn't my [ClipRRect] child have rounded corners?
///
/// When a [ClipRRect] is bigger than the child it contains, its rounded corners
/// could be drawn in unexpected positions. Make sure that [ClipRRect] and its child
/// have the same bounds (by shrinking the [ClipRRect] with a [FittedBox] or by
/// growing the child).
///
/// {@tool dartpad}
/// This example shows a [ClipRRect] that adds round corners to an image.
///
/// See code in examples/api/lib/widgets/basic/clip_rrect.1.dart **
/// {@end-tool}
///
/// See also:
///
/// [CustomClipper], for information about creating custom clips.
/// [ClipRect], for more efficient clips without rounded corners.
/// [ClipRSuperellipse], for a similar clipping shape with smoother
/// transitions between the straight sides and the rounded corners. This
/// shape closely matches the rounded rectangles commonly used in Apple’s
/// design language, resembling the `RoundedRectangle` shape in SwiftUI with
/// the `.continuous` corner style.
/// [ClipOval], for an elliptical clip.
/// [ClipPath], for an arbitrarily shaped clip.
/// FFI struct representation of ClipRRect widget.
/// This struct is used to pass widget data across the FFI boundary.
final class ClipRRectStruct extends Struct {
  //FlutterObject Struct
  external Pointer handle;
  external Pointer managedHandle;
  external Pointer<Utf8> widgetType;
  //WidgetStruct
  external Pointer<Utf8> id;

  @Int8()
  external int hasChild;

  external Pointer<WidgetStruct> child;

  /// The border radius of the rounded corners.
  ///
  /// Values are clamped so that horizontal and vertical radii sums do not
  /// exceed width/height.
  ///
  /// This value is ignored if [clipper] is non-null.
  external Pointer<BorderRadiusGeometryStruct> borderRadius;

  @Int8()
  external int hasClipper;

  /// If non-null, determines which clip to use.
  external Pointer<Void> clipper;

  /// {@macro flutter.rendering.ClipRectLayer.clipBehavior}
  ///
  /// Defaults to [Clip.antiAlias].
  @Int32()
  external int clipBehavior;

}
