// <auto-generated>
// This file was automatically generated on 2026-04-09 15:38:13 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi';
import 'package:ffi/ffi.dart';
import '../flutter_sharp_structs.dart';
import 'boxdecoration_struct.dart';
import 'edgeinsets_struct.dart';
import 'edgeinsetsgeometry_struct.dart';
import 'focusnode_struct.dart';
import 'scrollphysics_struct.dart';
import 'texteditingcontroller_struct.dart';
import 'textstyle_struct.dart';

/// Creates a [CupertinoFormRow] containing a [FormField] that wraps
/// a [CupertinoTextField].
///
/// A [Form] ancestor is not required. The [Form] allows one to
/// save, reset, or validate multiple fields at once. To use without a [Form],
/// pass a [GlobalKey] to the constructor and use [GlobalKey.currentState] to
/// save or reset the form field.
///
/// When a [controller] is specified, its [TextEditingController.text]
/// defines the [initialValue]. If this [FormField] is part of a scrolling
/// container that lazily constructs its children, like a [ListView] or a
/// [CustomScrollView], then a [controller] should be specified.
/// The controller's lifetime should be managed by a stateful widget ancestor
/// of the scrolling container.
///
/// The [prefix] parameter is displayed at the start of the row. Standard iOS
/// guidelines encourage passing a [Text] widget to [prefix] to detail the
/// nature of the input.
///
/// The [padding] parameter is used to pad the contents of the row. It is
/// directly passed to [CupertinoFormRow]. If the [padding]
/// parameter is null, [CupertinoFormRow] constructs its own default
/// padding (which is the standard form row padding in iOS.) If no edge
/// insets are intended, explicitly pass [EdgeInsets.zero] to [padding].
///
/// If a [controller] is not specified, [initialValue] can be used to give
/// the automatically generated controller an initial value.
///
/// Consider calling [TextEditingController.dispose] of the [controller], if one
/// is specified, when it is no longer needed. This will ensure we discard any
/// resources used by the object.
///
/// For documentation about the various parameters, see the
/// [CupertinoTextField] class and [CupertinoTextField.borderless],
/// the constructor.
///
/// {@tool snippet}
///
/// Creates a [CupertinoTextFormFieldRow] with a leading text and validator
/// function.
///
/// If the user enters valid text, the CupertinoTextField appears normally
/// without any warnings to the user.
///
/// If the user enters invalid text, the error message returned from the
/// validator function is displayed in dark red underneath the input.
///
/// ```dart
/// CupertinoTextFormFieldRow(
/// prefix: const Text('Username'),
/// onSaved: (String? value) {
/// This optional block of code can be used to run
/// code when the user saves the form.
/// },
/// validator: (String? value) {
/// return (value != null && value.contains('@')) ? 'Do not use the @ char.' : null;
/// },
/// )
/// ```
/// {@end-tool}
///
/// {@tool dartpad}
/// This example shows how to move the focus to the next field when the user
/// presses the SPACE key.
///
/// See code in examples/api/lib/cupertino/text_form_field_row/cupertino_text_form_field_row.1.dart **
/// {@end-tool}
/// FFI struct representation of CupertinoTextFormFieldRow widget.
/// This struct is used to pass widget data across the FFI boundary.
final class CupertinoTextFormFieldRowStruct extends Struct {
  //FlutterObject Struct
  external Pointer handle;
  external Pointer managedHandle;
  external Pointer<Utf8> widgetType;
  //WidgetStruct
  external Pointer<Utf8> id;

  @Int8()
  external int hasPrefix;

  /// A widget that is displayed at the start of the row.
  ///
  /// The [prefix] widget is displayed at the start of the row. Standard iOS
  /// guidelines encourage passing a [Text] widget to [prefix] to detail the
  /// nature of the input.
  external Pointer<WidgetStruct> prefix;

  @Int8()
  external int hasPadding;

  /// Content padding for the row.
  ///
  /// The [padding] widget is passed to [CupertinoFormRow]. If the [padding]
  /// parameter is null, [CupertinoFormRow] constructs its own default
  /// padding, which is the standard form row padding in iOS.
  ///
  /// If no edge insets are intended, explicitly pass [EdgeInsets.zero] to
  /// [padding].
  external Pointer<EdgeInsetsGeometryStruct> padding;

  @Int8()
  external int hasController;

  /// Controls the text being edited.
  ///
  /// If null, this widget will create its own [TextEditingController] and
  /// initialize its [TextEditingController.text] with [initialValue].
  external Pointer<TextEditingControllerStruct> controller;

  @Int8()
  external int hasOnChangedAction;

  /// {@macro flutter.material.TextFormField.onChanged}
  external Pointer<Utf8> onChangedAction;

  @Int8()
  external int hasInitialValue;

  external Pointer<Utf8> initialValue;

  @Int8()
  external int hasFocusNode;

  external Pointer<FocusNodeStruct> focusNode;

  @Int8()
  external int hasDecoration;

  external Pointer<BoxDecorationStruct> decoration;

  @Int8()
  external int hasKeyboardType;

  external Pointer<Void> keyboardType;

  @Int32()
  external int textCapitalization;

  @Int8()
  external int hasTextInputAction;

  @Int32()
  external int textInputAction;

  @Int8()
  external int hasStyle;

  external Pointer<TextStyleStruct> style;

  @Int8()
  external int hasStrutStyle;

  external Pointer<Void> strutStyle;

  @Int8()
  external int hasTextDirection;

  @Int32()
  external int textDirection;

  @Int32()
  external int textAlign;

  @Int8()
  external int hasTextAlignVertical;

  external Pointer<Void> textAlignVertical;

  @Int8()
  external int autofocus;

  @Int8()
  external int readOnly;

  @Int8()
  external int hasToolbarOptions;

  external Pointer<Void> toolbarOptions;

  @Int8()
  external int hasShowCursor;

  @Int8()
  external int showCursor;

  external Pointer<Utf8> obscuringCharacter;

  @Int8()
  external int obscureText;

  @Int8()
  external int autocorrect;

  @Int8()
  external int hasSmartDashesType;

  external Pointer<Void> smartDashesType;

  @Int8()
  external int hasSmartQuotesType;

  external Pointer<Void> smartQuotesType;

  @Int8()
  external int enableSuggestions;

  @Int8()
  external int hasMaxLines;

  @Int32()
  external int maxLines;

  @Int8()
  external int hasMinLines;

  @Int32()
  external int minLines;

  @Int8()
  external int expands;

  @Int8()
  external int hasMaxLength;

  @Int32()
  external int maxLength;

  @Int8()
  external int hasOnTapAction;

  external Pointer<Utf8> onTapAction;

  @Int8()
  external int hasOnEditingCompleteAction;

  external Pointer<Utf8> onEditingCompleteAction;

  @Int8()
  external int hasOnFieldSubmittedAction;

  external Pointer<Utf8> onFieldSubmittedAction;

  @Int8()
  external int hasOnSavedAction;

  external Pointer<Utf8> onSavedAction;

  @Int8()
  external int hasValidatorAction;

  external Pointer<Utf8> validatorAction;

  @Int8()
  external int hasInputFormatters;

  external Pointer<Void> inputFormatters;

  @Int8()
  external int hasEnabled;

  @Int8()
  external int enabled;

  @Double()
  external double cursorWidth;

  @Int8()
  external int hasCursorHeight;

  @Double()
  external double cursorHeight;

  @Int8()
  external int hasCursorColor;

  @Uint32()
  external int cursorColor;

  @Int8()
  external int hasKeyboardAppearance;

  @Int32()
  external int keyboardAppearance;

  external Pointer<EdgeInsetsStruct> scrollPadding;

  @Int8()
  external int enableInteractiveSelection;

  @Int8()
  external int hasSelectionControls;

  external Pointer<Void> selectionControls;

  @Int8()
  external int hasScrollPhysics;

  external Pointer<ScrollPhysicsStruct> scrollPhysics;

  @Int8()
  external int hasAutofillHints;

  external Pointer<Void> autofillHints;

  @Int32()
  external int autovalidateMode;

  @Int8()
  external int hasPlaceholder;

  external Pointer<Utf8> placeholder;

  @Int8()
  external int hasPlaceholderStyle;

  external Pointer<TextStyleStruct> placeholderStyle;

  @Int8()
  external int hasContextMenuBuilderAction;

  external Pointer<Utf8> contextMenuBuilderAction;

  @Int8()
  external int hasSpellCheckConfiguration;

  external Pointer<Void> spellCheckConfiguration;

  @Int8()
  external int hasSelectionHeightStyle;

  @Int32()
  external int selectionHeightStyle;

  @Int8()
  external int hasSelectionWidthStyle;

  @Int32()
  external int selectionWidthStyle;

  @Int8()
  external int hasRestorationId;

  external Pointer<Utf8> restorationId;

}
