// <auto-generated>
// This file was automatically generated on 2026-04-09 15:38:14 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi';
import 'package:ffi/ffi.dart';
import '../flutter_sharp_structs.dart';

/// The selection style to apply to descendant [EditableText] widgets which
/// don't have an explicit style.
///
/// {@macro flutter.cupertino.CupertinoApp.defaultSelectionStyle}
///
/// {@macro flutter.material.MaterialApp.defaultSelectionStyle}
///
/// See also:
/// [TextSelectionTheme]: which also creates a [DefaultSelectionStyle] for
/// the subtree.
/// FFI struct representation of DefaultSelectionStyle widget.
/// This struct is used to pass widget data across the FFI boundary.
final class DefaultSelectionStyleStruct extends Struct {
  //FlutterObject Struct
  external Pointer handle;
  external Pointer managedHandle;
  external Pointer<Utf8> widgetType;
  //WidgetStruct
  external Pointer<Utf8> id;

  external Pointer<WidgetStruct> child;

  @Int8()
  external int hasCursorColor;

  /// The color of the text field's cursor.
  ///
  /// The cursor indicates the current location of the text insertion point in
  /// the field.
  @Uint32()
  external int cursorColor;

  @Int8()
  external int hasSelectionColor;

  /// The background color of selected text.
  @Uint32()
  external int selectionColor;

  @Int8()
  external int hasMouseCursor;

  /// The [MouseCursor] for mouse pointers hovering over selectable Text widgets.
  ///
  /// If this property is null, [SystemMouseCursors.text] will be used.
  external Pointer<Void> mouseCursor;

}
