// <auto-generated>
// This file was automatically generated on 2026-01-07 22:15:10 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi';
import 'package:ffi/ffi.dart';
import '../../flutter_sharp_structs.dart';

/// /// The selection style to apply to descendant [EditableText] widgets which
/// don't have an explicit style.
///
/// {@macro flutter.cupertino.CupertinoApp.defaultSelectionStyle}
///
/// {@macro flutter.material.MaterialApp.defaultSelectionStyle}
///
/// See also:
/// * [TextSelectionTheme]: which also creates a [DefaultSelectionStyle] for
/// the subtree.
/// FFI struct representation of DefaultSelectionStyle widget.
/// This struct is used to pass widget data across the FFI boundary.
final class DefaultSelectionStyleStruct extends Struct {
  ///   /// The color of the text field's cursor.
  ///
  /// The cursor indicates the current location of the text insertion point in
  /// the field.
  @Uint32()
  external int cursorColor;

  ///   /// The background color of selected text.
  @Uint32()
  external int selectionColor;

  @Int8()
  external int hasMouseCursor;

  ///   /// The [MouseCursor] for mouse pointers hovering over selectable Text widgets.
  ///
  /// If this property is null, [SystemMouseCursors.text] will be used.
  external Pointer<Void> mouseCursor;

  @Int8()
  external int hasChild;

  external Pointer<WidgetStruct> child;

}
