// <auto-generated>
// This file was automatically generated on 2026-04-09 02:46:15 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi';
import 'package:ffi/ffi.dart';
import 'borderradiusgeometry_struct.dart';

/// A thin horizontal line, with padding on either side.
///
/// In the Material Design language, this represents a divider. Dividers can be
/// used in lists, [Drawer]s, and elsewhere to separate content.
///
/// To create a divider between [ListTile] items, consider using
/// [ListTile.divideTiles], which is optimized for this case.
///
/// {@youtube 560 315 https://www.youtube.com/watch?v=_liUC641Nmk}
///
/// The box's total height is controlled by [height]. The appropriate
/// padding is automatically computed from the height.
///
/// {@tool dartpad}
/// This sample shows how to display a Divider between an orange and blue box
/// inside a column. The Divider is 20 logical pixels in height and contains a
/// vertically centered black line that is 5 logical pixels thick. The black
/// line is indented by 20 logical pixels.
///
/// ![](https://flutter.github.io/assets-for-api-docs/assets/material/divider.png)
///
/// See code in examples/api/lib/material/divider/divider.0.dart **
/// {@end-tool}
///
/// {@tool dartpad}
/// This sample shows the creation of [Divider] widget, as described in:
/// https://m3.material.io/components/divider/overview
///
/// See code in examples/api/lib/material/divider/divider.1.dart **
/// {@end-tool}
///
/// See also:
///
/// [PopupMenuDivider], which is the equivalent but for popup menus.
/// [ListTile.divideTiles], another approach to dividing widgets in a list.
/// [VerticalDivider], which is the vertical analog of this widget.
/// <https://material.io/design/components/dividers.html>
/// FFI struct representation of Divider widget.
/// This struct is used to pass widget data across the FFI boundary.
final class DividerStruct extends Struct {
  //FlutterObject Struct
  external Pointer handle;
  external Pointer managedHandle;
  external Pointer<Utf8> widgetType;
  //WidgetStruct
  external Pointer<Utf8> id;

  @Int8()
  external int hasHeight;

  /// The divider's height extent.
  ///
  /// The divider itself is always drawn as a horizontal line that is centered
  /// within the height specified by this value.
  ///
  /// If this is null, then the [DividerThemeData.space] is used. If that is
  /// also null, then this defaults to 16.0.
  @Double()
  external double height;

  @Int8()
  external int hasThickness;

  /// The thickness of the line drawn within the divider.
  ///
  /// {@template flutter.material.Divider.thickness}
  /// A divider with a [thickness] of 0.0 is always drawn as a line with a
  /// height of exactly one device pixel.
  ///
  /// If this is null, then the [DividerThemeData.thickness] is used. If
  /// that is also null, then this defaults to 0.0.
  /// {@endtemplate}
  @Double()
  external double thickness;

  @Int8()
  external int hasIndent;

  /// The amount of empty space to the leading edge of the divider.
  ///
  /// {@template flutter.material.Divider.indent}
  /// If this is null, then the [DividerThemeData.indent] is used. If that is
  /// also null, then this defaults to 0.0.
  /// {@endtemplate}
  @Double()
  external double indent;

  @Int8()
  external int hasEndIndent;

  /// The amount of empty space to the trailing edge of the divider.
  ///
  /// {@template flutter.material.Divider.endIndent}
  /// If this is null, then the [DividerThemeData.endIndent] is used. If that is
  /// also null, then this defaults to 0.0.
  /// {@endtemplate}
  @Double()
  external double endIndent;

  @Int8()
  external int hasRadius;

  /// {@template flutter.material.Divider.radius}
  /// The amount of radius for the border of the divider.
  ///
  /// If this is null, then [DividerThemeData.radius] is used. If that is
  /// also null, then the default radius of [BoxDecoration] is used.
  /// {@endtemplate}
  external Pointer<BorderRadiusGeometryStruct> radius;

  @Int8()
  external int hasColor;

  /// {@template flutter.material.Divider.color}
  /// The color to use when painting the line.
  ///
  /// If this is null, then the [DividerThemeData.color] is used. If that is
  /// also null, then [ThemeData.dividerColor] is used.
  /// {@endtemplate}
  ///
  /// {@tool snippet}
  ///
  /// ```dart
  /// const Divider(
  /// color: Colors.deepOrange,
  /// )
  /// ```
  /// {@end-tool}
  @Uint32()
  external int color;
}
