// <auto-generated>
// This file was automatically generated on 2026-04-09 02:46:15 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi';
import 'package:ffi/ffi.dart';
import '../../flutter_sharp_structs.dart';
import 'focusnode_struct.dart';

/// A Material Design "elevated button".
///
/// Use elevated buttons to add dimension to otherwise mostly flat
/// layouts, e.g. in long busy lists of content, or in wide
/// spaces. Avoid using elevated buttons on already-elevated content
/// such as dialogs or cards.
///
/// An elevated button is a label [child] displayed on a [Material]
/// widget whose [Material.elevation] increases when the button is
/// pressed. The label's [Text] and [Icon] widgets are displayed in
/// [style]'s [ButtonStyle.foregroundColor] and the button's filled
/// background is the [ButtonStyle.backgroundColor].
///
/// The elevated button's default style is defined by
/// [defaultStyleOf]. The style of this elevated button can be
/// overridden with its [style] parameter. The style of all elevated
/// buttons in a subtree can be overridden with the
/// [ElevatedButtonTheme], and the style of all of the elevated
/// buttons in an app can be overridden with the [Theme]'s
/// [ThemeData.elevatedButtonTheme] property.
///
/// The static [styleFrom] method is a convenient way to create a
/// elevated button [ButtonStyle] from simple values.
///
/// If [onPressed] and [onLongPress] callbacks are null, then the
/// button will be disabled.
///
/// {@tool dartpad}
/// This sample produces an enabled and a disabled ElevatedButton.
///
/// See code in examples/api/lib/material/elevated_button/elevated_button.0.dart **
/// {@end-tool}
///
/// See also:
///
/// [FilledButton], a filled button that doesn't elevate when pressed.
/// [FilledButton.tonal], a filled button variant that uses a secondary fill color.
/// [OutlinedButton], a button with an outlined border and no fill color.
/// [TextButton], a button with no outline or fill color.
/// <https://material.io/design/components/buttons.html>
/// <https://m3.material.io/components/buttons>
/// FFI struct representation of ElevatedButton widget.
/// This struct is used to pass widget data across the FFI boundary.
final class ElevatedButtonStruct extends Struct {
  //FlutterObject Struct
  external Pointer handle;
  external Pointer managedHandle;
  external Pointer<Utf8> widgetType;
  //WidgetStruct
  external Pointer<Utf8> id;

  @Int8()
  external int hasChild;

  external Pointer<WidgetStruct> child;

  @Int8()
  external int hasOnPressedAction;

  external Pointer<Utf8> onPressedAction;

  @Int8()
  external int hasOnLongPressAction;

  external Pointer<Utf8> onLongPressAction;

  @Int8()
  external int hasOnHoverAction;

  external Pointer<Utf8> onHoverAction;

  @Int8()
  external int hasOnFocusChangeAction;

  external Pointer<Utf8> onFocusChangeAction;

  @Int8()
  external int hasStyle;

  external Pointer<Void> style;

  @Int8()
  external int hasFocusNode;

  external Pointer<FocusNodeStruct> focusNode;

  @Int8()
  external int autofocus;

  @Int8()
  external int hasClipBehavior;

  @Int32()
  external int clipBehavior;

  @Int8()
  external int hasStatesController;

  external Pointer<Void> statesController;
}
