// <auto-generated>
// This file was automatically generated on 2026-01-07 09:38:34 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi';
import 'package:ffi/ffi.dart';
import '../../flutter_sharp_structs.dart';
import 'statefulwidget_struct.dart';
import 'curve_struct.dart';

/// /// A [StatefulWidget] that expands and collapses.
///
/// An [Expansible] consists of a header, which is always shown, and a
/// body, which is hidden in its collapsed state and shown in its expanded
/// state.
///
/// The [Expansible] is expanded or collapsed with an animation driven by an
/// [AnimationController]. When the widget is expanded, the height of its body
/// animates from 0 to its fully expanded height.
///
/// This widget is typically used with [ListView] to create an "expand /
/// collapse" list entry. When used with scrolling widgets like [ListView], a
/// unique [PageStorageKey] must be specified as the [key], to enable the
/// [Expansible] to save and restore its expanded state when it is scrolled
/// in and out of view.
///
/// Provide [headerBuilder] and [bodyBuilder] callbacks to
/// build the header and body widgets. An additional [expansibleBuilder]
/// callback can be provided to further customize the layout of the widget.
///
/// The [Expansible] does not inherently toggle the expansion state. To toggle
/// the expansion state, call [ExpansibleController.expand] and
/// [ExpansibleController.collapse] as needed, most typically when the header
/// returned in [headerBuilder] is tapped.
///
/// See also:
///
/// * [ExpansionTile], a Material-styled widget that expands and collapses.
/// FFI struct representation of Expansible widget.
/// This struct is used to pass widget data across the FFI boundary.
final class ExpansibleStruct extends Struct {
  //FlutterObject Struct
  external Pointer handle;
  external Pointer managedHandle;
  external Pointer<Utf8> widgetType;
  //WidgetStruct
  external Pointer<Utf8> id;

  @Int8()
  external int hasController;

  ///   /// Expands and collapses the widget.
  ///
  /// The controller manages the expansion state and toggles the expansion.
  external Pointer<Void> controller;

  @Int8()
  external int hasHeaderBuilderAction;

  ///   /// Builds the always-displayed header.
  ///
  /// Many use cases involve toggling the expansion state when this header is
  /// tapped. To toggle the expansion state, call [ExpansibleController.expand]
  /// or [ExpansibleController.collapse].
  external Pointer<NativeFunction<Pointer<Void> Function()>> headerBuilderAction;

  @Int8()
  external int hasBodyBuilderAction;

  ///   /// Builds the collapsible body.
  ///
  /// When this widget is expanded, the height of its body animates from 0 to
  /// its fully extended height.
  external Pointer<NativeFunction<Pointer<Void> Function()>> bodyBuilderAction;

  ///   /// The duration of the expansion animation.
  ///
  /// Defaults to a duration of 200ms.
  @Int64()
  external int duration;

  @Int8()
  external int hasCurve;

  ///   /// The curve of the expansion animation.
  ///
  /// Defaults to [Curves.ease].
  external Pointer<CurveStruct> curve;

  @Int8()
  external int hasReverseCurve;

  ///   /// The reverse curve of the expansion animation.
  ///
  /// If null, uses [curve] in both directions.
  external Pointer<Void> reverseCurve;

  ///   /// Whether the state of the body is maintained when the widget expands or
  /// collapses.
  ///
  /// If true, the body is kept in the tree while the widget is
  /// collapsed. Otherwise, the body is removed from the tree when the
  /// widget is collapsed and recreated upon expansion.
  ///
  /// Defaults to false.
  @Int8()
  external int maintainState;

  @Int8()
  external int hasExpansibleBuilderAction;

  ///   /// Builds the widget with the results of [headerBuilder] and [bodyBuilder].
  ///
  /// Defaults to placing the header and body in a [Column].
  external Pointer<NativeFunction<Pointer<Void> Function()>> expansibleBuilderAction;

}
