// <auto-generated>
// This file was automatically generated on 2026-04-09 15:38:14 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi';
import 'package:ffi/ffi.dart';
import '../flutter_sharp_structs.dart';
import 'curve_struct.dart';

/// The Flutter logo, in widget form. This widget respects the [IconTheme].
/// For guidelines on using the Flutter logo, visit https://flutter.dev/brand.
///
/// {@youtube 560 315 https://www.youtube.com/watch?v=aAmP-WcI6dg}
///
/// See also:
///
/// [IconTheme], which provides ambient configuration for icons.
/// [Icon], for showing icons the Material design icon library.
/// [ImageIcon], for showing icons from [AssetImage]s or other [ImageProvider]s.
/// FFI struct representation of FlutterLogo widget.
/// This struct is used to pass widget data across the FFI boundary.
final class FlutterLogoStruct extends Struct {
  //FlutterObject Struct
  external Pointer handle;
  external Pointer managedHandle;
  external Pointer<Utf8> widgetType;
  //WidgetStruct
  external Pointer<Utf8> id;

  @Int8()
  external int hasSize;

  /// The size of the logo in logical pixels.
  ///
  /// The logo will be fit into a square this size.
  ///
  /// Defaults to the current [IconTheme] size, if any. If there is no
  /// [IconTheme], or it does not specify an explicit size, then it defaults to
  /// 24.0.
  @Double()
  external double size;

  /// The color used to paint the "Flutter" text on the logo, if [style] is
  /// [FlutterLogoStyle.horizontal] or [FlutterLogoStyle.stacked].
  ///
  /// If possible, the default (a medium grey) should be used against a white
  /// background.
  @Uint32()
  external int textColor;

  /// Whether and where to draw the "Flutter" text. By default, only the logo
  /// itself is drawn.
  external Pointer<Void> style;

  /// The length of time for the animation if the [style] or [textColor]
  /// properties are changed.
  @Int64()
  external int duration;

  /// The curve for the logo animation if the [style] or [textColor] change.
  external Pointer<CurveStruct> curve;

}
