// <auto-generated>
// This file was automatically generated on 2026-04-09 02:46:15 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi';
import 'package:ffi/ffi.dart';
import '../flutter_sharp_structs.dart';

/// A header used in a Material Design [GridTile].
///
/// Typically used to add a one or two line header or footer on a [GridTile].
///
/// For a one-line header, include a [title] widget. To add a second line, also
/// include a [subtitle] widget. Use [leading] or [trailing] to add an icon.
///
/// See also:
///
/// [GridTile]
/// <https://material.io/design/components/image-lists.html#anatomy>
/// FFI struct representation of GridTileBar widget.
/// This struct is used to pass widget data across the FFI boundary.
final class GridTileBarStruct extends Struct {
  //FlutterObject Struct
  external Pointer handle;
  external Pointer managedHandle;
  external Pointer<Utf8> widgetType;
  //WidgetStruct
  external Pointer<Utf8> id;

  @Int8()
  external int hasBackgroundColor;

  /// The color to paint behind the child widgets.
  ///
  /// Defaults to transparent.
  @Uint32()
  external int backgroundColor;

  @Int8()
  external int hasLeading;

  /// A widget to display before the title.
  ///
  /// Typically an [Icon] or an [IconButton] widget.
  external Pointer<WidgetStruct> leading;

  @Int8()
  external int hasTitle;

  /// The primary content of the list item.
  ///
  /// Typically a [Text] widget.
  external Pointer<WidgetStruct> title;

  @Int8()
  external int hasSubtitle;

  /// Additional content displayed below the title.
  ///
  /// Typically a [Text] widget.
  external Pointer<WidgetStruct> subtitle;

  @Int8()
  external int hasTrailing;

  /// A widget to display after the title.
  ///
  /// Typically an [Icon] or an [IconButton] widget.
  external Pointer<WidgetStruct> trailing;
}
