// <auto-generated>
// This file was automatically generated on 2026-04-09 02:46:15 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi';
import 'package:ffi/ffi.dart';
import '../../flutter_sharp_structs.dart';

/// Overrides the default [ButtonStyle] of its [MenuItemButton] and
/// [SubmenuButton] descendants.
///
/// See also:
///
/// [MenuButtonThemeData], which is used to configure this theme.
/// [MenuTheme], the theme used to configure the look of the menus themselves.
/// [MenuItemButton.defaultStyleOf] and [SubmenuButton.defaultStyleOf] which
/// return the default [ButtonStyle]s for menu buttons.
/// [MenuItemButton.styleFrom] and [SubmenuButton.styleFrom], which converts
/// simple values into a [ButtonStyle] that's consistent with their respective
/// defaults.
/// [ThemeData.menuButtonTheme], which can be used to override the default
/// [ButtonStyle] for [MenuItemButton]s and [SubmenuButton]s below the overall
/// [Theme].
/// FFI struct representation of MenuButtonTheme widget.
/// This struct is used to pass widget data across the FFI boundary.
final class MenuButtonThemeStruct extends Struct {
  //FlutterObject Struct
  external Pointer handle;
  external Pointer managedHandle;
  external Pointer<Utf8> widgetType;
  //WidgetStruct
  external Pointer<Utf8> id;

  external Pointer<WidgetStruct> child;

  /// The configuration of this theme.
  external Pointer<Void> data;
}
