// <auto-generated>
// This file was automatically generated on 2026-04-09 02:46:15 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi';
import 'package:ffi/ffi.dart';
import '../../flutter_sharp_structs.dart';

/// An inherited widget that defines the configuration in this widget's
/// descendants for menus created by the [SubmenuButton], [MenuBar], or
/// [MenuAnchor] widgets.
///
/// Values specified here are used for [SubmenuButton]'s menu properties that
/// are not given an explicit non-null value.
///
/// See also:
///
/// [MenuThemeData], a configuration object that holds attributes of a menu
/// used by this theme.
/// [MenuBarTheme], which does the same thing for the [MenuBar] widget.
/// [MenuBar], a widget that manages [MenuItemButton]s.
/// [MenuAnchor], a widget that creates a region that has a submenu.
/// [MenuItemButton], a widget that is a selectable item in a menu bar menu.
/// [SubmenuButton], a widget that specifies an item with a cascading submenu
/// in a [MenuBar] menu.
/// FFI struct representation of MenuTheme widget.
/// This struct is used to pass widget data across the FFI boundary.
final class MenuThemeStruct extends Struct {
  //FlutterObject Struct
  external Pointer handle;
  external Pointer managedHandle;
  external Pointer<Utf8> widgetType;
  //WidgetStruct
  external Pointer<Utf8> id;

  external Pointer<WidgetStruct> child;

  /// The properties for [MenuBar] and [MenuItemButton] in this widget's
  /// descendants.
  external Pointer<Void> data;
}
