// <auto-generated>
// This file was automatically generated on 2026-04-09 02:46:15 UTC
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

import 'dart:ffi';
import 'package:ffi/ffi.dart';
import '../../flutter_sharp_structs.dart';
import 'focusnode_struct.dart';

/// A Material Design "Text Button".
///
/// Use text buttons on toolbars, in dialogs, or inline with other
/// content but offset from that content with padding so that the
/// button's presence is obvious. Text buttons do not have visible
/// borders and must therefore rely on their position relative to
/// other content for context. In dialogs and cards, they should be
/// grouped together in one of the bottom corners. Avoid using text
/// buttons where they would blend in with other content, for example
/// in the middle of lists.
///
/// A text button is a label [child] displayed on a (zero elevation)
/// [Material] widget. The label's [Text] and [Icon] widgets are
/// displayed in the [style]'s [ButtonStyle.foregroundColor]. The
/// button reacts to touches by filling with the [style]'s
/// [ButtonStyle.backgroundColor].
///
/// The text button's default style is defined by [defaultStyleOf].
/// The style of this text button can be overridden with its [style]
/// parameter. The style of all text buttons in a subtree can be
/// overridden with the [TextButtonTheme] and the style of all of the
/// text buttons in an app can be overridden with the [Theme]'s
/// [ThemeData.textButtonTheme] property.
///
/// The static [styleFrom] method is a convenient way to create a
/// text button [ButtonStyle] from simple values.
///
/// If the [onPressed] and [onLongPress] callbacks are null, then this
/// button will be disabled, it will not react to touch.
///
/// {@tool dartpad}
/// This sample shows various ways to configure TextButtons, from the
/// simplest default appearance to versions that don't resemble
/// Material Design at all.
///
/// See code in examples/api/lib/material/text_button/text_button.0.dart **
/// {@end-tool}
///
/// {@tool dartpad}
/// This sample demonstrates using the [statesController] parameter to create a button
/// that adds support for [WidgetState.selected].
///
/// See code in examples/api/lib/material/text_button/text_button.1.dart **
/// {@end-tool}
///
/// See also:
///
/// [ElevatedButton], a filled button whose material elevates when pressed.
/// [FilledButton], a filled button that doesn't elevate when pressed.
/// [FilledButton.tonal], a filled button variant that uses a secondary fill color.
/// [OutlinedButton], a button with an outlined border and no fill color.
/// <https://material.io/design/components/buttons.html>
/// <https://m3.material.io/components/buttons>
/// FFI struct representation of TextButton widget.
/// This struct is used to pass widget data across the FFI boundary.
final class TextButtonStruct extends Struct {
  //FlutterObject Struct
  external Pointer handle;
  external Pointer managedHandle;
  external Pointer<Utf8> widgetType;
  //WidgetStruct
  external Pointer<Utf8> id;

  external Pointer<WidgetStruct> child;

  @Int8()
  external int hasOnPressedAction;

  external Pointer<Utf8> onPressedAction;

  @Int8()
  external int hasOnLongPressAction;

  external Pointer<Utf8> onLongPressAction;

  @Int8()
  external int hasOnHoverAction;

  external Pointer<Utf8> onHoverAction;

  @Int8()
  external int hasOnFocusChangeAction;

  external Pointer<Utf8> onFocusChangeAction;

  @Int8()
  external int hasStyle;

  external Pointer<Void> style;

  @Int8()
  external int hasFocusNode;

  external Pointer<FocusNodeStruct> focusNode;

  @Int8()
  external int autofocus;

  @Int8()
  external int hasClipBehavior;

  @Int32()
  external int clipBehavior;

  @Int8()
  external int hasStatesController;

  external Pointer<Void> statesController;

  @Int8()
  external int hasIsSemanticButton;

  @Int8()
  external int isSemanticButton;
}
